Add python bindings
applied-material-modeling/neml2 pull request #110
Opened 2023-11-11 01:18 UTC by hugary1995

Add python bindings
    
* Set up pybind11
* Set up pytest

CMake configure
    
- Let CMake generate config.h
- Let CMake generate conftest.py for pytest
- Use symlink for test artifacts when we are doing development (when .git folder is present)
- Fix dynamic section name with symlink
- Adapted the test workflow for pytest, let's see if it works

2023-11-11 03:06 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>90.19%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>89.29%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/NEML2Object.h#L50'>50</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>43.87%</b></td><td><b>79.49%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/OptionSet.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/OptionSet.h#L123'>123</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/OptionSet.h#L135'>135</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/OptionSet.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/OptionSet.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/OptionSet.h#L82'>82</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>96.34%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/UniqueVector.h'>UniqueVector.h</a></td><td>100%</td><td><b>17.86%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/UniqueVector.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/UniqueVector.h#L169'>169</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/base/UniqueVector.h#L171-L172'>171&ndash;172</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>37.67%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>53.13%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>63.77%</b></td><td><b>76.27%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/misc/utils.h#L173'>173</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/misc/utils.h#L239'>239</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/misc/utils.h#L241-L246'>241&ndash;246</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/misc/utils.h#L267'>267</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/misc/utils.h#L302'>302</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/misc/utils.h#L304-L307'>304&ndash;307</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/models/BufferStore.h'>BufferStore.h</a></td><td>100%</td><td><b>47.06%</b></td><td><b>58.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/models/BufferStore.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/models/BufferStore.h#L108'>108</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/models/BufferStore.h#L110-L111'>110&ndash;111</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/models/BufferStore.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/models/BufferStore.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/50af43b6c72ad690c633cbd3b40e2764a23ff4cd/include/neml2/models/BufferStore.h#L130- [...]

2023-11-11 05:53 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>90.19%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>89.29%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/NEML2Object.h#L50'>50</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>43.87%</b></td><td><b>79.49%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/OptionSet.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/OptionSet.h#L123'>123</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/OptionSet.h#L135'>135</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/OptionSet.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/OptionSet.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/OptionSet.h#L82'>82</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>96.34%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/UniqueVector.h'>UniqueVector.h</a></td><td>100%</td><td><b>17.86%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/UniqueVector.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/UniqueVector.h#L169'>169</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/base/UniqueVector.h#L171-L172'>171&ndash;172</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>37.67%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>53.13%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>63.77%</b></td><td><b>76.27%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/misc/utils.h#L173'>173</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/misc/utils.h#L239'>239</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/misc/utils.h#L241-L246'>241&ndash;246</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/misc/utils.h#L267'>267</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/misc/utils.h#L302'>302</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/misc/utils.h#L304-L307'>304&ndash;307</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/models/BufferStore.h'>BufferStore.h</a></td><td>100%</td><td><b>47.06%</b></td><td><b>58.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/models/BufferStore.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/models/BufferStore.h#L108'>108</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/models/BufferStore.h#L110-L111'>110&ndash;111</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/models/BufferStore.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/models/BufferStore.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/bb086d884c6e126ac6520eb38bf17b0916f9ca9d/include/neml2/models/BufferStore.h#L130- [...]

2023-11-13 20:44 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>90.19%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>89.29%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/NEML2Object.h#L50'>50</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>43.87%</b></td><td><b>79.49%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/OptionSet.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/OptionSet.h#L123'>123</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/OptionSet.h#L135'>135</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/OptionSet.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/OptionSet.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/OptionSet.h#L82'>82</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>96.34%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/UniqueVector.h'>UniqueVector.h</a></td><td>100%</td><td><b>17.86%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/UniqueVector.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/UniqueVector.h#L169'>169</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/base/UniqueVector.h#L171-L172'>171&ndash;172</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>37.67%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>53.13%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>63.77%</b></td><td><b>76.27%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/misc/utils.h#L173'>173</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/misc/utils.h#L239'>239</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/misc/utils.h#L241-L246'>241&ndash;246</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/misc/utils.h#L267'>267</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/misc/utils.h#L302'>302</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/misc/utils.h#L304-L307'>304&ndash;307</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/models/BufferStore.h'>BufferStore.h</a></td><td>100%</td><td><b>47.06%</b></td><td><b>58.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/models/BufferStore.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/models/BufferStore.h#L108'>108</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/models/BufferStore.h#L110-L111'>110&ndash;111</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/models/BufferStore.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/models/BufferStore.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8c6ade2c2c6b84ad40813b3456de23049206417/include/neml2/models/BufferStore.h#L130- [...]

2023-11-13 23:50 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>90.19%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>89.29%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/NEML2Object.h#L50'>50</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>43.87%</b></td><td><b>79.49%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/OptionSet.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/OptionSet.h#L123'>123</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/OptionSet.h#L135'>135</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/OptionSet.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/OptionSet.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/OptionSet.h#L82'>82</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>96.34%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/UniqueVector.h'>UniqueVector.h</a></td><td>100%</td><td><b>17.86%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/UniqueVector.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/UniqueVector.h#L169'>169</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/base/UniqueVector.h#L171-L172'>171&ndash;172</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>37.67%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>53.13%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>63.77%</b></td><td><b>76.27%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/misc/utils.h#L173'>173</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/misc/utils.h#L239'>239</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/misc/utils.h#L241-L246'>241&ndash;246</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/misc/utils.h#L267'>267</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/misc/utils.h#L302'>302</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/misc/utils.h#L304-L307'>304&ndash;307</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/models/BufferStore.h'>BufferStore.h</a></td><td>100%</td><td><b>47.06%</b></td><td><b>58.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/models/BufferStore.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/models/BufferStore.h#L108'>108</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/models/BufferStore.h#L110-L111'>110&ndash;111</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/models/BufferStore.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/models/BufferStore.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/00bae23b94454837c3b5c4540d4af5b6514c8ab3/include/neml2/models/BufferStore.h#L130- [...]

2023-11-14 04:47 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>90.19%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>89.29%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/NEML2Object.h#L50'>50</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>43.87%</b></td><td><b>79.49%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/OptionSet.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/OptionSet.h#L123'>123</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/OptionSet.h#L135'>135</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/OptionSet.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/OptionSet.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/OptionSet.h#L82'>82</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>96.34%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/UniqueVector.h'>UniqueVector.h</a></td><td>100%</td><td><b>17.86%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/UniqueVector.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/UniqueVector.h#L169'>169</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/base/UniqueVector.h#L171-L172'>171&ndash;172</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>37.67%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>53.13%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>63.77%</b></td><td><b>76.27%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/misc/utils.h#L173'>173</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/misc/utils.h#L239'>239</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/misc/utils.h#L241-L246'>241&ndash;246</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/misc/utils.h#L267'>267</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/misc/utils.h#L302'>302</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/misc/utils.h#L304-L307'>304&ndash;307</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/models/BufferStore.h'>BufferStore.h</a></td><td>100%</td><td><b>47.06%</b></td><td><b>58.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/models/BufferStore.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/models/BufferStore.h#L108'>108</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/models/BufferStore.h#L110-L111'>110&ndash;111</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/models/BufferStore.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/models/BufferStore.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/de60a6a6ff27de05618a9b881bb1dfadcc04b0c0/include/neml2/models/BufferStore.h#L130- [...]

2023-11-14 22:06 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>90.19%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>89.29%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/NEML2Object.h#L50'>50</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>43.87%</b></td><td><b>79.49%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/OptionSet.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/OptionSet.h#L123'>123</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/OptionSet.h#L135'>135</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/OptionSet.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/OptionSet.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/OptionSet.h#L82'>82</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>96.34%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/UniqueVector.h'>UniqueVector.h</a></td><td>100%</td><td><b>17.86%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/UniqueVector.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/UniqueVector.h#L169'>169</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/base/UniqueVector.h#L171-L172'>171&ndash;172</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>37.67%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>53.13%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>63.77%</b></td><td><b>76.27%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/misc/utils.h#L173'>173</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/misc/utils.h#L239'>239</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/misc/utils.h#L241-L246'>241&ndash;246</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/misc/utils.h#L267'>267</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/misc/utils.h#L302'>302</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/misc/utils.h#L304-L307'>304&ndash;307</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/models/BufferStore.h'>BufferStore.h</a></td><td>100%</td><td><b>47.06%</b></td><td><b>58.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/models/BufferStore.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/models/BufferStore.h#L108'>108</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/models/BufferStore.h#L110-L111'>110&ndash;111</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/models/BufferStore.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/models/BufferStore.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/58e6338bd882929b94bf5d98b5350d7184ae92ef/include/neml2/models/BufferStore.h#L130- [...]

2023-11-14 23:01 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>90.19%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>89.29%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/NEML2Object.h#L50'>50</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>43.87%</b></td><td><b>79.49%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/OptionSet.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/OptionSet.h#L123'>123</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/OptionSet.h#L135'>135</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/OptionSet.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/OptionSet.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/OptionSet.h#L82'>82</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>96.34%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/UniqueVector.h'>UniqueVector.h</a></td><td>100%</td><td><b>17.86%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/UniqueVector.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/UniqueVector.h#L169'>169</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/base/UniqueVector.h#L171-L172'>171&ndash;172</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>37.67%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>53.13%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>63.77%</b></td><td><b>76.27%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/misc/utils.h#L173'>173</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/misc/utils.h#L239'>239</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/misc/utils.h#L241-L246'>241&ndash;246</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/misc/utils.h#L267'>267</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/misc/utils.h#L302'>302</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/misc/utils.h#L304-L307'>304&ndash;307</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/models/BufferStore.h'>BufferStore.h</a></td><td>100%</td><td><b>47.06%</b></td><td><b>58.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/models/BufferStore.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/models/BufferStore.h#L108'>108</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/models/BufferStore.h#L110-L111'>110&ndash;111</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/models/BufferStore.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/models/BufferStore.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3a191c936172967e7f1f32a5a4dce0350adb4bb/include/neml2/models/BufferStore.h#L130- [...]

2023-11-15 00:23 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>90.19%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>89.29%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/NEML2Object.h#L50'>50</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>43.87%</b></td><td><b>79.49%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/OptionSet.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/OptionSet.h#L123'>123</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/OptionSet.h#L135'>135</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/OptionSet.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/OptionSet.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/OptionSet.h#L82'>82</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>96.34%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/UniqueVector.h'>UniqueVector.h</a></td><td>100%</td><td><b>17.86%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/UniqueVector.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/UniqueVector.h#L169'>169</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/base/UniqueVector.h#L171-L172'>171&ndash;172</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>37.67%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>53.13%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>63.77%</b></td><td><b>76.27%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/misc/utils.h#L173'>173</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/misc/utils.h#L239'>239</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/misc/utils.h#L241-L246'>241&ndash;246</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/misc/utils.h#L267'>267</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/misc/utils.h#L302'>302</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/misc/utils.h#L304-L307'>304&ndash;307</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/models/BufferStore.h'>BufferStore.h</a></td><td>100%</td><td><b>47.06%</b></td><td><b>58.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/models/BufferStore.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/models/BufferStore.h#L108'>108</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/models/BufferStore.h#L110-L111'>110&ndash;111</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/models/BufferStore.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/models/BufferStore.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/98b9ee9fc15629a0be72dc6f954f0485a0b9d40f/include/neml2/models/BufferStore.h#L130- [...]

2023-11-15 01:59 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>90.19%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>89.29%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/NEML2Object.h#L50'>50</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>43.87%</b></td><td><b>79.49%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/OptionSet.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/OptionSet.h#L123'>123</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/OptionSet.h#L135'>135</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/OptionSet.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/OptionSet.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/OptionSet.h#L82'>82</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>96.34%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/UniqueVector.h'>UniqueVector.h</a></td><td>100%</td><td><b>17.86%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/UniqueVector.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/UniqueVector.h#L169'>169</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/base/UniqueVector.h#L171-L172'>171&ndash;172</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>37.67%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>53.13%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>63.77%</b></td><td><b>76.27%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/misc/utils.h#L173'>173</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/misc/utils.h#L239'>239</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/misc/utils.h#L241-L246'>241&ndash;246</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/misc/utils.h#L267'>267</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/misc/utils.h#L302'>302</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/misc/utils.h#L304-L307'>304&ndash;307</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/models/BufferStore.h'>BufferStore.h</a></td><td>100%</td><td><b>47.06%</b></td><td><b>58.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/models/BufferStore.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/models/BufferStore.h#L108'>108</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/models/BufferStore.h#L110-L111'>110&ndash;111</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/models/BufferStore.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/models/BufferStore.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/91a26f72012618839ff7881b6c6335a3821089b3/include/neml2/models/BufferStore.h#L130- [...]

2023-11-15 16:18 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>90.19%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>89.29%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/NEML2Object.h#L50'>50</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>43.87%</b></td><td><b>79.49%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/OptionSet.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/OptionSet.h#L123'>123</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/OptionSet.h#L135'>135</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/OptionSet.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/OptionSet.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/OptionSet.h#L82'>82</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>96.34%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/UniqueVector.h'>UniqueVector.h</a></td><td>100%</td><td><b>17.86%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/UniqueVector.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/UniqueVector.h#L169'>169</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/base/UniqueVector.h#L171-L172'>171&ndash;172</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>37.67%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>53.13%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>63.77%</b></td><td><b>76.27%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/misc/utils.h#L173'>173</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/misc/utils.h#L239'>239</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/misc/utils.h#L241-L246'>241&ndash;246</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/misc/utils.h#L267'>267</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/misc/utils.h#L302'>302</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/misc/utils.h#L304-L307'>304&ndash;307</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/models/BufferStore.h'>BufferStore.h</a></td><td>100%</td><td><b>47.06%</b></td><td><b>58.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/models/BufferStore.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/models/BufferStore.h#L108'>108</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/models/BufferStore.h#L110-L111'>110&ndash;111</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/models/BufferStore.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/models/BufferStore.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/82b54608f7a29b81ac8238483d503b2c41c63dfc/include/neml2/models/BufferStore.h#L130- [...]

2023-11-16 01:17 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>90.19%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>89.29%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/NEML2Object.h#L50'>50</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>43.87%</b></td><td><b>79.49%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/OptionSet.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/OptionSet.h#L123'>123</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/OptionSet.h#L135'>135</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/OptionSet.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/OptionSet.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/OptionSet.h#L82'>82</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>96.34%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/UniqueVector.h'>UniqueVector.h</a></td><td>100%</td><td><b>17.86%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/UniqueVector.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/UniqueVector.h#L169'>169</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/base/UniqueVector.h#L171-L172'>171&ndash;172</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>37.67%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>53.13%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>63.77%</b></td><td><b>76.27%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/misc/utils.h#L173'>173</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/misc/utils.h#L239'>239</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/misc/utils.h#L241-L246'>241&ndash;246</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/misc/utils.h#L267'>267</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/misc/utils.h#L302'>302</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/misc/utils.h#L304-L307'>304&ndash;307</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/models/BufferStore.h'>BufferStore.h</a></td><td>100%</td><td><b>47.06%</b></td><td><b>58.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/models/BufferStore.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/models/BufferStore.h#L108'>108</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/models/BufferStore.h#L110-L111'>110&ndash;111</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/models/BufferStore.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/models/BufferStore.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/9d71263adcc6f66493e436cbd262d4c6d367ea7d/include/neml2/models/BufferStore.h#L130- [...]

2023-11-16 07:15 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>90.19%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>89.29%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/NEML2Object.h#L50'>50</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>43.87%</b></td><td><b>79.49%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/OptionSet.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/OptionSet.h#L123'>123</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/OptionSet.h#L135'>135</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/OptionSet.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/OptionSet.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/OptionSet.h#L82'>82</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>96.34%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/UniqueVector.h'>UniqueVector.h</a></td><td>100%</td><td><b>17.86%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/UniqueVector.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/UniqueVector.h#L169'>169</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/base/UniqueVector.h#L171-L172'>171&ndash;172</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>37.67%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>53.13%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>63.77%</b></td><td><b>76.27%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/misc/utils.h#L173'>173</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/misc/utils.h#L239'>239</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/misc/utils.h#L241-L246'>241&ndash;246</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/misc/utils.h#L267'>267</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/misc/utils.h#L302'>302</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/misc/utils.h#L304-L307'>304&ndash;307</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/models/BufferStore.h'>BufferStore.h</a></td><td>100%</td><td><b>47.06%</b></td><td><b>58.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/models/BufferStore.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/models/BufferStore.h#L108'>108</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/models/BufferStore.h#L110-L111'>110&ndash;111</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/models/BufferStore.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/models/BufferStore.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/a85c80c982e1d13dff77e5737b79ce3b85cee763/include/neml2/models/BufferStore.h#L130- [...]

2023-12-10 21:13 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>89.78%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>86.15%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/CrossRef.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/CrossRef.h#L95-L96'>95&ndash;96</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>9.38%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>50%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/NEML2Object.h#L50'>50</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>43.69%</b></td><td><b>79.49%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/OptionSet.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/OptionSet.h#L123'>123</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/OptionSet.h#L135'>135</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/OptionSet.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/OptionSet.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/OptionSet.h#L82'>82</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>89.16%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/UniqueVector.h'>UniqueVector.h</a></td><td>100%</td><td><b>14.29%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/UniqueVector.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/UniqueVector.h#L169'>169</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/base/UniqueVector.h#L171-L172'>171&ndash;172</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.03%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>48.57%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>63.04%</b></td><td><b>76.27%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/misc/utils.h#L173'>173</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/misc/utils.h#L239'>239</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/misc/utils.h#L241-L246'>241&ndash;246</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/misc/utils.h#L267'>267</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/misc/utils.h#L302'>302</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/misc/utils.h#L304-L307'>304&ndash;307</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/models/BufferStore.h'>BufferStore.h</a></td><td>100%</td><td><b>44.44%</b></td><td><b>58.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/models/BufferStore.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/models/BufferStore.h#L108'>108</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/models/BufferStore.h#L110-L111'>110&ndash;111</a>, <a href='https://github.com/reverendbedford/neml2/blob/22916025781edfa89a133801de3b03f961b38524/include/neml2/models/BufferStore.h#L113-L114'>113& [...]

2023-12-10 23:45 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>89.78%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>86.15%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/CrossRef.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/CrossRef.h#L95-L96'>95&ndash;96</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>9.38%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>50%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/NEML2Object.h#L50'>50</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>43.69%</b></td><td><b>79.49%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/OptionSet.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/OptionSet.h#L123'>123</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/OptionSet.h#L135'>135</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/OptionSet.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/OptionSet.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/OptionSet.h#L82'>82</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>89.16%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/UniqueVector.h'>UniqueVector.h</a></td><td>100%</td><td><b>14.29%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/UniqueVector.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/UniqueVector.h#L169'>169</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/base/UniqueVector.h#L171-L172'>171&ndash;172</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.03%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>48.57%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>63.04%</b></td><td><b>76.27%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/misc/utils.h#L173'>173</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/misc/utils.h#L239'>239</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/misc/utils.h#L241-L246'>241&ndash;246</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/misc/utils.h#L267'>267</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/misc/utils.h#L302'>302</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/misc/utils.h#L304-L307'>304&ndash;307</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/models/BufferStore.h'>BufferStore.h</a></td><td>100%</td><td><b>44.44%</b></td><td><b>58.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/models/BufferStore.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/models/BufferStore.h#L108'>108</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/models/BufferStore.h#L110-L111'>110&ndash;111</a>, <a href='https://github.com/reverendbedford/neml2/blob/edf4888d708a4fb4e4bba5195c2d7bc42613cc7e/include/neml2/models/BufferStore.h#L113-L114'>113& [...]

2023-12-11 14:45 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>89.78%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>86.15%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/CrossRef.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/CrossRef.h#L95-L96'>95&ndash;96</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>9.38%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>50%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/NEML2Object.h#L50'>50</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>43.69%</b></td><td><b>79.49%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/OptionSet.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/OptionSet.h#L123'>123</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/OptionSet.h#L135'>135</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/OptionSet.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/OptionSet.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/OptionSet.h#L82'>82</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>89.16%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/UniqueVector.h'>UniqueVector.h</a></td><td>100%</td><td><b>14.29%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/UniqueVector.h#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/UniqueVector.h#L169'>169</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/base/UniqueVector.h#L171-L172'>171&ndash;172</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.03%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>48.57%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>63.04%</b></td><td><b>76.27%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/misc/utils.h#L173'>173</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/misc/utils.h#L239'>239</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/misc/utils.h#L241-L246'>241&ndash;246</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/misc/utils.h#L267'>267</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/misc/utils.h#L302'>302</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/misc/utils.h#L304-L307'>304&ndash;307</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/models/BufferStore.h'>BufferStore.h</a></td><td>100%</td><td><b>44.44%</b></td><td><b>58.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/models/BufferStore.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/models/BufferStore.h#L108'>108</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/models/BufferStore.h#L110-L111'>110&ndash;111</a>, <a href='https://github.com/reverendbedford/neml2/blob/b67e7b2cd4f145940912df35e364583c43cf327d/include/neml2/models/BufferStore.h#L113-L114'>113& [...]

2023-12-18 23:54 UTC, reverendbedford requested changes
1. Things seem to break with torch 2.01.  We should try to be backwards compatible, at least for torch 2.x.
2. It may be worthwhile to setup the basic python packaging stuff now (i.e. a `setup.py`).  I don't know if we'll ever want to make this available as a python package directly, but we might.  And I'm not sure how compatible your directory layout here will be if we do that.  You can look at NEML for a `setup.py` that works with cmake.
3. What is the actual minimum torch and python version required?  If we really need python3.11 that could be annoying, as it's not standard on Ubuntu yet.
4. The tests error on python3.10 with a legitimate syntax error.  Probably should fix that unless 3.11 is really needed.
5. We should have the python tests loop over python versions in our valid range.  Maybe the same thing with torch, but I'm okay with just forcing people to 2.1 if that's what's needed.

2023-12-18 23:54 UTC, reverendbedford commented on CMakeLists.txt
> +if(POLICY CMP0094)
For my information, why is this needed?

2023-12-18 23:54 UTC, reverendbedford commented on CMakeLists.txt
> -# Select between system torch and the current (CPU) torch
Can we separate all these policy checks into a separate file using `include`?

2023-12-18 23:54 UTC, reverendbedford commented on doc/content/_01_install.md
> +There are many ways of installing the Nvidia driver and the CUDA toolkit. We will not try to make a recommendation here. However, do make sure the Nvidia driver is compatible with your GPU (See e.g.
NVIDIA

2023-12-18 23:54 UTC, reverendbedford commented on include/neml2/tensors/WR2.h
Oh, these come from `VecBase`...

2023-12-18 23:54 UTC, reverendbedford commented on include/neml2/tensors/macros.h
I updated these on the basic_cp branch, so we'll just have to watch out when we merge.

2023-12-18 23:54 UTC, reverendbedford commented on python/neml2_wrap/tensors/FixedDimTensor.h
> +  // Ctors, conversions, accessros etc.
spelling

2023-12-18 23:54 UTC, reverendbedford commented on python/neml2_wrap/tensors/Rot.cxx
> +  // Ctors, conversions, accessros etc.
Just do a `sed` to fix them, I'll stop commenting.

2023-12-18 23:54 UTC, reverendbedford commented on python/neml2_wrap/tensors/tensors.cxx
> +  // #define TENSORS_DEF_T(T) def_##T(m)
Why did you go with the manual list?

2024-02-21 02:49 UTC, hugary1995 commented on CMakeLists.txt
> +if(POLICY CMP0094)
I think I got some warnings without explicitly telling cmake which behavior to use.

2024-02-21 02:59 UTC, hugary1995 commented
> 1. It may be worthwhile to setup the basic python packaging stuff now (i.e. a `setup.py`).  I don't know if we'll ever want to make this available as a python package directly, but we might.  And I'm not sure how compatible your directory layout here will be if we do that.  You can look at NEML for a `setup.py` that works with cmake.

I'll try to add a pyproject.toml

> 2. What is the actual minimum torch and python version required?  If we really need python3.11 that could be annoying, as it's not standard on Ubuntu yet.
> 3. The tests error on python3.10 with a legitimate syntax error.  Probably should fix that unless 3.11 is really needed.

I dropped the 3.11 requirement and fixed the unpacking syntax error.

> 4. We should have the python test action loop over python versions in our valid range.  Maybe the same thing with torch, but I'm okay with just forcing people to 2.1 if that's what's needed.

I agree, if not github does not have any limit on the number of checks...

2024-02-21 03:27 UTC, hugary1995 commented
lol I forgot ubuntu 22.04 does not have python 3.6 in the main universe. Should we switch to conda or just drop python 3.6 support? I'm fine with either solution.

2024-02-21 04:16 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>88.51%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f225827eb809a9b5d5/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3b02d7f9783bee766e3903f2258 [...]

2024-02-21 04:39 UTC, hugary1995 commented on CMakeLists.txt
> -# Select between system torch and the current (CPU) torch
I tried this: separating policies into a file and include them in CMakeLists.txt. The policies then take no effect as if the include did nothing. Perhaps I did something, but for now I rolled back to the original version -- these policies are kept within the main CMakeLists.txt.

2024-02-21 05:30 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>88.51%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735ffadf8c020e66d/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8936067b77935595f2bd15a735f [...]

2024-02-23 01:38 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>88.51%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e225381ba7cb12f27fa/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0a90bced264ac14074048e22538 [...]

2024-02-23 05:49 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>88.51%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e15ae8a54af267/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a8ee33d4abb14178114e90b662e [...]

2024-02-23 15:01 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>88.51%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e944db2f4d26d2e/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/4a83d37724da3607950a40231e9 [...]

2024-02-24 04:39 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.79%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64ee42be1c088cf/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/771574292ecd47af06a53c6ea64 [...]

2024-02-24 17:29 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.79%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2ddd02a6d513ca8/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7efa1ca4e0b7113f106d4ebda2d [...]

2024-02-24 19:37 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.79%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac5567c26b0f25a75a/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/448dd47a264da53eef1722ac556 [...]

2024-02-24 20:26 UTC, hugary1995 commented
This is ready again.

2024-02-24 21:01 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.79%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd70173cb588ac36/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b125e393f732d02d426294abfd7 [...]

2024-02-25 03:53 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.79%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2153b8df9e856d/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/98968c76930cf1a2ad968c95fe2 [...]

2024-03-07 16:27 UTC, reverendbedford requested changes
1. Add check that the python source has been blacked (`black --check`).
2. I have a fun bug where I installed the package, uninstalled it, and then tried to install it again.  It will not build.  The problem is with linking to torch.  Delete the build folder and trying again fixed the issue.  Uhh, maybe try it on Linux and see what happens?
3. It would be nice to be able to construct both `BatchTensor` and the derived classes of `FixedDimTensor` from torch tensors and numpy arrays.  I think you just need to implement the `torch.tensor` variant and then rely on the torch tensor constructor to handle the rest of the conversions.  They must have a "ensure_tensor" or similar method like numpy.  For `BatchTensor` the user would supply the tensor and an `int` indicating the separation between the batch and base dims.  For `FixedDimTensor` we should be able to infer all the dimensions (and throw if necessary) without help.
4. I don't think you test the `torch.tensor` view into our classes.  A few simple tests would be nice (values are the same, if you change the tensor view you change the underlying neml2 tensor data, devices are the same).
5.

2024-03-07 16:27 UTC, reverendbedford commented on .github/workflows/tests.yml
> +      fail-fast: false
You want this long term?

2024-03-07 16:27 UTC, reverendbedford commented on .github/workflows/tests.yml
> +              neml2::Registry::print(std::cout);\n\
I take it you want this in the final tests.

2024-03-07 16:27 UTC, reverendbedford commented on CMakeLists.txt
> +      if(Python_Interpreter_FOUND)
Okay...  I feel like we should rely on cmake, not python, if at all possible as this now requires python even to build a no-bindings version of the library.

2024-03-07 16:27 UTC, reverendbedford commented on include/neml2/base/config.h.in
> +#cmakedefine NEML2_SOURCE_DIR "@NEML2_SOURCE_DIR@"
I may find out, but what do we used hard-coded directory names for?

2024-03-07 16:27 UTC, reverendbedford commented on include/neml2/models/crystallography/MillerIndex.h
> -namespace crystallography
Why can't we use sub name spaces anymore?

2024-03-07 16:27 UTC, reverendbedford commented on python/CMakeLists.txt
> +# Binary Python modules (such as pybind11 bindings) don't work well with
We want this commented out?

2024-03-07 16:27 UTC, reverendbedford commented on python/CMakeLists.txt
> +message(STATUS "Found libTorch Python binding: ${LIBTORCH_PYTHON}")
I hate it when CMake prints...  Unless we really, really need this I would get rid of it.

2024-03-07 16:27 UTC, reverendbedford commented on python/neml2_wrap/misc/math.cxx
> +  m.def("bmm", &math::bmm);
I feel like I added a few generalized batch linear algebra methods...  Or did those get eliminated?

2024-03-07 16:27 UTC, reverendbedford commented on python/neml2_wrap/misc/types.h
> + * @brief This instantiation enables type conversion between Python object <--> torch::Dtype
dtype

2024-03-07 16:27 UTC, reverendbedford commented on scripts/find_torch.py
If we have no choice this is fine, but I really feel like this should be done with a CMake find script rather than python.

2024-03-07 16:27 UTC, reverendbedford commented on setup.py
> +        if platform.system() == "Windows":
We will have to figure this out if neml2 gets popular, but I guess we can put it off for now.  I never really managed to get it to work with NEML.

2024-03-08 15:16 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.79%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356709614bf415f0/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2c9283d02493cc6c3ec3e680356 [...]

2024-03-08 20:45 UTC, hugary1995 commented on .github/workflows/tests.yml
> +      fail-fast: false
I do. See docs here https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

We use the matrix strategy to test different platforms. If the ubuntu test fails, I still want to mac test to continue.

2024-03-08 20:45 UTC, hugary1995 commented on .github/workflows/tests.yml
> +              neml2::Registry::print(std::cout);\n\
ya, this is probably the easiest way to make sure all the objects are registered and manufacturable.

2024-03-08 20:47 UTC, hugary1995 commented on include/neml2/base/config.h.in
> +#cmakedefine NEML2_SOURCE_DIR "@NEML2_SOURCE_DIR@"
This is for fixing the relative path when we install test artifacts by synlink (during development). I guess I can move this into `tests/include/config.h.in` instead.

2024-03-08 20:47 UTC, hugary1995 commented on include/neml2/models/crystallography/MillerIndex.h
> -namespace crystallography
The nested namespace destroys my beautiful tensor macros :)

2024-03-08 20:49 UTC, hugary1995 commented on python/CMakeLists.txt
> +# Binary Python modules (such as pybind11 bindings) don't work well with
I forgot to uncomment this.

2024-03-08 20:50 UTC, hugary1995 commented on python/CMakeLists.txt
> +message(STATUS "Found libTorch Python binding: ${LIBTORCH_PYTHON}")
Agreed.

2024-03-08 20:52 UTC, hugary1995 commented on python/neml2_wrap/misc/math.cxx
> +  m.def("bmm", &math::bmm);
I'll add them here.

2024-03-08 20:53 UTC, hugary1995 commented on setup.py
> +        if platform.system() == "Windows":
We'll send people to WSL for now, I guess.

2024-03-08 23:01 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.79%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba89973f65f2ba02/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bdb4167990c66ec6c93a0c60ba8 [...]

2024-03-09 00:01 UTC, hugary1995 commented on include/neml2/base/config.h.in
> +#cmakedefine NEML2_SOURCE_DIR "@NEML2_SOURCE_DIR@"
I removed these hard-coded paths entirely.

2024-03-09 00:04 UTC, hugary1995 commented
I searched online but couldn't find any way of locating the pytorch package without first finding python.

I would argue that what I have right now is fine, because if python is not found, it will merrily fall back to plan B (downloading a cpu libtorch). So strictly speaking, we are not introducing python as a dependency (if we are not going to compile python bindings).

2024-03-09 00:04 UTC, hugary1995 commented on CMakeLists.txt
> +      if(Python_Interpreter_FOUND)
See my comment below. Feel free to unresolve this if you want to discuss further.

2024-03-09 00:04 UTC, hugary1995 commented on scripts/find_torch.py
See my comment below. Feel free to unresolve this if you want to discuss further.

2024-03-09 00:06 UTC, hugary1995 commented
Also note that I renamed the github workflow recipe "Formatting Check" to "C++ Formatting Check" (because we now have a "Python Formatting Check"). So you will need to modify the list of expected checks.

2024-03-09 01:07 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.79%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9fcd7a37c787e79/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a015ee98268980565f15237ee9f [...]

2024-03-09 02:32 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.79%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d18ceb2597391a/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/87f8fd3c0724c190faf417cef4d [...]

2024-03-09 05:28 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.79%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf682bdf1efeb890d/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ca3dec8a2d8f6d908efbb6acf68 [...]

2024-03-09 06:36 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.79%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d9bf2bf05619f8/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3c5e8f27b6338bb791d5700ca5d [...]

2024-03-09 13:31 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.79%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856d9259cfd5d8e5/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/270dd1eb19127f7924cbdf2c856 [...]

2024-03-09 15:48 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.79%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b10de13526b6f24/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b12ecad5652f78de3429c5d51b1 [...]

2024-03-09 22:04 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.79%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7c43089bbf98ee/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/43b118c1faad67bfcfdcf8069c7 [...]

2024-03-10 01:08 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.79%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f6089636dc60a4e79a16/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3f305c030e922954453f608963 [...]

2024-03-10 04:46 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.79%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b0b12fe6545db2/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd831def690c6d21b61a1620e9b [...]

2024-03-12 03:18 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.79%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>79.01%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>39.89%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>33.33%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637441a44dcb4e69/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8364cd528699ce2ef048b9d637 [...]

2024-04-04 21:16 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.62%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>77.78%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>22.22%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>36.07%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>32.06%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8ddf706f9e6fb8/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dd5e6264fd53d9069c15c14eec8 [...]

2024-04-05 22:19 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.62%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>77.78%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>22.22%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>36.07%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>32.06%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c4c8d8223832ca/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/689735347905d6c1a9328e0e75c [...]

2024-04-06 14:27 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.62%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>77.78%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>22.22%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>36.07%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>32.06%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527c92c4593c94a0/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/783389ae3d3f462a248940e3527 [...]

2024-04-06 21:34 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.62%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>77.78%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>22.22%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>36.07%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>32.06%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c85b391481aece/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b1085cc564126fffa9c2b81b02c [...]

2024-04-07 04:04 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.62%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>77.78%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>22.22%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>36.07%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>32.06%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6ebf1cfb01ba2cb0/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/70aa7986d17b8eb311908a8e6eb [...]

2024-04-07 19:12 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.62%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>77.78%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>22.22%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>36.07%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>31.96%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c1c7889ebac7e0/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7cf3ee4ee69b7f42293b710971c [...]

2024-04-08 01:45 UTC, hugary1995 commented
A few "new" things to review:
1. I reworked the CMakeLists.txt to enable various build configurations, including wheels.
2. I added bindings for Factory, HITParser, LabeledTensor, Model so that basic python workflow works, i.e. loading a model from an input file, use the loaded model to give value and derivatives, etc.
3. I added a cmake-variants.yaml to the repo root for vscode users.

I let the wheels use a special rpath to avoid bundling all the libtorch dependencies into our wheel. We probably want to discuss about this.

2024-04-08 01:47 UTC, hugary1995 commented
I haven't added the "upload to pypi" step yet. We may want to play with the wheels on more machines before uploading to pypi...

2024-04-08 02:12 UTC, hugary1995 commented
At a higher level, we should probably think about how to auto-update python wheels to stay up-to-date with pytorch updates. I am also not entirely satisfied with the hard-coded torch versions scattered across the repository.

2024-04-08 02:43 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.62%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>77.78%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>22.22%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>36.07%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>31.96%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f623353ac880b836b41/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/147a2d8dc87abaeda3374f62335 [...]

2024-04-09 03:23 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b><table><tbody><tr><th>87.74%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>77.78%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>22.22%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>36.07%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/Storage.h'>Storage.h</a></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>31.96%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5fcfd8e47ee1f61/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/519ca99902010480632920d6a5f [...]

2024-04-09 14:28 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b> will be<table><tbody><tr><th>87.74%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>80.43%</b></td><td>100%</td><td><b>77.78%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>28%</b></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>37.50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.75%</b></td><td>100%</td><td><b>36.07%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>83.83%</b></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='6'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/drivers/Driver.h'>Driver.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td><b>85.71%</b></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='6'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/misc/error.h'>error.h</a></td><td><b>34.36%</b></td><td>100%</td><td><b>31.96%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3e450af04090791f9471e44ae70aae70950c85b/include/neml2/misc/error.h#L35-L36'>35&ndash;36 [...]

2024-04-09 15:45 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b> will be<table><tbody><tr><th>87.74%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>80.43%</b></td><td>100%</td><td><b>77.78%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>28%</b></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>37.50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.75%</b></td><td>100%</td><td><b>36.07%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>83.83%</b></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='6'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/drivers/Driver.h'>Driver.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td><b>85.71%</b></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='6'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/misc/error.h'>error.h</a></td><td><b>34.36%</b></td><td>100%</td><td><b>31.96%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/daed5f052f9bc7afafe46bb49eb7313293030688/include/neml2/misc/error.h#L35-L36'>35&ndash;36 [...]

2024-04-09 17:12 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b> will be<table><tbody><tr><th>87.74%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>80.43%</b></td><td>100%</td><td><b>77.78%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>28%</b></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>37.50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.75%</b></td><td>100%</td><td><b>36.07%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>83.83%</b></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='6'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/drivers/Driver.h'>Driver.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td><b>85.71%</b></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='6'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/misc/error.h'>error.h</a></td><td><b>34.36%</b></td><td>100%</td><td><b>31.96%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/d139efce9c037ec709286ca7d009bba0969cfcae/include/neml2/misc/error.h#L35-L36'>35&ndash;36 [...]

2024-04-15 16:24 UTC, reverendbedford requested changes
1. See comment on minimum cmake version.
2. We should probably include "build and test" for python bindings in the github actions.
3. I suggest have a `load_model` helper that combines `load_input` and `get_model`.
4. Perhaps add a parameter partial type test to `test_model.py` as that's going to be important shortly.

I will make a new PR to actually upload the pypi package after we merge this.

Good work, nearly done!

2024-04-15 16:24 UTC, reverendbedford commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.21)
I think it's 3.23

2024-04-16 13:33 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b> will be<table><tbody><tr><th>87.74%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>80.43%</b></td><td>100%</td><td><b>77.78%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>28%</b></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>37.50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.75%</b></td><td>100%</td><td><b>36.07%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>83.83%</b></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='6'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/drivers/Driver.h'>Driver.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td><b>85.71%</b></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='6'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/misc/error.h'>error.h</a></td><td><b>34.36%</b></td><td>100%</td><td><b>31.96%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5a2975b1dcd7971cc6e1c33213547f6f69241b57/include/neml2/misc/error.h#L35-L36'>35&ndash;36 [...]

2024-04-16 17:03 UTC, hugary1995 commented
I opened a future issue after merging this PR: #130

2024-04-16 17:07 UTC, hugary1995 commented
And also #131

2024-04-16 18:05 UTC, reverendbedford commented
Coverage after merging <b>pybind</b> into <b>main</b> will be<table><tbody><tr><th>87.74%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>80.43%</b></td><td>100%</td><td><b>77.78%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>28%</b></td><td>100%</td><td><b>11.11%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>37.50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>57.14%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.75%</b></td><td>100%</td><td><b>36.07%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>83.83%</b></td><td>100%</td><td><b>83.61%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='6'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/drivers/Driver.h'>Driver.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td><b>85.71%</b></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='6'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/misc/error.h'>error.h</a></td><td><b>34.36%</b></td><td>100%</td><td><b>31.96%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6a60dd0abb5c31094f9cc8e74fd5766bd05bfae1/include/neml2/misc/error.h#L35-L36'>35&ndash;36 [...]

2024-04-17 17:59 UTC, reverendbedford approved these changes

2024-04-17 18:06 UTC, merged