FY24 documentation improvements (part 1)
applied-material-modeling/neml2 pull request #142
Opened 2024-05-02 22:22 UTC by hugary1995

Annual documentation season...

This is the first PR to document changes made in FY24

- Added a syntax executable under the doc folder to help extract all the syntax
- Change doxygen and doxygen-awesome-css from git submodules to cmake FetchContent
- Update doxygen and doxygen-awesome-css to their latest versions
- Reorganize documentation content to split user-facing and developer-facing content
- Update the installation guide
- Update the developer guide to reflect FY24 changes
- Improve syntax documentation: extract class documentation, list objects by section, etc.

A follow on PR will add the user guide.

2024-05-03 15:46 UTC, reverendbedford commented
Coverage after merging <b>doc</b> into <b>main</b> will be<table><tbody><tr><th>86.95%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/CrossRef.h#L101'>101</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/CrossRef.h#L103-L104'>103&ndash;104</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/CrossRef.h#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/CrossRef.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/CrossRef.h#L95-L96'>95&ndash;96</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.47%</b></td><td>100%</td><td><b>81.24%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/fc0af51af2a90e0dc9eb3fab5d74f36085eced8d/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td c [...]

2024-05-03 16:08 UTC, hugary1995 commented
Note that this PR gets rid of _all_ submodules. Now this relies on CMake's FetchContent to pull dependencies on-demand. I am now a huge fan of CMake's FetchContent idea, and I think its development has become mature especially now that we require a recent CMake.

2024-05-04 00:21 UTC, reverendbedford commented
Coverage after merging <b>doc</b> into <b>main</b> will be<table><tbody><tr><th>86.95%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/CrossRef.h#L101'>101</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/CrossRef.h#L103-L104'>103&ndash;104</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/CrossRef.h#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/CrossRef.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/CrossRef.h#L95-L96'>95&ndash;96</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.47%</b></td><td>100%</td><td><b>81.24%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/dcbb6600d2e15af9c69ee4f2116d6f37676dd1e0/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td c [...]

2024-05-06 12:46 UTC, reverendbedford commented
Coverage after merging <b>doc</b> into <b>main</b> will be<table><tbody><tr><th>86.95%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/CrossRef.h#L101'>101</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/CrossRef.h#L103-L104'>103&ndash;104</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/CrossRef.h#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/CrossRef.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/CrossRef.h#L95-L96'>95&ndash;96</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.47%</b></td><td>100%</td><td><b>81.24%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/29161007f274a35577b823f19b7c52a941fb517d/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td c [...]

2024-05-07 20:51 UTC, reverendbedford commented
Coverage after merging <b>doc</b> into <b>main</b> will be<table><tbody><tr><th>86.95%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/CrossRef.h#L101'>101</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/CrossRef.h#L103-L104'>103&ndash;104</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/CrossRef.h#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/CrossRef.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/CrossRef.h#L95-L96'>95&ndash;96</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.47%</b></td><td>100%</td><td><b>81.24%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/5db15f915233f47ac0a69bbc0a1d9720ecceaa42/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td c [...]

2024-05-14 19:50 UTC, reverendbedford commented
Coverage after merging <b>doc</b> into <b>main</b> will be<table><tbody><tr><th>86.99%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/CrossRef.h#L101'>101</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/CrossRef.h#L103-L104'>103&ndash;104</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/CrossRef.h#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/CrossRef.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/CrossRef.h#L95-L96'>95&ndash;96</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.47%</b></td><td>100%</td><td><b>81.24%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/be75a5750b4a342f8415a1d1690c5bddc9f88482/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td c [...]

2024-05-14 20:19 UTC, hugary1995 commented
ping @reverendbedford

2024-05-14 21:14 UTC, reverendbedford commented
Coverage after merging <b>doc</b> into <b>main</b> will be<table><tbody><tr><th>87.01%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/CrossRef.h#L101'>101</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/CrossRef.h#L103-L104'>103&ndash;104</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/CrossRef.h#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/CrossRef.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/CrossRef.h#L95-L96'>95&ndash;96</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.47%</b></td><td>100%</td><td><b>81.24%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/97dd57c32ea2b9df1db57f39a691e4f01fa1ff69/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td c [...]

2024-05-15 21:42 UTC, reverendbedford commented
Coverage after merging <b>doc</b> into <b>main</b> will be<table><tbody><tr><th>87.01%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/CrossRef.h#L101'>101</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/CrossRef.h#L103-L104'>103&ndash;104</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/CrossRef.h#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/CrossRef.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/CrossRef.h#L95-L96'>95&ndash;96</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.47%</b></td><td>100%</td><td><b>81.24%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/7e7d32395b9b25f3b9b20e8cc834b1489babcda8/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td c [...]

2024-05-17 22:02 UTC, reverendbedford commented
Coverage after merging <b>doc</b> into <b>main</b> will be<table><tbody><tr><th>87.01%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/CrossRef.h#L101'>101</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/CrossRef.h#L103-L104'>103&ndash;104</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/CrossRef.h#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/CrossRef.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/CrossRef.h#L95-L96'>95&ndash;96</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.47%</b></td><td>100%</td><td><b>81.24%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/b0543338d1f6e30efd93fc0a5a0e416f966ab0ec/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td c [...]

2024-05-20 17:47 UTC, reverendbedford commented
Coverage after merging <b>doc</b> into <b>main</b> will be<table><tbody><tr><th>87.01%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/CrossRef.h#L101'>101</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/CrossRef.h#L103-L104'>103&ndash;104</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/CrossRef.h#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/CrossRef.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/CrossRef.h#L95-L96'>95&ndash;96</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.47%</b></td><td>100%</td><td><b>81.24%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/74371f6926205564307267c9b53f15c59d59dd09/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td c [...]

2024-06-06 03:16 UTC, reverendbedford commented
Coverage after merging <b>doc</b> into <b>main</b> will be<table><tbody><tr><th>86.95%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/CrossRef.h#L101'>101</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/CrossRef.h#L103-L104'>103&ndash;104</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/CrossRef.h#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/CrossRef.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/CrossRef.h#L95-L96'>95&ndash;96</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.47%</b></td><td>100%</td><td><b>81.24%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/04964a05b56dca1220250e74a55ee58110d8f7fb/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td c [...]

2024-06-06 14:35 UTC, reverendbedford commented
Coverage after merging <b>doc</b> into <b>main</b> will be<table><tbody><tr><th>86.95%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/CrossRef.h#L101'>101</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/CrossRef.h#L103-L104'>103&ndash;104</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/CrossRef.h#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/CrossRef.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/CrossRef.h#L95-L96'>95&ndash;96</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.47%</b></td><td>100%</td><td><b>81.24%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/eb6245e68f1727afc69026af9eb136ebba13bee5/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td c [...]

2024-06-06 22:58 UTC, reverendbedford commented
Coverage after merging <b>doc</b> into <b>main</b> will be<table><tbody><tr><th>86.95%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/CrossRef.h#L101'>101</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/CrossRef.h#L103-L104'>103&ndash;104</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/CrossRef.h#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/CrossRef.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/CrossRef.h#L95-L96'>95&ndash;96</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.47%</b></td><td>100%</td><td><b>81.24%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/6cc74c69038f2a2acb5d181b3de112ab6ea8ccf1/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td c [...]

2024-06-12 02:19 UTC, reverendbedford requested changes
### For you
- Add some additional documentation on the use of the python bindings.
- Make some moderate effort to expand the object docstring and input documentation.  Doesn't have to be fully comprehensive, but if we don't work on that now it's never going to happen.

## For me
- Crystal plasticity docs.

## After this
- Issue a new major release (b/c of python changes)
- Update copyright year when we do that.

2024-06-12 02:19 UTC, reverendbedford commented on README.md
> +- **Strict quality assurance**: NEML2 is developed under a strict quality assurance program. Because the NEML2 distributions do not provide full, parameterized models for any actual materials, ensuri
Should we add something on multiphysics (or physics agnostic)?

- **Multiphysics**: NEML2 is not tied to an underlying problem physics.  Current modules cover thermal and mechanical material models, but the framework can be used to implement a wide range of constitutive models.  For coupled problems, NEML2 will return the exact, coupled Jacobian entries required to achieve optimal convergence for fully-coupled implementations.

2024-06-12 02:19 UTC, reverendbedford commented on doc/content/install.md
> +- **Recommended** If you choose to download PyTorch using conda or pip, the NEML2 CMake script can automatically detect and use the PyTorch installation.
**Recommended**: (with a colon)

2024-06-12 02:19 UTC, reverendbedford commented on doc/content/install.md
> +Commonly used configuration options are summarized below. Default options are underlined.
Might be nice to underline "underlined"

2024-06-12 02:19 UTC, reverendbedford commented on doc/content/getting_started.md
Might make sense to have a section that briefly explains/demos the "experimental" python bindings.

2024-06-12 02:19 UTC, reverendbedford commented on doc/content/physics/solid_mechanics.md
You want me to add some crystal plasticity documentation I take it...

2024-06-12 20:29 UTC, reverendbedford commented
Coverage after merging <b>doc</b> into <b>main</b> will be<table><tbody><tr><th>86.95%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/CrossRef.h#L101'>101</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/CrossRef.h#L103-L104'>103&ndash;104</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/CrossRef.h#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/CrossRef.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/CrossRef.h#L95-L96'>95&ndash;96</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.47%</b></td><td>100%</td><td><b>81.24%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/78a56775da0c7a90277d50bc4a548cae2ef601ce/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td c [...]

2024-06-12 21:58 UTC, reverendbedford commented
Coverage after merging <b>doc</b> into <b>main</b> will be<table><tbody><tr><th>86.95%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/CrossRef.h#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/CrossRef.h#L104-L105'>104&ndash;105</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/CrossRef.h#L76'>76</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/CrossRef.h#L94'>94</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/CrossRef.h#L96-L97'>96&ndash;97</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.47%</b></td><td>100%</td><td><b>81.24%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/8b350c418947275f819fbe10a664471a9748535a/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td c [...]

2024-06-13 01:20 UTC, reverendbedford commented
Coverage after merging <b>doc</b> into <b>main</b> will be<table><tbody><tr><th>87.27%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/CrossRef.h#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/CrossRef.h#L104-L105'>104&ndash;105</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/CrossRef.h#L76'>76</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/CrossRef.h#L94'>94</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/CrossRef.h#L96-L97'>96&ndash;97</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.40%</b></td><td>100%</td><td><b>81.16%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/c6148d2783a3483454dfaa9a1c2504b87e038795/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td c [...]

2024-06-13 03:10 UTC, reverendbedford commented
Coverage after merging <b>doc</b> into <b>main</b> will be<table><tbody><tr><th>87.41%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/CrossRef.h#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/CrossRef.h#L104-L105'>104&ndash;105</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/CrossRef.h#L76'>76</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/CrossRef.h#L94'>94</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/CrossRef.h#L96-L97'>96&ndash;97</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.40%</b></td><td>100%</td><td><b>81.16%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/04aa2c9b697f543fee59101d13ab76adbaf3ec8b/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td c [...]

2024-06-13 20:54 UTC, reverendbedford commented
The following syntax is missing:
'ElasticStrainRate' is missing object description
  'deformation_rate' is mising option description
  'elastic_strain' is mising option description
  'elastic_strain_rate' is mising option description
  'plastic_deformation_rate' is mising option description
  'vorticity' is mising option description
'FixOrientation' is missing object description
  'input_orientation' is mising option description
  'output_orientation' is mising option description
  'threshold' is mising option description
'LinearSingleSlipHardeningRule' is missing object description
  'hardening_slope' is mising option description
  'slip_hardening' is mising option description
  'slip_hardening_rate' is mising option description
  'sum_slip_rates' is mising option description
'OrientationRate' is missing object description
  'elastic_strain' is mising option description
  'orientation_rate' is mising option description
  'plastic_deformation_rate' is mising option description
  'plastic_vorticity' is mising option description
  'vorticity' is mising option description
'PlasticDeformationRate' is missing object description
  'crystal_geometry_name' is mising option description
  'orientation' is mising option description
  'plastic_deformation_rate' is mising option description
  'slip_rates' is mising option description
'PlasticVorticity' is missing object description
  'crystal_geometry_name' is mising option description
  'orientation' is mising option description
  'plastic_vorticity' is mising option description
  'slip_rates' is mising option description
'PowerLawSlipRule' is missing object description
  'crystal_geometry_name' is mising option description
  'gamma0' is mising option description
  'n' is mising option description
  'resolved_shears' is mising option description
  'slip_rates' is mising option description
  'slip_strengths' is mising option description
'ResolvedShear' is missing object description
  'crystal_geometry_name' is mising option description
  'orientation' is mising option description
  'resolved_shears' is mising option description
  'stress' is mising option description
'SingleSlipStrengthMap' is missing object description
  'constant_strength' is mising option description
  'crystal_geometry_name' is mising option description
  'slip_hardening' is mising option description
  'slip_strengths' is mising option description
'SumSlipRates' is missing object description
  'crystal_geometry_name' is mising option description
  'slip_rates' is mising option description
  'sum_slip_rates' is mising option description
'VoceSingleSlipHardeningRule' is missing object description
  'initial_slope' is mising option description
  'saturated_hardening' is mising option description
  'slip_hardening' is mising option description
  'slip_hardening_rate' is mising option description
  'sum_slip_rates' is mising option description
'FillMillerIndex' is missing object description
  'values' is mising option description
'Orientation' is missing object description
'SymmetryFromOrbifold' is missing object description
  'orbifold' is mising option description
'CrystalGeometry' is missing object description
  'crystal_class' is mising option description
  'lattice_vectors' is mising option description
  'slip_directions' is mising option description
  'slip_planes' is mising option description
'CubicCrystal' is missing object description
  'lattice_parameter' is mising option description
  'slip_directions' is mising option description
  'slip_planes' is mising option description
  'cauchy_stress' is mising option description
  'temperature' is mising option description
  'subproblem_abs_tol' is mising option description

<!-- thollander/actions-comment-pull-request "doc_scold" -->

2024-06-13 22:04 UTC, reverendbedford commented
Coverage after merging <b>doc</b> into <b>main</b> will be<table><tbody><tr><th>87.81%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/CrossRef.h#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/CrossRef.h#L104-L105'>104&ndash;105</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/CrossRef.h#L76'>76</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/CrossRef.h#L94'>94</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/CrossRef.h#L96-L97'>96&ndash;97</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.40%</b></td><td>100%</td><td><b>81.16%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/bda360d65f0f12d9ed3306741a984aeeaa93a6e9/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td c [...]

2024-06-13 23:02 UTC, reverendbedford approved these changes

2024-06-14 00:03 UTC, hugary1995 reviewed
LGTM. Unfortunately, docstring of individual options cannot render latex. I'll found two occurrences which I'll fix by either removing the formula or relocate them into the object summary doc.

2024-06-14 00:03 UTC, hugary1995 commented on src/neml2/models/crystallography/CubicCrystal.cxx
> +  options.set("lattice_parameter").doc() = "The lattice parameter \\f$ a \\f$";
Note to myself: currently latex in option doc doesn't work so I'll have to remove it.

2024-06-14 00:03 UTC, hugary1995 commented on src/neml2/models/crystallography/user_tensors/FillMillerIndex.cxx
> +                                "\\bar{1} \\f$.";
Note to myself: no latex in option doc.

2024-06-14 00:04 UTC, reverendbedford commented
Coverage after merging <b>doc</b> into <b>main</b> will be<table><tbody><tr><th>88.00%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/CrossRef.h#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/CrossRef.h#L104-L105'>104&ndash;105</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/CrossRef.h#L76'>76</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/CrossRef.h#L94'>94</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/CrossRef.h#L96-L97'>96&ndash;97</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.40%</b></td><td>100%</td><td><b>81.16%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/dac6b3393b23591eb9e37351411ac272a2b98b84/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td c [...]

2024-06-14 00:08 UTC, hugary1995 commented
The option docstring formula rendering issue is documented in issue #146. I'll merge when tests pass.

2024-06-14 01:04 UTC, reverendbedford commented
Coverage after merging <b>doc</b> into <b>main</b> will be<table><tbody><tr><th>88.00%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/CrossRef.h#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/CrossRef.h#L104-L105'>104&ndash;105</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/CrossRef.h#L76'>76</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/CrossRef.h#L94'>94</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/CrossRef.h#L96-L97'>96&ndash;97</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.40%</b></td><td>100%</td><td><b>81.16%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/27dd9881bd6cabd69b97f9791096f03deafa5caf/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td c [...]

2024-06-14 01:07 UTC, merged