Adds mixed stress/strain control to solid_mechanics models
applied-material-modeling/neml2 pull request #144
Opened 2024-06-03 17:53 UTC by reverendbedford

This adds an object that can be used to change a strain (or stress) controlled solid mechanics model to run under mixed stress and strain control.  It also modifies `SolidMechanicsDriver` to let people use the new capability and adds a verification test for a Chaboche model to compare to NEML1.

2024-06-03 18:53 UTC, reverendbedford commented
Coverage after merging <b>mixed_control</b> into <b>main</b> will be<table><tbody><tr><th>87.07%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>80.43%</b></td><td>100%</td><td><b>77.78%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/DependencyResolver.h#L178'>178</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/DependencyResolver.h#L180-L181'>180&ndash;181</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/DependencyResolver.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/DependencyResolver.h#L188-L190'>188&ndash;190</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/DependencyResolver.h#L223'>223</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/DependencyResolver.h#L250'>250</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/DependencyResolver.h#L262'>262</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/DependencyResolver.h#L272-L273'>272&ndash;273</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/DependencyResolver.h#L305-L306'>305&ndash;306</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/DependencyResolver.h#L308-L309'>308&ndash;309</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.75%</b></td><td>100%</td><td><b>36.07%</b></td><td><b>74.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/OptionSet.h#L127'>127</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/OptionSet.h#L130'>130</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/OptionSet.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.55%</b></td><td>100%</td><td><b>81.32%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='6'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/drivers/Driver.h'>Driver.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/drivers/TransientDriver.h'>TransientDriver.h</a></td><td><b>85.71%</b></td><td>100%</td><td>100%</td><td><b>75%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/drivers/TransientDriver.h#L149'>149</a></td></tr><tr><td colspan='6'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/misc/error.h'>error.h</a></td><td><b>31.84%</b></td><td>100%</td><td><b>29.89%</b></td><td><b>63.64%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/41987220cc34f4e76a169da0b65a2f60101333b8/include/neml2/misc/error.h#L37-L38'>37&ndas [...]

2024-06-14 01:23 UTC, reverendbedford commented
## Missing syntax
  * 'MixedControlSetup' is missing object description
    * 'MixedControlSetup'.'cauchy_stress' is missing option description
    * 'MixedControlSetup'.'control' is missing option description
    * 'MixedControlSetup'.'fixed_values' is missing option description
    * 'MixedControlSetup'.'mixed_state' is missing option description
    * 'MixedControlSetup'.'strain' is missing option description
    * 'MixedControlSetup'.'threshold' is missing option description
    * 'SolidMechanicsDriver'.'control_name' is missing option description
    * 'SolidMechanicsDriver'.'fixed_values' is missing option description
    * 'SolidMechanicsDriver'.'prescribed_control' is missing option description
    * 'SolidMechanicsDriver'.'prescribed_mixed_conditions' is missing option description
    * 'SolidMechanicsDriver'.'prescribed_temperatures' is missing option description
    * 'SolidMechanicsDriver'.'temperature' is missing option description

<!-- thollander/actions-comment-pull-request "doc_scold" -->

2024-06-14 01:35 UTC, hugary1995 requested changes
Overall looks good to me. This turns out to be surprisingly simple!

Only one major comment: I like the idea of control signal, but is model supposed to "see" the control signal? It seems to me that the current implementation actually has the control signal being an input variable. An alternative implementation would be declaring the control signal as a buffer (as opposed to being an input variable), and let the driver update that buffer at every time step.

2024-06-14 01:35 UTC, hugary1995 commented on src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx
> +  options.set<VariableName>("fixed_values") = VariableName("forces", "fixed_values");
The conflict resolution wasn't very successful.

2024-06-14 01:35 UTC, hugary1995 commented on src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx
> +  options.set<CrossRef<torch::Tensor>>("prescribed_control");
Also to blame auto merging.

2024-06-14 01:35 UTC, hugary1995 commented on src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx
> +  options.set<CrossRef<torch::Tensor>>("prescribed_control");
Some option docstrings will definitely help, I think I'm already confusing `prescribed_mixed_conditions` with `prescribed_control`.

2024-06-14 01:35 UTC, hugary1995 commented on src/neml2/models/solid_mechanics/MixedControlSetup.cxx
> +  options.set<VariableName>("strain") = VariableName("forces", "E");
Let's see if github workflow correctly scolds you about missing docstrings.

2024-06-14 01:39 UTC, hugary1995 commented
> ## Missing syntax
> * 'MixedControlSetup' is missing object description
>   
>   * 'MixedControlSetup'.'cauchy_stress' is missing option description
>   * 'MixedControlSetup'.'control' is missing option description
>   * 'MixedControlSetup'.'fixed_values' is missing option description
>   * 'MixedControlSetup'.'mixed_state' is missing option description
>   * 'MixedControlSetup'.'strain' is missing option description
>   * 'MixedControlSetup'.'threshold' is missing option description
>   * 'SolidMechanicsDriver'.'control_name' is missing option description
>   * 'SolidMechanicsDriver'.'fixed_values' is missing option description
>   * 'SolidMechanicsDriver'.'prescribed_control' is missing option description
>   * 'SolidMechanicsDriver'.'prescribed_mixed_conditions' is missing option description
>   * 'SolidMechanicsDriver'.'prescribed_temperatures' is missing option description
>   * 'SolidMechanicsDriver'.'temperature' is missing option description

Not directly related to this PR, but the syntax comment could be improved... Though I guess it's mostly my fault.

2024-06-14 02:17 UTC, reverendbedford commented
Coverage after merging <b>mixed_control</b> into <b>main</b> will be<table><tbody><tr><th>87.85%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/CrossRef.h#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/CrossRef.h#L104-L105'>104&ndash;105</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/CrossRef.h#L76'>76</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/CrossRef.h#L94'>94</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/CrossRef.h#L96-L97'>96&ndash;97</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.47%</b></td><td>100%</td><td><b>81.24%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/ed97fca3f71a30246f06283a5c4c540f37b08278/include/neml2/base/Storage.h#L177'>177</a></td></tr [...]

2024-06-14 12:23 UTC, hugary1995 commented
Maybe also add a section in `solid_mechanics.md` to talk about strain, stress, and mixed controls.

2024-06-14 21:09 UTC, reverendbedford commented
@hugary1995  I think I convinced you to leave the control signal as is.  This push makes the rest of your suggestions.

2024-06-14 22:11 UTC, reverendbedford commented
Coverage after merging <b>mixed_control</b> into <b>main</b> will be<table><tbody><tr><th>87.89%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>38.04%</b></td><td>100%</td><td><b>38.27%</b></td><td><b>36.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/CrossRef.h#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/CrossRef.h#L104-L105'>104&ndash;105</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/CrossRef.h#L76'>76</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/CrossRef.h#L94'>94</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/CrossRef.h#L96-L97'>96&ndash;97</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.47%</b></td><td>100%</td><td><b>81.24%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/f8c69d920764bd8353f88233f719ba2c646acc0d/include/neml2/base/Storage.h#L177'>177</a></td></tr [...]

2024-06-15 03:04 UTC, hugary1995 requested changes
Minor points.

I don't have computer access, so I confirmed that our doco looks perfect on my phone :)

2024-06-15 03:04 UTC, hugary1995 commented on include/neml2/models/solid_mechanics/MixedControlSetup.h
> +  const Real _threshold;
In the most general case _threshold can be anything broadcastable with _control, not just Real. Feel free to create an issue to mark this as future work.

2024-06-15 03:04 UTC, hugary1995 commented on include/neml2/models/solid_mechanics/MixedControlSetup.h
> +  std::pair<SSR4, SSR4> _make_operators(const SR2 & bcontrol) const;
This is not terribly important but I don't we ever prefix underscore in method names.

2024-06-15 03:04 UTC, hugary1995 commented on src/neml2/models/solid_mechanics/MixedControlSetup.cxx
> +  auto dstrain = SSR4(BatchTensor(torch::diag_embed(ones_stress), batch_dim()));
Do we have diag_embed in our math namespace?

2024-06-15 03:04 UTC, hugary1995 commented on src/neml2/models/solid_mechanics/MixedControlSetup.cxx
> +  return std::make_pair(dstrain, dstress);
```suggestion
  return {dstrain, dstress};
```

2024-06-17 14:23 UTC, hugary1995 commented on src/neml2/models/solid_mechanics/MixedControlSetup.cxx
> +  options.set<BatchTensor>("threshold") = BatchTensor::full({}, 0.5);
This is probably leading to the doco failure as the default value serializes to a multi line string... I can try to fix it when I get back unless you find a workaround before I do.

2024-06-17 14:51 UTC, hugary1995 commented on src/neml2/models/solid_mechanics/MixedControlSetup.cxx
> +  options.set<CrossRef<BatchTensor>>("threshold");
You can set the default to be a string "0.5".

2024-06-17 14:51 UTC, hugary1995 commented on tests/regression/solid_mechanics/mixed_control/model.i
> +    threshold = 'threshold'
Even if it's cross ref, we can still write `threshold = 0.5`.

2024-06-17 14:51 UTC, hugary1995 commented on tests/regression/solid_mechanics/mixed_control/model.i
> +    threshold = 'threshold'
And this can be omitted if you give it a default.

2024-06-17 14:58 UTC, hugary1995 approved these changes

2024-06-17 15:59 UTC, reverendbedford commented
Coverage after merging <b>mixed_control</b> into <b>main</b> will be<table><tbody><tr><th>87.94%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>41.94%</b></td><td>100%</td><td><b>39.02%</b></td><td><b>63.64%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/CrossRef.h#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/CrossRef.h#L104-L105'>104&ndash;105</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/CrossRef.h#L76'>76</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>39%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>50%</b></td><td>100%</td><td><b>22.22%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>39.28%</b></td><td>100%</td><td><b>35.85%</b></td><td><b>68.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/OptionSet.h#L134'>134</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/OptionSet.h#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/OptionSet.h#L61'>61</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/OptionSet.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/OptionSet.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/OptionSet.h#L85'>85</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/OptionSet.h#L89'>89</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/OptionSet.h#L91'>91</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/OptionSet.h#L93'>93</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/OptionSet.h#L95'>95</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/Registry.h'>Registry.h</a></td><td><b>81.47%</b></td><td>100%</td><td><b>81.24%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/Storage.h'>Storage.h</a></td><td><b>56.10%</b></td><td>100%</td><td><b>39.13%</b></td><td><b>77.78%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/Storage.h#L147-L148'>147&ndash;148</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/Storage.h#L150'>150</a>, <a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/base/Storage.h#L177'>177</a></td></tr><tr><td colspan='6'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3ba0a001c03a469138f160305069235ef44db14d/include/neml2/drivers/Driver.h'>Driver.h</a></td><td><b>0%</b></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td [...]

2024-06-17 16:02 UTC, merged

2024-06-18 21:01 UTC, hugary1995 commented
I see what's going on -- we need to return a nonzero exit code so that merging is blocked in case of missing doc...