Fix inplace operation error
applied-material-modeling/neml2 pull request #160
Opened 2024-07-10 05:01 UTC by hugary1995

* New concept "inference mode"
* Fix nonlinear parameter declaration
* Fix input view set up logic
* Move 3rd party deps out of the build tree
* Add regression test for inplace error

Docstring for `inference_mode`:

By default, inference mode is off, and variables are re-allocated every time the model is 
evaluated. As a consequence, variable views need to be reconfigured over and over again. 
This default behavior avoids in-place operations and is mandatory to use torch AD (i.e. for 
parameter derivative or AD forward operator). When inference mode is on, no gradient is 
computed, and the variables and variable views are set up once and for all, which speed up 
evaluation. See https://pytorch.org/cppdocs/notes/inference_mode.html for details.

2024-07-10 05:08 UTC, reverendbedford commented
## Syntax check

No syntax error, good job! :purple_heart:
<!-- thollander/actions-comment-pull-request "doc_scold" -->

2024-07-10 05:30 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>87.87%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>34.21%</b></td><td>100%</td><td><b>31.37%</b></td><td><b>58.33%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/CrossRef.h#L105'>105</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/CrossRef.h#L107-L108'>107&ndash;108</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/CrossRef.h#L72'>72</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/CrossRef.h#L79'>79</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>41.90%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/NEML2Object.h#L52'>52</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/OptionCollection.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>34.38%</b></td><td>100%</td><td><b>30.55%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/OptionSet.h#L100'>100</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/OptionSet.h#L133'>133</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/OptionSet.h#L145'>145</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/OptionSet.h#L151'>151</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/OptionSet.h#L157'>157</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/OptionSet.h#L222'>222</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/OptionSet.h#L224-L225'>224&ndash;225</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/OptionSet.h#L396'>396</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/OptionSet.h#L71'>71</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/OptionSet.h#L84'>84</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/OptionSet.h#L86'>86</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f154032b78e/include/neml2/base/OptionSet.h#L90'>90</a>, <a href='https://github.com/reverendbedford/neml2/blob/1196941d047918062bcd8787294a8f [...]

2024-07-10 12:55 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>87.87%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>34.21%</b></td><td>100%</td><td><b>31.37%</b></td><td><b>58.33%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/CrossRef.h#L105'>105</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/CrossRef.h#L107-L108'>107&ndash;108</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/CrossRef.h#L72'>72</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/CrossRef.h#L79'>79</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>41.90%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/NEML2Object.h#L52'>52</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/OptionCollection.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>34.38%</b></td><td>100%</td><td><b>30.55%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/OptionSet.h#L100'>100</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/OptionSet.h#L133'>133</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/OptionSet.h#L145'>145</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/OptionSet.h#L151'>151</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/OptionSet.h#L157'>157</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/OptionSet.h#L222'>222</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/OptionSet.h#L224-L225'>224&ndash;225</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/OptionSet.h#L396'>396</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/OptionSet.h#L71'>71</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/OptionSet.h#L84'>84</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/OptionSet.h#L86'>86</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127ceaca3a7206/include/neml2/base/OptionSet.h#L90'>90</a>, <a href='https://github.com/reverendbedford/neml2/blob/0efa416be3b64401d7b733fa4a127c [...]

2024-07-10 14:58 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>87.87%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>34.21%</b></td><td>100%</td><td><b>31.37%</b></td><td><b>58.33%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/CrossRef.h#L105'>105</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/CrossRef.h#L107-L108'>107&ndash;108</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/CrossRef.h#L72'>72</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/CrossRef.h#L79'>79</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>41.90%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/NEML2Object.h#L52'>52</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/OptionCollection.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>34.38%</b></td><td>100%</td><td><b>30.55%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/OptionSet.h#L100'>100</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/OptionSet.h#L133'>133</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/OptionSet.h#L145'>145</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/OptionSet.h#L151'>151</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/OptionSet.h#L157'>157</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/OptionSet.h#L222'>222</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/OptionSet.h#L224-L225'>224&ndash;225</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/OptionSet.h#L396'>396</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/OptionSet.h#L71'>71</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/OptionSet.h#L84'>84</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/OptionSet.h#L86'>86</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de88a864fd00b/include/neml2/base/OptionSet.h#L90'>90</a>, <a href='https://github.com/reverendbedford/neml2/blob/0eab254717873e56c89f1dc9d13de8 [...]

2024-07-10 17:16 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>87.87%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>34.21%</b></td><td>100%</td><td><b>31.37%</b></td><td><b>58.33%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/CrossRef.h#L105'>105</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/CrossRef.h#L107-L108'>107&ndash;108</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/CrossRef.h#L72'>72</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/CrossRef.h#L79'>79</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>41.90%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/NEML2Object.h#L52'>52</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/NEML2Object.h#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/NEML2Object.h#L66'>66</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/OptionCollection.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>34.38%</b></td><td>100%</td><td><b>30.55%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/OptionSet.h#L100'>100</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/OptionSet.h#L133'>133</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/OptionSet.h#L142'>142</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/OptionSet.h#L145'>145</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/OptionSet.h#L151'>151</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/OptionSet.h#L157'>157</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/OptionSet.h#L222'>222</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/OptionSet.h#L224-L225'>224&ndash;225</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/OptionSet.h#L396'>396</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/OptionSet.h#L66'>66</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/OptionSet.h#L71'>71</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/OptionSet.h#L84'>84</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/OptionSet.h#L86'>86</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34a8097ad9a8/include/neml2/base/OptionSet.h#L90'>90</a>, <a href='https://github.com/reverendbedford/neml2/blob/bcb111bc582584f1dc4666d8011d34 [...]

2024-07-13 14:32 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>87.68%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>34.51%</b></td><td>100%</td><td><b>31.68%</b></td><td><b>58.33%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/CrossRef.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/CrossRef.h#L108-L109'>108&ndash;109</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/CrossRef.h#L73'>73</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/CrossRef.h#L80'>80</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>41.90%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/NEML2Object.h#L49'>49</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/NEML2Object.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/NEML2Object.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/NEML2Object.h#L65'>65</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/OptionCollection.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>34.25%</b></td><td>100%</td><td><b>30.42%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/OptionSet.h#L131'>131</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/OptionSet.h#L140'>140</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/OptionSet.h#L143'>143</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/OptionSet.h#L149'>149</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/OptionSet.h#L155'>155</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/OptionSet.h#L220'>220</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/OptionSet.h#L222-L223'>222&ndash;223</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/OptionSet.h#L394'>394</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/OptionSet.h#L64'>64</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/OptionSet.h#L69'>69</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/OptionSet.h#L82'>82</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/OptionSet.h#L84'>84</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/OptionSet.h#L88'>88</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d59bf9fe78/include/neml2/base/OptionSet.h#L92'>92</a>, <a href='https://github.com/reverendbedford/neml2/blob/92cb79dfe91aa142bc5606cf629566d5 [...]

2024-07-13 21:11 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>87.71%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>34.51%</b></td><td>100%</td><td><b>31.68%</b></td><td><b>58.33%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/CrossRef.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/CrossRef.h#L108-L109'>108&ndash;109</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/CrossRef.h#L73'>73</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/CrossRef.h#L80'>80</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>41.90%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/NEML2Object.h#L49'>49</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/NEML2Object.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/NEML2Object.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/NEML2Object.h#L65'>65</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/OptionCollection.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>40.91%</b></td><td>100%</td><td><b>37.20%</b></td><td><b>70.31%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/OptionSet.h#L104'>104</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/OptionSet.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/OptionSet.h#L110'>110</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/OptionSet.h#L114'>114</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/OptionSet.h#L116'>116</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/OptionSet.h#L118'>118</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/OptionSet.h#L153'>153</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/OptionSet.h#L162'>162</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/OptionSet.h#L165'>165</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/OptionSet.h#L171'>171</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/OptionSet.h#L177'>177</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/OptionSet.h#L183'>183</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf297512e/include/neml2/base/OptionSet.h#L258'>258</a>, <a href='https://github.com/reverendbedford/neml2/blob/06672424c5b924a65f5664406dfaf2cbf29 [...]

2024-07-13 22:09 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>87.71%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>34.51%</b></td><td>100%</td><td><b>31.68%</b></td><td><b>58.33%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/CrossRef.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/CrossRef.h#L108-L109'>108&ndash;109</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/CrossRef.h#L73'>73</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/CrossRef.h#L80'>80</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>41.90%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/NEML2Object.h#L49'>49</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/NEML2Object.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/NEML2Object.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/NEML2Object.h#L65'>65</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/OptionCollection.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>40.91%</b></td><td>100%</td><td><b>37.20%</b></td><td><b>70.31%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/OptionSet.h#L104'>104</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/OptionSet.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/OptionSet.h#L110'>110</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/OptionSet.h#L114'>114</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/OptionSet.h#L116'>116</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/OptionSet.h#L118'>118</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/OptionSet.h#L153'>153</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/OptionSet.h#L162'>162</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/OptionSet.h#L165'>165</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/OptionSet.h#L171'>171</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/OptionSet.h#L177'>177</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/OptionSet.h#L183'>183</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea382c2/include/neml2/base/OptionSet.h#L258'>258</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb0b6a8930ec77af16d549d6dab58cfe8ea [...]

2024-07-14 01:18 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>87.92%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>34.51%</b></td><td>100%</td><td><b>31.68%</b></td><td><b>58.33%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/CrossRef.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/CrossRef.h#L108-L109'>108&ndash;109</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/CrossRef.h#L73'>73</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/CrossRef.h#L80'>80</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>41.90%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/NEML2Object.h#L49'>49</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/NEML2Object.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/NEML2Object.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/NEML2Object.h#L65'>65</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/OptionCollection.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>40.91%</b></td><td>100%</td><td><b>37.20%</b></td><td><b>70.31%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/OptionSet.h#L104'>104</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/OptionSet.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/OptionSet.h#L110'>110</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/OptionSet.h#L114'>114</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/OptionSet.h#L116'>116</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/OptionSet.h#L118'>118</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/OptionSet.h#L153'>153</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/OptionSet.h#L162'>162</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/OptionSet.h#L165'>165</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/OptionSet.h#L171'>171</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/OptionSet.h#L177'>177</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/OptionSet.h#L183'>183</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91714fe/include/neml2/base/OptionSet.h#L258'>258</a>, <a href='https://github.com/reverendbedford/neml2/blob/29aed0ab3a054e00fd68b883f853e649d91 [...]

2024-07-14 01:46 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>87.92%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>34.51%</b></td><td>100%</td><td><b>31.68%</b></td><td><b>58.33%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/CrossRef.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/CrossRef.h#L108-L109'>108&ndash;109</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/CrossRef.h#L73'>73</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/CrossRef.h#L80'>80</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>41.90%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/NEML2Object.h#L49'>49</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/NEML2Object.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/NEML2Object.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/NEML2Object.h#L65'>65</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/OptionCollection.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>40.91%</b></td><td>100%</td><td><b>37.20%</b></td><td><b>70.31%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/OptionSet.h#L104'>104</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/OptionSet.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/OptionSet.h#L110'>110</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/OptionSet.h#L114'>114</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/OptionSet.h#L116'>116</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/OptionSet.h#L118'>118</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/OptionSet.h#L153'>153</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/OptionSet.h#L162'>162</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/OptionSet.h#L165'>165</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/OptionSet.h#L171'>171</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/OptionSet.h#L177'>177</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/OptionSet.h#L183'>183</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897a7138/include/neml2/base/OptionSet.h#L258'>258</a>, <a href='https://github.com/reverendbedford/neml2/blob/ddec3bef6d5602408c4d33b045438fc8897 [...]

2024-07-14 19:30 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>88.06%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>36.75%</b></td><td>100%</td><td><b>32.35%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/CrossRef.h#L111'>111</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/CrossRef.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/CrossRef.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/CrossRef.h#L85'>85</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>41.90%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/NEML2Object.h#L49'>49</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/NEML2Object.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/NEML2Object.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/NEML2Object.h#L65'>65</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/OptionCollection.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>40.91%</b></td><td>100%</td><td><b>37.20%</b></td><td><b>70.31%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/OptionSet.h#L104'>104</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/OptionSet.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/OptionSet.h#L110'>110</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/OptionSet.h#L114'>114</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/OptionSet.h#L116'>116</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/OptionSet.h#L118'>118</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/OptionSet.h#L153'>153</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/OptionSet.h#L162'>162</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/OptionSet.h#L165'>165</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/OptionSet.h#L171'>171</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/OptionSet.h#L177'>177</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/OptionSet.h#L183'>183</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8f0aeb/include/neml2/base/OptionSet.h#L258'>258</a>, <a href='https://github.com/reverendbedford/neml2/blob/15946b2d701a780e362cf06df87095a03f8 [...]

2024-07-15 04:08 UTC, hugary1995 commented
Changes in addition to the original PR description:
- Threaded composed model evaluation
- Avoided for loop and runtime slicing wherever possible
- Variable tensor type runtime introspection, i.e. `model.input_view("foo")->type()` returns an enum corresponding to the tensor type.
- Removed config.h, obsolete methods, and obsolete scripts
- Reorganized source file include hierarchy (CrossRef, math, etc) -- compilation is pretty fast now
- Use emoji to distinguish between input, output, parameter, and buffer in the syntax documentation
- A few renamings (summarized below)
- Python bindings usability is significantly improved. Most notably, we no longer need to call something like `.tensor().tensor()`. Plus we can evaluate model using one of three types of arguments: `torch.Tensor`, `neml2.Tensor`, and `neml2.LabeledVector`, with corresponding return types.
- Also added necessary bindings from the pyzag_integration branch -- there are a few that I don't want to include, but I could be convinced.
- Added a small epsilon to the derivative calculation of RateIndependentPlasticFlowConstraint to prevent nan. This was uncovered by some MOOSE tests.

Renamings:
- `neml2::TorchSize` -> `neml2::Size`
- `neml2::TorchShape` -> `neml2::TensorShape`
- `neml2::TorchShapeRef` -> `neml2::TensorShapeRef`
- `neml2::TorchIndex` -> `neml2::indexing::TensorIndex`
- `neml2::TorchSlice` -> `neml2::indexing::TensorIndices`
- `neml2::BatchTensor` -> `neml2::Tensor`
- `neml2::FixedDimTensor` -> `neml2::LogicalTensor`
- Model `SumModel` -> `LinearCombination`

2024-07-15 04:16 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>87.95%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>36.75%</b></td><td>100%</td><td><b>32.35%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/CrossRef.h#L111'>111</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/CrossRef.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/CrossRef.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/CrossRef.h#L85'>85</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>41.90%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/NEML2Object.h#L49'>49</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/NEML2Object.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/NEML2Object.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/NEML2Object.h#L65'>65</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/OptionCollection.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>40.91%</b></td><td>100%</td><td><b>37.20%</b></td><td><b>70.31%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/OptionSet.h#L104'>104</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/OptionSet.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/OptionSet.h#L110'>110</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/OptionSet.h#L114'>114</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/OptionSet.h#L116'>116</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/OptionSet.h#L118'>118</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/OptionSet.h#L153'>153</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/OptionSet.h#L162'>162</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/OptionSet.h#L165'>165</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/OptionSet.h#L171'>171</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/OptionSet.h#L177'>177</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/OptionSet.h#L183'>183</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c68c85/include/neml2/base/OptionSet.h#L258'>258</a>, <a href='https://github.com/reverendbedford/neml2/blob/1368409610d51209091f937274c3d78872c [...]

2024-07-15 04:59 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>87.96%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>36.75%</b></td><td>100%</td><td><b>32.35%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/CrossRef.h#L111'>111</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/CrossRef.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/CrossRef.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/CrossRef.h#L85'>85</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>41.90%</b></td><td>100%</td><td><b>24.69%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/NEML2Object.h#L49'>49</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/NEML2Object.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/NEML2Object.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/NEML2Object.h#L65'>65</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/OptionCollection.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>40.91%</b></td><td>100%</td><td><b>37.20%</b></td><td><b>70.31%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/OptionSet.h#L104'>104</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/OptionSet.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/OptionSet.h#L110'>110</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/OptionSet.h#L114'>114</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/OptionSet.h#L116'>116</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/OptionSet.h#L118'>118</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/OptionSet.h#L153'>153</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/OptionSet.h#L162'>162</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/OptionSet.h#L165'>165</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/OptionSet.h#L171'>171</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/OptionSet.h#L177'>177</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/OptionSet.h#L183'>183</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928efdf0/include/neml2/base/OptionSet.h#L258'>258</a>, <a href='https://github.com/reverendbedford/neml2/blob/97ad801d70fd0c25622dd74bcd5e66cd928 [...]

2024-07-16 03:15 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>88.02%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>36.75%</b></td><td>100%</td><td><b>32.35%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/CrossRef.h#L111'>111</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/CrossRef.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/CrossRef.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/CrossRef.h#L85'>85</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>43.81%</b></td><td>100%</td><td><b>27.16%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/NEML2Object.h#L49'>49</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/NEML2Object.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/NEML2Object.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/NEML2Object.h#L65'>65</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/OptionCollection.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>40.91%</b></td><td>100%</td><td><b>37.20%</b></td><td><b>70.31%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/OptionSet.h#L104'>104</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/OptionSet.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/OptionSet.h#L110'>110</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/OptionSet.h#L114'>114</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/OptionSet.h#L116'>116</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/OptionSet.h#L118'>118</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/OptionSet.h#L153'>153</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/OptionSet.h#L162'>162</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/OptionSet.h#L165'>165</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/OptionSet.h#L171'>171</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/OptionSet.h#L177'>177</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/OptionSet.h#L183'>183</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3767b3/include/neml2/base/OptionSet.h#L258'>258</a>, <a href='https://github.com/reverendbedford/neml2/blob/4cca524f987aac0cab7befaeb4d410047d3 [...]

2024-07-16 19:35 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>87.93%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>36.75%</b></td><td>100%</td><td><b>32.35%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/CrossRef.h#L111'>111</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/CrossRef.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/CrossRef.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/CrossRef.h#L85'>85</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>43.81%</b></td><td>100%</td><td><b>27.16%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/NEML2Object.h#L49'>49</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/NEML2Object.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/NEML2Object.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/NEML2Object.h#L65'>65</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/OptionCollection.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>40.91%</b></td><td>100%</td><td><b>37.20%</b></td><td><b>70.31%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/OptionSet.h#L104'>104</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/OptionSet.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/OptionSet.h#L110'>110</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/OptionSet.h#L114'>114</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/OptionSet.h#L116'>116</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/OptionSet.h#L118'>118</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/OptionSet.h#L153'>153</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/OptionSet.h#L162'>162</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/OptionSet.h#L165'>165</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/OptionSet.h#L171'>171</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/OptionSet.h#L177'>177</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/OptionSet.h#L183'>183</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21fae472/include/neml2/base/OptionSet.h#L258'>258</a>, <a href='https://github.com/reverendbedford/neml2/blob/f75aed77b27e865229d2e063e61e421b21f [...]

2024-07-17 01:18 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>87.89%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>36.75%</b></td><td>100%</td><td><b>32.35%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/CrossRef.h#L111'>111</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/CrossRef.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/CrossRef.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/CrossRef.h#L85'>85</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>43.81%</b></td><td>100%</td><td><b>27.16%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/NEML2Object.h#L49'>49</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/NEML2Object.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/NEML2Object.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/NEML2Object.h#L65'>65</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/OptionCollection.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>40.91%</b></td><td>100%</td><td><b>37.20%</b></td><td><b>70.31%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/OptionSet.h#L104'>104</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/OptionSet.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/OptionSet.h#L110'>110</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/OptionSet.h#L114'>114</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/OptionSet.h#L116'>116</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/OptionSet.h#L118'>118</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/OptionSet.h#L153'>153</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/OptionSet.h#L162'>162</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/OptionSet.h#L165'>165</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/OptionSet.h#L171'>171</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/OptionSet.h#L177'>177</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/OptionSet.h#L183'>183</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce324bd46/include/neml2/base/OptionSet.h#L258'>258</a>, <a href='https://github.com/reverendbedford/neml2/blob/2f0d6c0e73ed1292d388f9cf62215b3ce32 [...]

2024-07-17 15:22 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>87.90%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>36.75%</b></td><td>100%</td><td><b>32.35%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/CrossRef.h#L111'>111</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/CrossRef.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/CrossRef.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/CrossRef.h#L85'>85</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>43.81%</b></td><td>100%</td><td><b>27.16%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/NEML2Object.h#L49'>49</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/NEML2Object.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/NEML2Object.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/NEML2Object.h#L65'>65</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/OptionCollection.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>40.91%</b></td><td>100%</td><td><b>37.20%</b></td><td><b>70.31%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/OptionSet.h#L104'>104</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/OptionSet.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/OptionSet.h#L110'>110</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/OptionSet.h#L114'>114</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/OptionSet.h#L116'>116</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/OptionSet.h#L118'>118</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/OptionSet.h#L153'>153</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/OptionSet.h#L162'>162</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/OptionSet.h#L165'>165</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/OptionSet.h#L171'>171</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/OptionSet.h#L177'>177</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/OptionSet.h#L183'>183</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66acf67/include/neml2/base/OptionSet.h#L258'>258</a>, <a href='https://github.com/reverendbedford/neml2/blob/70f70959299ba378118d1fd09ab2d20bc66 [...]

2024-07-19 14:50 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>87.64%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>36.75%</b></td><td>100%</td><td><b>32.35%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/CrossRef.h#L111'>111</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/CrossRef.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/CrossRef.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/CrossRef.h#L85'>85</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>43.81%</b></td><td>100%</td><td><b>27.16%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/NEML2Object.h#L49'>49</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/NEML2Object.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/NEML2Object.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/NEML2Object.h#L65'>65</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/OptionCollection.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>40.91%</b></td><td>100%</td><td><b>37.20%</b></td><td><b>70.31%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/OptionSet.h#L104'>104</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/OptionSet.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/OptionSet.h#L110'>110</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/OptionSet.h#L114'>114</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/OptionSet.h#L116'>116</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/OptionSet.h#L118'>118</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/OptionSet.h#L153'>153</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/OptionSet.h#L162'>162</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/OptionSet.h#L165'>165</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/OptionSet.h#L171'>171</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/OptionSet.h#L177'>177</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/OptionSet.h#L183'>183</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed6401730130b8d3/include/neml2/base/OptionSet.h#L258'>258</a>, <a href='https://github.com/reverendbedford/neml2/blob/cb493e2e858825eb9f0df5b0ed640173013 [...]

2024-07-19 17:35 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>87.64%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>36.75%</b></td><td>100%</td><td><b>32.35%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/CrossRef.h#L111'>111</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/CrossRef.h#L113-L114'>113&ndash;114</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/CrossRef.h#L78'>78</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/CrossRef.h#L85'>85</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>43.81%</b></td><td>100%</td><td><b>27.16%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/NEML2Object.h#L49'>49</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/NEML2Object.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/NEML2Object.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/NEML2Object.h#L65'>65</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/OptionCollection.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>40.91%</b></td><td>100%</td><td><b>37.20%</b></td><td><b>70.31%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/OptionSet.h#L104'>104</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/OptionSet.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/OptionSet.h#L110'>110</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/OptionSet.h#L114'>114</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/OptionSet.h#L116'>116</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/OptionSet.h#L118'>118</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/OptionSet.h#L153'>153</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/OptionSet.h#L162'>162</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/OptionSet.h#L165'>165</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/OptionSet.h#L171'>171</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/OptionSet.h#L177'>177</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/OptionSet.h#L183'>183</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9f1aae/include/neml2/base/OptionSet.h#L258'>258</a>, <a href='https://github.com/reverendbedford/neml2/blob/a666c7012df1eeac845e92aa6a07f290af9 [...]

2024-07-20 01:15 UTC, hugary1995 commented
close #159

2024-07-20 01:36 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>87.67%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>36.75%</b></td><td>100%</td><td><b>32.35%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/CrossRef.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/CrossRef.h#L126-L127'>126&ndash;127</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/CrossRef.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/CrossRef.h#L88'>88</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>43.81%</b></td><td>100%</td><td><b>27.16%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/NEML2Object.h#L49'>49</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/NEML2Object.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/NEML2Object.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/NEML2Object.h#L65'>65</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/OptionCollection.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>40.91%</b></td><td>100%</td><td><b>37.20%</b></td><td><b>70.31%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/OptionSet.h#L104'>104</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/OptionSet.h#L106'>106</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/OptionSet.h#L110'>110</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/OptionSet.h#L114'>114</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/OptionSet.h#L116'>116</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/OptionSet.h#L118'>118</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/OptionSet.h#L120'>120</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/OptionSet.h#L153'>153</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/OptionSet.h#L162'>162</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/OptionSet.h#L165'>165</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/OptionSet.h#L171'>171</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/OptionSet.h#L177'>177</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/OptionSet.h#L183'>183</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b782417259/include/neml2/base/OptionSet.h#L258'>258</a>, <a href='https://github.com/reverendbedford/neml2/blob/34e829a697d39aeee49ba6a4d47cc8b7824 [...]

2024-07-20 23:35 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>87.67%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td><b>36.75%</b></td><td>100%</td><td><b>32.35%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/CrossRef.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/CrossRef.h#L126-L127'>126&ndash;127</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/CrossRef.h#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/CrossRef.h#L88'>88</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/DependencyResolver.h'>DependencyResolver.h</a></td><td><b>86.13%</b></td><td>100%</td><td><b>88.24%</b></td><td><b>85.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/DependencyResolver.h#L219'>219</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/DependencyResolver.h#L221-L222'>221&ndash;222</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/DependencyResolver.h#L226'>226</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/DependencyResolver.h#L229-L231'>229&ndash;231</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/DependencyResolver.h#L264'>264</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/DependencyResolver.h#L291'>291</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/DependencyResolver.h#L303'>303</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/DependencyResolver.h#L313-L314'>313&ndash;314</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/DependencyResolver.h#L344'>344</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/DependencyResolver.h#L346-L347'>346&ndash;347</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/DependencyResolver.h#L349-L350'>349&ndash;350</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/EnumSelection.h'>EnumSelection.h</a></td><td><b>28.57%</b></td><td>100%</td><td><b>33.33%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/EnumSelection.h#L74'>74</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/EnumSelection.h#L87'>87</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/EnumSelection.h#L89'>89</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/Factory.h'>Factory.h</a></td><td><b>43.81%</b></td><td>100%</td><td><b>27.16%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td><b>45.45%</b></td><td>100%</td><td><b>20%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/NEML2Object.h#L49'>49</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/NEML2Object.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/NEML2Object.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/NEML2Object.h#L65'>65</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td><b>25%</b></td><td>100%</td><td><b>25%</b></td><td><b>25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/OptionCollection.h#L41'>41</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/OptionCollection.h#L44'>44</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/OptionCollection.h#L56'>56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td><b>40.91%</b></td><td>100%</td><td><b>37.20%</b></td><td><b>70.31%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/OptionSet.h#L112'>112</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/OptionSet.h#L114'>114</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/OptionSet.h#L118'>118</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/OptionSet.h#L122'>122</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/OptionSet.h#L124'>124</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/OptionSet.h#L126'>126</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/OptionSet.h#L128'>128</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/OptionSet.h#L161'>161</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/OptionSet.h#L170'>170</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/OptionSet.h#L173'>173</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/OptionSet.h#L179'>179</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/OptionSet.h#L185'>185</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/OptionSet.h#L191'>191</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176ed0fa/include/neml2/base/OptionSet.h#L266'>266</a>, <a href='https://github.com/reverendbedford/neml2/blob/5a3d8811560a4a5b6f0a725107948ded176 [...]

2024-07-21 02:58 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>92.00%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.04%</b></td><td>100%</td><td>100%</td><td><b>97.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/base/Factory.cxx#L45'>45</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td><b>98.04%</b></td><td>100%</td><td>100%</td><td><b>97.44%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/base/OptionSet.cxx#L48'>48</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>95.83%</b></td><td>100%</td><td>100%</td><td><b>95.65%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/base/Settings.cxx#L111'>111</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/base/Settings.cxx#L116'>116</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>98.51%</b></td><td>100%</td><td>100%</td><td><b>98.38%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/drivers/TransientDriver.cxx#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/drivers/TransientDriver.cxx#L276'>276</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.37%</b></td><td>100%</td><td>100%</td><td><b>94.03%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.06%</b></td><td>100%</td><td>100%</td><td><b>99.02%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/misc/math.cxx'>math.cxx</a></td><td><b>95.72%</b></td><td>100%</td><td><b>93.55%</b></td><td><b>96.15%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/misc/math.cxx#L248'>248</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/misc/math.cxx#L314'>314</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/misc/math.cxx#L316-L317'>316&ndash;317</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/misc/math.cxx#L340'>340</a>, <a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/misc/math.cxx#L342'>342</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f4351b8f04cca033caaa/src/neml2/misc/parser_utils.cxx'>parser_utils.cxx</a></td><td><b>98.46%</b></td><td>100%</td><td>100%</td><td><b>98.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/cd677f99711bd6415ce3f [...]

2024-07-21 17:51 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>94.30%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.04%</b></td><td>100%</td><td>100%</td><td><b>97.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/base/Factory.cxx#L45'>45</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td><b>98.04%</b></td><td>100%</td><td>100%</td><td><b>97.44%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/base/OptionSet.cxx#L48'>48</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>95.83%</b></td><td>100%</td><td>100%</td><td><b>95.65%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/base/Settings.cxx#L111'>111</a>, <a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/base/Settings.cxx#L116'>116</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>98.51%</b></td><td>100%</td><td>100%</td><td><b>98.38%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/drivers/TransientDriver.cxx#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/drivers/TransientDriver.cxx#L276'>276</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.37%</b></td><td>100%</td><td>100%</td><td><b>94.03%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.06%</b></td><td>100%</td><td>100%</td><td><b>99.02%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/misc/math.cxx'>math.cxx</a></td><td><b>95.74%</b></td><td>100%</td><td><b>93.55%</b></td><td><b>96.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/misc/math.cxx#L249'>249</a>, <a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/misc/math.cxx#L315'>315</a>, <a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/misc/math.cxx#L317-L318'>317&ndash;318</a>, <a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/misc/math.cxx#L341'>341</a>, <a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/misc/math.cxx#L343'>343</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777d91094d3c7ded12109f/src/neml2/misc/parser_utils.cxx'>parser_utils.cxx</a></td><td><b>98.46%</b></td><td>100%</td><td>100%</td><td><b>98.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/47a968f2d95fdfda00777 [...]

2024-07-21 18:13 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>94.30%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.04%</b></td><td>100%</td><td>100%</td><td><b>97.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/base/Factory.cxx#L45'>45</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td><b>98.04%</b></td><td>100%</td><td>100%</td><td><b>97.44%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/base/OptionSet.cxx#L48'>48</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>95.83%</b></td><td>100%</td><td>100%</td><td><b>95.65%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/base/Settings.cxx#L111'>111</a>, <a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/base/Settings.cxx#L116'>116</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>98.51%</b></td><td>100%</td><td>100%</td><td><b>98.38%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/drivers/TransientDriver.cxx#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/drivers/TransientDriver.cxx#L276'>276</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.37%</b></td><td>100%</td><td>100%</td><td><b>94.03%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.06%</b></td><td>100%</td><td>100%</td><td><b>99.02%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/misc/math.cxx'>math.cxx</a></td><td><b>95.74%</b></td><td>100%</td><td><b>93.55%</b></td><td><b>96.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/misc/math.cxx#L249'>249</a>, <a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/misc/math.cxx#L315'>315</a>, <a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/misc/math.cxx#L317-L318'>317&ndash;318</a>, <a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/misc/math.cxx#L341'>341</a>, <a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/misc/math.cxx#L343'>343</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc47056558008f3feb24bb1d/src/neml2/misc/parser_utils.cxx'>parser_utils.cxx</a></td><td><b>98.46%</b></td><td>100%</td><td>100%</td><td><b>98.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/09f8ba0d90f2b72adc470 [...]

2024-07-21 20:19 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>94.26%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.04%</b></td><td>100%</td><td>100%</td><td><b>97.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/base/Factory.cxx#L45'>45</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td><b>96.08%</b></td><td>100%</td><td>100%</td><td><b>94.87%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/base/OptionSet.cxx#L39'>39</a>, <a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/base/OptionSet.cxx#L48'>48</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>95.83%</b></td><td>100%</td><td>100%</td><td><b>95.65%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/base/Settings.cxx#L111'>111</a>, <a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/base/Settings.cxx#L116'>116</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>98.51%</b></td><td>100%</td><td>100%</td><td><b>98.38%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/TransientDriver.cxx#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/TransientDriver.cxx#L276'>276</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.37%</b></td><td>100%</td><td>100%</td><td><b>94.03%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>87.74%</b></td><td>100%</td><td>100%</td><td><b>87.25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L117'>117</a>, <a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L148'>148</a>, <a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L150-L151'>150&ndash;151</a>, <a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L154'>154</a>, <a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L156'>156</a>, <a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L158'>158</a>, <a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L161'>161</a>, <a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L163'>163</a>, <a href='https://github.com/reverendbedford/neml2/blob/6f52f96e36bc6ac4d25072f821d67a3de17c8ce3/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L194-L196'>194&ndash;196</a>, <a href='https://gith [...]

2024-07-21 22:13 UTC, hugary1995 commented
I am now letting parameter declaration error out when you declare a nonlinear parameter but its hand-coded derivatives are not implemented. This additional error checking uncovered that you were using nonlinear parameters in `PerzynaPlasticFlowRate` without providing their derivatives. This happens in km_flow/mixed_control and km_flow/full_model. It seems that those models can converge quite nicely even without those derivatives, but I added the missing derivatives anyways.

I also added two global settings with defaults
```python
[Settings]
  buffer_name_separator = '.'
  parameter_name_separator = '.'
[]
```
which allows you to customize the separator. I'd imagine that this is necessary for some pyzag stuff. You can change the separator to something like '::' and so parameter names will be "yield::sy" instead of "yield.sy".

2024-07-21 22:30 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>94.48%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.04%</b></td><td>100%</td><td>100%</td><td><b>97.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/base/Factory.cxx#L45'>45</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td><b>98.04%</b></td><td>100%</td><td>100%</td><td><b>97.44%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/base/OptionSet.cxx#L48'>48</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>96.43%</b></td><td>100%</td><td>100%</td><td><b>96.30%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/base/Settings.cxx#L121'>121</a>, <a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/base/Settings.cxx#L126'>126</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>98.51%</b></td><td>100%</td><td>100%</td><td><b>98.38%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/drivers/TransientDriver.cxx#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/drivers/TransientDriver.cxx#L276'>276</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.37%</b></td><td>100%</td><td>100%</td><td><b>94.03%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.06%</b></td><td>100%</td><td>100%</td><td><b>99.02%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/misc/math.cxx'>math.cxx</a></td><td><b>95.74%</b></td><td>100%</td><td><b>93.55%</b></td><td><b>96.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/misc/math.cxx#L249'>249</a>, <a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/misc/math.cxx#L315'>315</a>, <a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/misc/math.cxx#L317-L318'>317&ndash;318</a>, <a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/misc/math.cxx#L341'>341</a>, <a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/misc/math.cxx#L343'>343</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b530410463809312ca2a6eda2/src/neml2/misc/parser_utils.cxx'>parser_utils.cxx</a></td><td><b>98.46%</b></td><td>100%</td><td>100%</td><td><b>98.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c199c4e2fef5f63b53041 [...]

2024-07-22 02:18 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>94.48%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.04%</b></td><td>100%</td><td>100%</td><td><b>97.62%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/base/Factory.cxx#L45'>45</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td><b>98.04%</b></td><td>100%</td><td>100%</td><td><b>97.44%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/base/OptionSet.cxx#L48'>48</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>96.43%</b></td><td>100%</td><td>100%</td><td><b>96.30%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/base/Settings.cxx#L121'>121</a>, <a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/base/Settings.cxx#L126'>126</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>98.51%</b></td><td>100%</td><td>100%</td><td><b>98.38%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/drivers/TransientDriver.cxx#L146'>146</a>, <a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/drivers/TransientDriver.cxx#L276'>276</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.37%</b></td><td>100%</td><td>100%</td><td><b>94.03%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.06%</b></td><td>100%</td><td>100%</td><td><b>99.02%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/misc/math.cxx'>math.cxx</a></td><td><b>95.74%</b></td><td>100%</td><td><b>93.55%</b></td><td><b>96.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/misc/math.cxx#L249'>249</a>, <a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/misc/math.cxx#L315'>315</a>, <a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/misc/math.cxx#L317-L318'>317&ndash;318</a>, <a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/misc/math.cxx#L341'>341</a>, <a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/misc/math.cxx#L343'>343</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713b7eb09d139e227a0a60/src/neml2/misc/parser_utils.cxx'>parser_utils.cxx</a></td><td><b>98.46%</b></td><td>100%</td><td>100%</td><td><b>98.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/65994ac9f675862a46713 [...]

2024-07-22 22:11 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>94.46%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/DiagnosticsInterface.cxx'>DiagnosticsInterface.cxx</a></td><td><b>66.67%</b></td><td>100%</td><td>100%</td><td><b>61.54%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/DiagnosticsInterface.cxx#L37-L41'>37&ndash;41</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.15%</b></td><td>100%</td><td>100%</td><td><b>97.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/Factory.cxx#L46'>46</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td><b>98.04%</b></td><td>100%</td><td>100%</td><td><b>97.44%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/OptionSet.cxx#L48'>48</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>96.49%</b></td><td>100%</td><td>100%</td><td><b>96.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/Settings.cxx#L121'>121</a>, <a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/base/Settings.cxx#L126'>126</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>93.50%</b></td><td>100%</td><td>100%</td><td><b>92.93%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/drivers/TransientDriver.cxx#L260-L264'>260&ndash;264</a>, <a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/drivers/TransientDriver.cxx#L266-L271'>266&ndash;271</a>, <a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/drivers/TransientDriver.cxx#L274'>274</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.67%</b></td><td>100%</td><td>100%</td><td><b>94.37%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.11%</b></td><td>100%</td><td>100%</td><td><b>99.07%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/misc/math.cxx'>math.cxx</a></td><td><b>95.74%</b></td><td>100%</td><td><b>93.55%</b></td><td><b>96.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/misc/math.cxx#L249'>249</a>, <a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/misc/math.cxx#L315'>315</a>, <a href='https://github.com/reverendbedford/neml2/blob/9a63632e72624af6b0a55094323e520f5b147e63/src/neml2/misc/math.cxx#L317-L318'>317&ndas [...]

2024-07-25 00:27 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>93.90%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/DiagnosticsInterface.cxx'>DiagnosticsInterface.cxx</a></td><td><b>62.26%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>61.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/DiagnosticsInterface.cxx#L38-L42'>38&ndash;42</a>, <a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/DiagnosticsInterface.cxx#L59'>59</a>, <a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/DiagnosticsInterface.cxx#L62-L64'>62&ndash;64</a>, <a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/DiagnosticsInterface.cxx#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/DiagnosticsInterface.cxx#L78-L80'>78&ndash;80</a>, <a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/DiagnosticsInterface.cxx#L83'>83</a>, <a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/DiagnosticsInterface.cxx#L86-L88'>86&ndash;88</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.15%</b></td><td>100%</td><td>100%</td><td><b>97.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/Factory.cxx#L46'>46</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td><b>98.25%</b></td><td>100%</td><td>100%</td><td><b>97.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/OptionSet.cxx#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>96.49%</b></td><td>100%</td><td>100%</td><td><b>96.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/Settings.cxx#L121'>121</a>, <a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/base/Settings.cxx#L126'>126</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>99%</b></td><td>100%</td><td>100%</td><td><b>98.91%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/drivers/TransientDriver.cxx#L274'>274</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.67%</b></td><td>100%</td><td>100%</td><td><b>94.37%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.11%</b></td><td>100%</td><td>100%</td><td><b>99.07%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/d6c7b892603739d969ddb0669d5fa2cccdc0a686/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://gi [...]

2024-07-25 01:32 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>93.90%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/DiagnosticsInterface.cxx'>DiagnosticsInterface.cxx</a></td><td><b>62.26%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>61.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/DiagnosticsInterface.cxx#L38-L42'>38&ndash;42</a>, <a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/DiagnosticsInterface.cxx#L59'>59</a>, <a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/DiagnosticsInterface.cxx#L62-L64'>62&ndash;64</a>, <a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/DiagnosticsInterface.cxx#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/DiagnosticsInterface.cxx#L78-L80'>78&ndash;80</a>, <a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/DiagnosticsInterface.cxx#L83'>83</a>, <a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/DiagnosticsInterface.cxx#L86-L88'>86&ndash;88</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.15%</b></td><td>100%</td><td>100%</td><td><b>97.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/Factory.cxx#L46'>46</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td><b>98.25%</b></td><td>100%</td><td>100%</td><td><b>97.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/OptionSet.cxx#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>96.49%</b></td><td>100%</td><td>100%</td><td><b>96.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/Settings.cxx#L121'>121</a>, <a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/base/Settings.cxx#L126'>126</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>99%</b></td><td>100%</td><td>100%</td><td><b>98.91%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/drivers/TransientDriver.cxx#L274'>274</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.67%</b></td><td>100%</td><td>100%</td><td><b>94.37%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.11%</b></td><td>100%</td><td>100%</td><td><b>99.07%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/b864da4e2ede42ecc784282db046c48ba596dbc4/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://gi [...]

2024-07-25 02:45 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>93.88%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/DiagnosticsInterface.cxx'>DiagnosticsInterface.cxx</a></td><td><b>62.26%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>61.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/DiagnosticsInterface.cxx#L38-L42'>38&ndash;42</a>, <a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/DiagnosticsInterface.cxx#L59'>59</a>, <a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/DiagnosticsInterface.cxx#L62-L64'>62&ndash;64</a>, <a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/DiagnosticsInterface.cxx#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/DiagnosticsInterface.cxx#L78-L80'>78&ndash;80</a>, <a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/DiagnosticsInterface.cxx#L83'>83</a>, <a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/DiagnosticsInterface.cxx#L86-L88'>86&ndash;88</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.15%</b></td><td>100%</td><td>100%</td><td><b>97.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/Factory.cxx#L46'>46</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td><b>98.25%</b></td><td>100%</td><td>100%</td><td><b>97.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/OptionSet.cxx#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>96.49%</b></td><td>100%</td><td>100%</td><td><b>96.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/Settings.cxx#L121'>121</a>, <a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/base/Settings.cxx#L126'>126</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>99%</b></td><td>100%</td><td>100%</td><td><b>98.91%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/drivers/TransientDriver.cxx#L272'>272</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.67%</b></td><td>100%</td><td>100%</td><td><b>94.37%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.11%</b></td><td>100%</td><td>100%</td><td><b>99.07%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5e0ddd11eab4e7cb75ad0af7bd516f230109a951/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://gi [...]

2024-07-26 02:59 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>93.98%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/DiagnosticsInterface.cxx'>DiagnosticsInterface.cxx</a></td><td><b>62.26%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>61.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/DiagnosticsInterface.cxx#L38-L42'>38&ndash;42</a>, <a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/DiagnosticsInterface.cxx#L59'>59</a>, <a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/DiagnosticsInterface.cxx#L62-L64'>62&ndash;64</a>, <a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/DiagnosticsInterface.cxx#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/DiagnosticsInterface.cxx#L78-L80'>78&ndash;80</a>, <a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/DiagnosticsInterface.cxx#L83'>83</a>, <a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/DiagnosticsInterface.cxx#L86-L88'>86&ndash;88</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.15%</b></td><td>100%</td><td>100%</td><td><b>97.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/Factory.cxx#L46'>46</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td><b>98.25%</b></td><td>100%</td><td>100%</td><td><b>97.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/OptionSet.cxx#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>96.49%</b></td><td>100%</td><td>100%</td><td><b>96.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/Settings.cxx#L121'>121</a>, <a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/base/Settings.cxx#L126'>126</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>99%</b></td><td>100%</td><td>100%</td><td><b>98.91%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/drivers/TransientDriver.cxx#L272'>272</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.67%</b></td><td>100%</td><td>100%</td><td><b>94.37%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.11%</b></td><td>100%</td><td>100%</td><td><b>99.07%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f9537f6b5f5b27485758b1e529225ecd967d219a/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://gi [...]

2024-07-26 22:00 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>94.08%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/DiagnosticsInterface.cxx'>DiagnosticsInterface.cxx</a></td><td><b>71.70%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/DiagnosticsInterface.cxx#L59'>59</a>, <a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/DiagnosticsInterface.cxx#L62-L64'>62&ndash;64</a>, <a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/DiagnosticsInterface.cxx#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/DiagnosticsInterface.cxx#L78-L80'>78&ndash;80</a>, <a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/DiagnosticsInterface.cxx#L83'>83</a>, <a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/DiagnosticsInterface.cxx#L86-L88'>86&ndash;88</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.15%</b></td><td>100%</td><td>100%</td><td><b>97.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/Factory.cxx#L46'>46</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td><b>98.25%</b></td><td>100%</td><td>100%</td><td><b>97.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/OptionSet.cxx#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>96.49%</b></td><td>100%</td><td>100%</td><td><b>96.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/Settings.cxx#L121'>121</a>, <a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/base/Settings.cxx#L126'>126</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>99%</b></td><td>100%</td><td>100%</td><td><b>98.91%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/drivers/TransientDriver.cxx#L272'>272</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.67%</b></td><td>100%</td><td>100%</td><td><b>94.37%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.11%</b></td><td>100%</td><td>100%</td><td><b>99.07%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da6bf9f2a652cd66f342202e59ee3d9eec50c9ad/src/neml2/misc/math.cxx'>math.cxx</a></td><td><b>95.74%</b></td><td>100%</td><td><b>9 [...]

2024-07-27 02:08 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>94.06%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/DiagnosticsInterface.cxx'>DiagnosticsInterface.cxx</a></td><td><b>71.70%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/DiagnosticsInterface.cxx#L59'>59</a>, <a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/DiagnosticsInterface.cxx#L62-L64'>62&ndash;64</a>, <a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/DiagnosticsInterface.cxx#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/DiagnosticsInterface.cxx#L78-L80'>78&ndash;80</a>, <a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/DiagnosticsInterface.cxx#L83'>83</a>, <a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/DiagnosticsInterface.cxx#L86-L88'>86&ndash;88</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.21%</b></td><td>100%</td><td>100%</td><td><b>97.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/Factory.cxx#L46'>46</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td><b>98.25%</b></td><td>100%</td><td>100%</td><td><b>97.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/OptionSet.cxx#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>96.49%</b></td><td>100%</td><td>100%</td><td><b>96.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/Settings.cxx#L121'>121</a>, <a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/base/Settings.cxx#L126'>126</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>99%</b></td><td>100%</td><td>100%</td><td><b>98.91%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/drivers/TransientDriver.cxx#L272'>272</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.67%</b></td><td>100%</td><td>100%</td><td><b>94.37%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.11%</b></td><td>100%</td><td>100%</td><td><b>99.07%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175a1d54ac310b515217b82fdadfee4f114adb75/src/neml2/misc/math.cxx'>math.cxx</a></td><td><b>95.74%</b></td><td>100%</td><td><b>9 [...]

2024-07-27 11:00 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>94.07%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/DiagnosticsInterface.cxx'>DiagnosticsInterface.cxx</a></td><td><b>71.70%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/DiagnosticsInterface.cxx#L59'>59</a>, <a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/DiagnosticsInterface.cxx#L62-L64'>62&ndash;64</a>, <a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/DiagnosticsInterface.cxx#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/DiagnosticsInterface.cxx#L78-L80'>78&ndash;80</a>, <a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/DiagnosticsInterface.cxx#L83'>83</a>, <a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/DiagnosticsInterface.cxx#L86-L88'>86&ndash;88</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.21%</b></td><td>100%</td><td>100%</td><td><b>97.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/Factory.cxx#L46'>46</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td><b>98.25%</b></td><td>100%</td><td>100%</td><td><b>97.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/OptionSet.cxx#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>96.49%</b></td><td>100%</td><td>100%</td><td><b>96.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/Settings.cxx#L121'>121</a>, <a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/base/Settings.cxx#L126'>126</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>99%</b></td><td>100%</td><td>100%</td><td><b>98.91%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/drivers/TransientDriver.cxx#L272'>272</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.67%</b></td><td>100%</td><td>100%</td><td><b>94.37%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.11%</b></td><td>100%</td><td>100%</td><td><b>99.07%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/da47a1c36b8a451a454176165b6bac4963d9d4a3/src/neml2/misc/math.cxx'>math.cxx</a></td><td><b>95.74%</b></td><td>100%</td><td><b>9 [...]

2024-07-28 14:34 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>94.07%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/DiagnosticsInterface.cxx'>DiagnosticsInterface.cxx</a></td><td><b>71.70%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/DiagnosticsInterface.cxx#L59'>59</a>, <a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/DiagnosticsInterface.cxx#L62-L64'>62&ndash;64</a>, <a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/DiagnosticsInterface.cxx#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/DiagnosticsInterface.cxx#L78-L80'>78&ndash;80</a>, <a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/DiagnosticsInterface.cxx#L83'>83</a>, <a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/DiagnosticsInterface.cxx#L86-L88'>86&ndash;88</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.21%</b></td><td>100%</td><td>100%</td><td><b>97.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/Factory.cxx#L46'>46</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td><b>98.25%</b></td><td>100%</td><td>100%</td><td><b>97.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/OptionSet.cxx#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>96.49%</b></td><td>100%</td><td>100%</td><td><b>96.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/Settings.cxx#L121'>121</a>, <a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/base/Settings.cxx#L126'>126</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>99%</b></td><td>100%</td><td>100%</td><td><b>98.91%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/drivers/TransientDriver.cxx#L272'>272</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.67%</b></td><td>100%</td><td>100%</td><td><b>94.37%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.11%</b></td><td>100%</td><td>100%</td><td><b>99.07%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/92ce52d04d913033ae9289813b16492b762a6957/src/neml2/misc/math.cxx'>math.cxx</a></td><td><b>95.74%</b></td><td>100%</td><td><b>9 [...]

2024-07-28 19:10 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>94.07%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/DiagnosticsInterface.cxx'>DiagnosticsInterface.cxx</a></td><td><b>71.70%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/DiagnosticsInterface.cxx#L59'>59</a>, <a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/DiagnosticsInterface.cxx#L62-L64'>62&ndash;64</a>, <a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/DiagnosticsInterface.cxx#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/DiagnosticsInterface.cxx#L78-L80'>78&ndash;80</a>, <a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/DiagnosticsInterface.cxx#L83'>83</a>, <a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/DiagnosticsInterface.cxx#L86-L88'>86&ndash;88</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.21%</b></td><td>100%</td><td>100%</td><td><b>97.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/Factory.cxx#L46'>46</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td><b>98.25%</b></td><td>100%</td><td>100%</td><td><b>97.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/OptionSet.cxx#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>96.49%</b></td><td>100%</td><td>100%</td><td><b>96.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/Settings.cxx#L121'>121</a>, <a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/base/Settings.cxx#L126'>126</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>99%</b></td><td>100%</td><td>100%</td><td><b>98.91%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/drivers/TransientDriver.cxx#L272'>272</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.67%</b></td><td>100%</td><td>100%</td><td><b>94.37%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.11%</b></td><td>100%</td><td>100%</td><td><b>99.07%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/02cb1aa9e290dbef548bf6b5cae7c630d19194ea/src/neml2/misc/math.cxx'>math.cxx</a></td><td><b>95.74%</b></td><td>100%</td><td><b>9 [...]

2024-07-28 22:59 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>94.07%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/DiagnosticsInterface.cxx'>DiagnosticsInterface.cxx</a></td><td><b>71.70%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/DiagnosticsInterface.cxx#L59'>59</a>, <a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/DiagnosticsInterface.cxx#L62-L64'>62&ndash;64</a>, <a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/DiagnosticsInterface.cxx#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/DiagnosticsInterface.cxx#L78-L80'>78&ndash;80</a>, <a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/DiagnosticsInterface.cxx#L83'>83</a>, <a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/DiagnosticsInterface.cxx#L86-L88'>86&ndash;88</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.21%</b></td><td>100%</td><td>100%</td><td><b>97.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/Factory.cxx#L46'>46</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td><b>98.25%</b></td><td>100%</td><td>100%</td><td><b>97.67%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/OptionSet.cxx#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>96.49%</b></td><td>100%</td><td>100%</td><td><b>96.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/Settings.cxx#L121'>121</a>, <a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/base/Settings.cxx#L126'>126</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>99%</b></td><td>100%</td><td>100%</td><td><b>98.91%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/drivers/TransientDriver.cxx#L272'>272</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.67%</b></td><td>100%</td><td>100%</td><td><b>94.37%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.11%</b></td><td>100%</td><td>100%</td><td><b>99.07%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f1132465d656da86bbe27ca2c3ce4633f76c9707/src/neml2/misc/math.cxx'>math.cxx</a></td><td><b>95.74%</b></td><td>100%</td><td><b>9 [...]

2024-07-28 23:46 UTC, hugary1995 commented
Added extensive error checking through the "DiagnosticsInterface".
Added a Python module for visualizing model composition and dependency.

2024-07-29 00:46 UTC, hugary1995 commented
Also updates copyright year to 2024.

2024-07-29 04:08 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>94.21%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/DiagnosticsInterface.cxx'>DiagnosticsInterface.cxx</a></td><td><b>71.70%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/DiagnosticsInterface.cxx#L59'>59</a>, <a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/DiagnosticsInterface.cxx#L62-L64'>62&ndash;64</a>, <a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/DiagnosticsInterface.cxx#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/DiagnosticsInterface.cxx#L78-L80'>78&ndash;80</a>, <a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/DiagnosticsInterface.cxx#L83'>83</a>, <a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/DiagnosticsInterface.cxx#L86-L88'>86&ndash;88</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.21%</b></td><td>100%</td><td>100%</td><td><b>97.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/Factory.cxx#L46'>46</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>96.49%</b></td><td>100%</td><td>100%</td><td><b>96.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/Settings.cxx#L121'>121</a>, <a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/base/Settings.cxx#L126'>126</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>99%</b></td><td>100%</td><td>100%</td><td><b>98.91%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/drivers/TransientDriver.cxx#L272'>272</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.67%</b></td><td>100%</td><td>100%</td><td><b>94.37%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.11%</b></td><td>100%</td><td>100%</td><td><b>99.07%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/misc/math.cxx'>math.cxx</a></td><td><b>95.74%</b></td><td>100%</td><td><b>93.55%</b></td><td><b>96.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/8d51a8831e4f55a4b53b3589ec1e54fe7c040054/src/neml2/misc/mat [...]

2024-07-29 13:37 UTC, hugary1995 commented
Added clang-tidy

2024-07-29 13:48 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>94.21%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/DiagnosticsInterface.cxx'>DiagnosticsInterface.cxx</a></td><td><b>71.70%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/DiagnosticsInterface.cxx#L59'>59</a>, <a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/DiagnosticsInterface.cxx#L62-L64'>62&ndash;64</a>, <a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/DiagnosticsInterface.cxx#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/DiagnosticsInterface.cxx#L78-L80'>78&ndash;80</a>, <a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/DiagnosticsInterface.cxx#L83'>83</a>, <a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/DiagnosticsInterface.cxx#L86-L88'>86&ndash;88</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.21%</b></td><td>100%</td><td>100%</td><td><b>97.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/Factory.cxx#L46'>46</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>96.49%</b></td><td>100%</td><td>100%</td><td><b>96.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/Settings.cxx#L121'>121</a>, <a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/base/Settings.cxx#L126'>126</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>99%</b></td><td>100%</td><td>100%</td><td><b>98.91%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/drivers/TransientDriver.cxx#L272'>272</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.67%</b></td><td>100%</td><td>100%</td><td><b>94.37%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.11%</b></td><td>100%</td><td>100%</td><td><b>99.07%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/misc/math.cxx'>math.cxx</a></td><td><b>95.74%</b></td><td>100%</td><td><b>93.55%</b></td><td><b>96.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/f37e6c767b4fc6aa9dea9f3c1d86cfcb47a46c99/src/neml2/misc/mat [...]

2024-07-31 22:37 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>94.23%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/DiagnosticsInterface.cxx'>DiagnosticsInterface.cxx</a></td><td><b>71.70%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/DiagnosticsInterface.cxx#L59'>59</a>, <a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/DiagnosticsInterface.cxx#L62-L64'>62&ndash;64</a>, <a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/DiagnosticsInterface.cxx#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/DiagnosticsInterface.cxx#L78-L80'>78&ndash;80</a>, <a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/DiagnosticsInterface.cxx#L83'>83</a>, <a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/DiagnosticsInterface.cxx#L86-L88'>86&ndash;88</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.21%</b></td><td>100%</td><td>100%</td><td><b>97.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/Factory.cxx#L46'>46</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>96.49%</b></td><td>100%</td><td>100%</td><td><b>96.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/Settings.cxx#L121'>121</a>, <a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/base/Settings.cxx#L126'>126</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>99%</b></td><td>100%</td><td>100%</td><td><b>98.91%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/drivers/TransientDriver.cxx#L272'>272</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.67%</b></td><td>100%</td><td>100%</td><td><b>94.37%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.11%</b></td><td>100%</td><td>100%</td><td><b>99.07%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/misc/math.cxx'>math.cxx</a></td><td><b>95.74%</b></td><td>100%</td><td><b>93.55%</b></td><td><b>96.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/5fb297d8c01627f38b77512124a2ef4bd0cb2bf3/src/neml2/misc/mat [...]

2024-08-05 20:31 UTC, reverendbedford requested changes
This is way too big to really review anymore, but...
1. There are a few simple/typo type suggestions marked.
2. Adding some timing results to distinguish `disable_AD = false` and `true` might help users, i.e. how much faster will it run (less memory will it use).  You already have these, so maybe just add to that section in the docs.

I don't know, anything in particular I should look at?

2024-08-05 20:31 UTC, reverendbedford commented on CMakeLists.txt
> +set(NEML2_CLANG_TIDY_PATH "clang-tidy" CACHE STRING "Path to the clang-tidy executable")
I may figure this out later, but shouldn't we use CMake to find this?

2024-08-05 20:31 UTC, reverendbedford commented on cmake-variants.yaml
> -        CMAKE_UNITY_BUILD: ON
What's the reason for this change?

2024-08-05 20:31 UTC, reverendbedford commented on doc/content/user/python.md
> +As is the same in the equivalent C++ example, the above Python script parses the input file named "input.i", loads the linear elasticity model named "model", constructs 3 strain tensors, and finally
"As" -> "All"

2024-08-05 20:31 UTC, reverendbedford commented on doc/content/dev/testing.md
> +It is of paramount importance to ensure the correctness of the implementation. NEML2 offers 4 types of tests for different purposes.
"4" -> "four"

2024-08-05 21:04 UTC, hugary1995 commented on CMakeLists.txt
> +set(NEML2_CLANG_TIDY_PATH "clang-tidy" CACHE STRING "Path to the clang-tidy executable")
This is provided as a hint for finding clang-tidy, as it is pretty common to have clang-tidy-14, clang-tidy-15, etc. You can of course use the default hint "clang-tidy" and create symlink for clang-tidy-xx.

2024-08-05 21:04 UTC, hugary1995 commented on cmake-variants.yaml
> -        CMAKE_UNITY_BUILD: ON
The UNITY build doesn't save much time anymore with the improved include dependency and the intermediate torch includes.

2024-08-05 21:12 UTC, hugary1995 commented
> I don't know, anything in particular I should look at?

Here is the list of major changes, if that helps:
- Optionally enable_AD to avoid in-place operation errors
- Fix nonlinear parameter declaration
- Fix input view set up logic
- Move 3rd party deps out of the build tree
- Add regression test for inplace error
- Threaded composed model evaluation
- Avoided for loop and runtime slicing wherever possible
- Variable tensor type runtime introspection, i.e. `model.input_view("foo")->type()` returns an enum corresponding to the tensor type.
- Removed config.h, obsolete methods, and obsolete scripts
- Reorganized source file include hierarchy (CrossRef, math, etc) -- compilation is pretty fast now
- Use emoji to distinguish between input, output, parameter, and buffer in the syntax documentation
- A few renamings (summarized below)
- Python bindings usability is significantly improved. Most notably, we no longer need to call something like `.tensor().tensor()`. Plus we can evaluate model using one of three types of arguments: `torch.Tensor`, `neml2.Tensor`, and `neml2.LabeledVector`, with corresponding return types.
- Also added necessary bindings from the pyzag_integration branch -- there are a few that I don't want to include, but I could be convinced.
- Added a small epsilon to the derivative calculation of RateIndependentPlasticFlowConstraint to prevent nan. This was uncovered by some MOOSE tests.
- I am now letting parameter declaration error out when you declare a nonlinear parameter but its hand-coded derivatives are not implemented. 
- Two new global settings which should be self-explanatory: `buffer_name_separator` and `parameter_name_separator`
- Added extensive error checking through the "DiagnosticsInterface".
- Added a Python module for visualizing model composition and dependency.
- clang-tidy

Renamings:
- `neml2::TorchSize` -> `neml2::Size`
- `neml2::TorchShape` -> `neml2::TensorShape`
- `neml2::TorchShapeRef` -> `neml2::TensorShapeRef`
- `neml2::TorchIndex` -> `neml2::indexing::TensorIndex`
- `neml2::TorchSlice` -> `neml2::indexing::TensorIndices`
- `neml2::BatchTensor` -> `neml2::Tensor`
- `neml2::FixedDimTensor` -> `neml2::PrimitiveTensor`
- Model `SumModel` -> `LinearCombination`

2024-08-05 23:43 UTC, reverendbedford commented
Coverage after merging <b>inference_mode</b> into <b>main</b> will be<table><tbody><tr><th>94.23%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/CrossRef.cxx'>CrossRef.cxx</a></td><td><b>83.87%</b></td><td>100%</td><td><b>75%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/DiagnosticsInterface.cxx'>DiagnosticsInterface.cxx</a></td><td><b>71.70%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/DiagnosticsInterface.cxx#L59'>59</a>, <a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/DiagnosticsInterface.cxx#L62-L64'>62&ndash;64</a>, <a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/DiagnosticsInterface.cxx#L75'>75</a>, <a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/DiagnosticsInterface.cxx#L78-L80'>78&ndash;80</a>, <a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/DiagnosticsInterface.cxx#L83'>83</a>, <a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/DiagnosticsInterface.cxx#L86-L88'>86&ndash;88</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/EnumSelection.cxx'>EnumSelection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/Factory.cxx'>Factory.cxx</a></td><td><b>98.21%</b></td><td>100%</td><td>100%</td><td><b>97.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/Factory.cxx#L46'>46</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/HITParser.cxx'>HITParser.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/NEML2Object.cxx'>NEML2Object.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/NEML2Object.cxx#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/OptionCollection.cxx'>OptionCollection.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/OptionSet.cxx'>OptionSet.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/Registry.cxx'>Registry.cxx</a></td><td><b>75%</b></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/Registry.cxx#L38'>38</a>, <a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/Registry.cxx#L40-L41'>40&ndash;41</a>, <a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/Registry.cxx#L56'>56</a>, <a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/Registry.cxx#L58-L59'>58&ndash;59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/Settings.cxx'>Settings.cxx</a></td><td><b>96.49%</b></td><td>100%</td><td>100%</td><td><b>96.36%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/Settings.cxx#L121'>121</a>, <a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/base/Settings.cxx#L126'>126</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/drivers/Driver.cxx'>Driver.cxx</a></td><td><b>91.67%</b></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/drivers/Driver.cxx#L39'>39</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/drivers/TransientDriver.cxx'>TransientDriver.cxx</a></td><td><b>99%</b></td><td>100%</td><td>100%</td><td><b>98.91%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/drivers/TransientDriver.cxx#L102'>102</a>, <a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/drivers/TransientDriver.cxx#L272'>272</a></td></tr><tr><td colspan='6'><b>src/neml2/drivers/solid_mechanics</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx'>LargeDeformationIncrementalSolidMechanicsDriver.cxx</a></td><td><b>94.67%</b></td><td>100%</td><td>100%</td><td><b>94.37%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L63'>63</a>, <a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L81'>81</a>, <a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/drivers/solid_mechanics/LargeDeformationIncrementalSolidMechanicsDriver.cxx#L83-L84'>83&ndash;84</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx'>SolidMechanicsDriver.cxx</a></td><td><b>99.11%</b></td><td>100%</td><td>100%</td><td><b>99.07%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/drivers/solid_mechanics/SolidMechanicsDriver.cxx#L77'>77</a></td></tr><tr><td colspan='6'><b>src/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/misc/math.cxx'>math.cxx</a></td><td><b>95.74%</b></td><td>100%</td><td><b>93.55%</b></td><td><b>96.18%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/88acd0130b79768a3f0e09144be6c25ef141df9b/src/neml2/misc/mat [...]

2024-08-06 00:59 UTC, reverendbedford approved these changes

2024-08-06 01:05 UTC, merged