Use out-of-place evaluation wherever possible
applied-material-modeling/neml2 pull request #177
Opened 2024-12-04 11:59 UTC by hugary1995

- On-demand matrix assembly
- Fix unit tests, regression tests, and verification tests
- Add more model forward operator APIs
- Refactor LabeledAxis
- Update unit test and drivers to use the new model evaluation APIs

2024-12-15 00:13 UTC, hugary1995 commented
This will also close #165 and #180

2024-12-15 22:24 UTC, hugary1995 commented
I'm pretty sure this is my personal record in # line change.

2024-12-16 17:37 UTC, reverendbedford requested changes
Several minor comments.  The biggest request is to centralize the names of the "canonical" axes to make those easier to configure later on.  Hopefully the detailed comments on this idea make it clear what I mean.

2024-12-16 17:37 UTC, reverendbedford commented on doc/content/system/model.md
> +NEML2 stores each variable in contiguous memory, but does not guarantee contiguity across variables. This choice is made to allow for massive asynchronous evaluation (with the help of lazy tensor) an
```suggestion
NEML2 stores each variable in contiguous memory, but does not guarantee contiguity across variables. This choice is made to allow for massive asynchronous evaluation (with the help of lazy tensors) and to reduce memory consumption (since variables can have different number of batch shapes). However, this choice is not ideal for a family of nonlinear material models whose constitutive updates require solving one (or more) implicit system of equations. To address such issue, NEML2 offers two mechanisms to facilitate the creation of the implicit system (e.g., its residual and Jacobian):
```

2024-12-16 17:37 UTC, reverendbedford commented on doc/content/system/model.md
> +Deriving and implementing derivatives of the forward operator can be cubersome from times to times. NEML2 offers the option to use automatic differentiation (AD) to obtain derivatives. To enable auto
```suggestion
Deriving and implementing derivatives of the forward operator can be cumbersome from times to times. NEML2 offers the option to use automatic differentiation (AD) to obtain derivatives. To enable automatic differentiation, one simply need to override the neml2::Model::request_AD method and specify which derivatives should be computed using AD:
```

2024-12-16 17:37 UTC, reverendbedford commented on doc/content/system/model.md
> +So yes, an axis can be labeled recursively, e.g.,
```suggestion
An axis can be labeled recursively, e.g.,
```

2024-12-16 17:37 UTC, reverendbedford commented on include/neml2/contrib/boost/bitmask_operators.h
Already asked, but do we need this now?

2024-12-16 17:37 UTC, reverendbedford commented on include/neml2/misc/math.h
> +constexpr std::array<std::array<Size, 3>, 3> mandel_reverse_index{
Doesn't really matter, but why this change?

2024-12-16 17:37 UTC, reverendbedford commented on include/neml2/misc/types.h
> +/**
I start to worry we have a lot of magic numbers/strings going on with the canonical axis labels.  I think you do some magic strings in `Variable` as well, though I guess I'll get to that when I find it.  Is there a way to collect all these definitions in one file, in case we want to make global changes to their names later?

2024-12-16 17:37 UTC, reverendbedford commented on include/neml2/solvers/NonlinearSystem.h
> +  struct RES : public Tensor
Real picky, but do we want these to be all caps or do we want `Res`, `Jac`, etc.?

2024-12-16 17:37 UTC, reverendbedford commented on include/neml2/tensors/TensorBaseImpl.h
There are like no comments in this header...

2024-12-16 17:37 UTC, reverendbedford commented on python/tests/pyzag/test_NEML2PyzagModel.py
> +# @pytest.mark.parametrize("input", ["elastic_model", "viscoplastic_model"])
Don't need the comment.

2024-12-16 17:37 UTC, reverendbedford commented on include/neml2/models/solid_mechanics/crystal_plasticity/CrystalMean.h
> +  const crystallography::CrystalGeometry & _crystal_geometry;
Why do we need this?

2024-12-16 17:37 UTC, reverendbedford commented on include/neml2/models/Assembler.h
> +  ValueMap disassemble(const Tensor &) const;
Are these the best names?  Maybe something like `split_by_subaxis` and `split_by_variable` (or `assemble_by_...`).

2024-12-16 17:37 UTC, reverendbedford commented on include/neml2/models/Variable.h
> +class VariableBase
Might be in the specialized classes, but a top-level comment would b nice.

2024-12-16 17:37 UTC, reverendbedford commented on include/neml2/models/Variable.h
> +
Some of these are obvious by the name, but many aren't.  More comments will help.

2024-12-16 17:37 UTC, reverendbedford commented on include/neml2/models/Variable.h
`VariableBase` is a giant class, I don't know if there is a way to split things up a bit.  Maybe there isn't, if so I won't die on this hill.

2024-12-16 17:37 UTC, reverendbedford commented on src/neml2/models/Variable.cxx
> +bool
This is another example of magic strings defining our canonicle axes...  Can we put these types of definitions in one file to make it easy to change things later?

2024-12-16 17:37 UTC, reverendbedford commented on src/neml2/models/LabeledAxis.cxx
> +LabeledAxis::cache_reserved_subaxis(const std::string & axis_name)
Same comment on centralizing definitions of the canonical axes names.

2024-12-16 17:37 UTC, reverendbedford commented on src/neml2/models/LabeledAxisAccessor.cxx
> +  neml_assert(_item_names.size() >= 1, "variable name length must be at least 1");
More magic strings to define the canonical axes.

2024-12-16 17:37 UTC, reverendbedford commented on src/neml2/models/LabeledAxisAccessor.cxx
>    neml_assert(_item_names.size() >= 1, "variable name length must be at least 1");
And here.

2024-12-16 17:37 UTC, reverendbedford commented on python/neml2/pyzag/interface.py
> +    def nstate(self):
Assume you find a way to centralize the string names of the canonical axes, we can wrap that in python to provide these values, rather than the hard-coded strings.

2024-12-16 17:37 UTC, reverendbedford commented on python/neml2/pyzag/interface.py
> +        # neml2.diagnose(self.model)
Why commented out?

2024-12-16 17:37 UTC, reverendbedford commented on python/neml2/pyzag/interface.py
Suprised the linter doesn't complain.

2024-12-16 20:21 UTC, hugary1995 commented on include/neml2/misc/math.h
> +constexpr std::array<std::array<Size, 3>, 3> mandel_reverse_index{
Because clang-tidy suggests using std::array to replace c-arrays. I don't want to disable that check, so I switched to std::array here.

2024-12-16 20:24 UTC, hugary1995 commented on include/neml2/tensors/TensorBaseImpl.h
Cuz they are "implementation". The comments are in the header file "TensorBase.h". I'll add a comment pointing people to the actual header.

2024-12-16 20:28 UTC, hugary1995 commented on include/neml2/models/solid_mechanics/crystal_plasticity/CrystalMean.h
> +  const crystallography::CrystalGeometry & _crystal_geometry;
We need the crystal geometry object to know the number of slip systems. Alternatively, we can ask the user to specify nslip, but that's one additional input option.

Once "list" tensors are better handled, we could infer list shape, and then we can remove the need of crystal geometry in this class.

2024-12-16 20:41 UTC, hugary1995 commented on include/neml2/contrib/boost/bitmask_operators.h
Removed.

2024-12-16 20:44 UTC, hugary1995 commented on include/neml2/models/Variable.h
> +
I'd argue that they are all overriding the base methods. By doxygen convention, the comments inherit from the base methods.

2024-12-16 22:37 UTC, hugary1995 commented on python/neml2/pyzag/interface.py
well this is allowed!

2024-12-16 22:37 UTC, hugary1995 commented on python/neml2/pyzag/interface.py
> +        # neml2.diagnose(self.model)
I added a comment explaining why.

2024-12-16 22:40 UTC, hugary1995 commented on include/neml2/models/Variable.h
It's a little counter-intuitive to split VariableBase. It serves as a polymorphic base so that we could store derived Variable<T> in a homogeneous container. So from that perspective, it's actually better to remain as a single class.

2024-12-16 22:49 UTC, reverendbedford approved these changes

2024-12-16 23:18 UTC, merged