Support spatial velocity gradient input for crystal models
applied-material-modeling/neml2 pull request #187
Opened 2024-12-17 20:09 UTC by reverendbedford

Add some trivial models and tensor types for splitting an `R2` into symmetric and skew parts.

Test a crystal model taking the spatial velocity gradient as input.

2024-12-17 22:09 UTC, hugary1995 approved these changes
Looks good to me. Feel free to merge after addressing the minor comments.

2024-12-17 22:09 UTC, hugary1995 commented on include/neml2/models/R2toSR2.h
> +  /// Invariant of the input tensor
Wrong Doxygen comment.

2024-12-17 22:09 UTC, hugary1995 commented on include/neml2/models/R2toWR2.h
> +  /// Invariant of the input tensor
Wrong doxygen comment.

2024-12-17 22:09 UTC, hugary1995 commented on src/neml2/models/R2toWR2.cxx
> +    auto I = R2(torch::eye(3, A.options()));
Can we change this to `R2::identity(A.options())`?

2024-12-18 03:02 UTC, reverendbedford commented
Don't merge yet, still want to test in MOOSE.

2024-12-20 12:20 UTC, hugary1995 requested changes

2024-12-20 12:20 UTC, hugary1995 commented on CMakePresets.json
> +      ]
These changes are already in main. Remember to rebase/merge before you merge this PR.

2024-12-20 12:20 UTC, hugary1995 commented on include/neml2/models/IncrementalRate.h
> +class IncrementalRate : public Model
IDK if this is the best name. "Incremental" rate sounds a bit weird.

2024-12-20 12:20 UTC, hugary1995 commented on src/neml2/models/IncrementalRate.cxx
> +register_NEML2_object(R2IncrementalRate);
Maybe also instantiate Scalar, SR2, and Vec.

2024-12-20 12:20 UTC, hugary1995 commented on src/neml2/models/IncrementalRate.cxx
> +                  "incremental force variable, "
```suggestion
                  "variable value increment, "
```

2024-12-20 12:20 UTC, hugary1995 commented on src/neml2/models/IncrementalRate.cxx
> +  options.set("variable").doc() = "The variable to take time derivative with";
```suggestion
  options.set_input("variable_increment");
  options.set("variable_increment").doc() = "Increment of the variable to take time derivative with";
```

2024-12-20 12:20 UTC, hugary1995 commented on src/neml2/models/IncrementalRate.cxx
> +      _dv_dt.d(_dv) = Tensor(torch::eye(_dv.base_storage(), _dv.options()) / dt, dt.batch_dim());
This should be replaced with `T::identity_map(_dv.options())`

2024-12-20 12:20 UTC, hugary1995 commented on python/examples/statistical.ipynb
If you look at the image showing the trained mean and and 90% prediction, it's noticeably "worse" than before.

2024-12-20 12:20 UTC, hugary1995 commented on python/neml2/pyzag/interface.py
> +            self.parameter_names.append(pname)
I think it's better to add some comments explaining why we need an additional map between names, and also the use of `getattr` below. I bet we'll forget in the future.

2025-01-02 16:48 UTC, reverendbedford commented on include/neml2/models/IncrementalRate.h
> +class IncrementalRate : public Model
How about `IncrementToRate`

2025-01-02 16:49 UTC, hugary1995 commented on include/neml2/models/IncrementalRate.h
> +class IncrementalRate : public Model
We already have an object named `VariableRate`, so let's call this one `VariableRateFromIncrement` for consistency.

2025-01-02 17:29 UTC, reverendbedford commented on python/examples/statistical.ipynb
Did I touch this?

2025-01-02 17:32 UTC, reverendbedford commented on python/neml2/pyzag/interface.py
> +            self.parameter_names.append(pname)
Good idea.

2025-01-02 17:40 UTC, hugary1995 approved these changes
Fix one typo then good to go.

2025-01-02 17:40 UTC, hugary1995 commented on src/neml2/models/R2toWR2.cxx
> +  options.set("output").doc() = "Output symmetric rank two tensor";
```suggestion
  options.set("output").doc() = "Output skew symmetric rank two tensor";
```

2025-01-02 17:43 UTC, reverendbedford commented on src/neml2/models/R2toWR2.cxx
> +  options.set("output").doc() = "Output symmetric rank two tensor";
Whoops.

2025-01-02 18:16 UTC, merged