Model can be .to(CUDA)
applied-material-modeling/neml2 pull request #35
Opened 2022-12-09 04:02 UTC by hugary1995

1. `Model` inherits from torch::nn::Module
2. submodule registration handled internally by `Model` and `ComposedModel`
3. Material properties registered as `Parameter`s

so... all `Model`s should be to-cuda-able. But I'm flying blind here. I still need to properly deal with TorchDefaults before I can test sending a CPU-constructed `Model` to GPU.

ref #4

2022-12-09 04:09 UTC, hugary1995 commented
ref #10

2022-12-09 04:27 UTC, reverendbedford commented
Total Coverage: <b>83.21%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/utils.h'>utils.h</a></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/utils.h#L31'>31</a></td></tr><tr><td colspan='5'><b>include/miscellaneous</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/miscellaneous/error.h'>error.h</a></td><td>100%</td><td><b>26.09%</b></td><td><b>35.29%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/miscellaneous/error.h#L10'>10</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/miscellaneous/error.h#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/miscellaneous/error.h#L13'>13</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/miscellaneous/error.h#L48'>48</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/miscellaneous/error.h#L49'>49</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/miscellaneous/error.h#L50'>50</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/miscellaneous/error.h#L51'>51</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/miscellaneous/error.h#L67'>67</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/miscellaneous/error.h#L69'>69</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/miscellaneous/error.h#L70'>70</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/miscellaneous/error.h#L71'>71</a></td></tr><tr><td colspan='5'><b>include/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/models/Model.h'>Model.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/BatchTensor.h'>BatchTensor.h</a></td><td>100%</td><td><b>86.67%</b></td><td><b>86.44%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/BatchTensor.h#L105'>105</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/BatchTensor.h#L106'>106</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/BatchTensor.h#L108'>108</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/BatchTensor.h#L110'>110</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/BatchTensor.h#L113'>113</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/BatchTensor.h#L150'>150</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/BatchTensor.h#L152'>152</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/BatchTensor.h#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/FixedDimTensor.h'>FixedDimTensor.h</a></td><td>100%</td><td><b>83.33%</b></td><td><b>84.62%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/FixedDimTensor.h#L38'>38</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/FixedDimTensor.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledAxis.h'>LabeledAxis.h</a></td><td>100%</td><td><b>72.73%</b></td><td><b>81.25%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledAxis.h#L132'>132</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledAxis.h#L135'>135</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledAxis.h#L138'>138</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledMatrix.h'>LabeledMatrix.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledTensor.h'>LabeledTensor.h</a></td><td>100%</td><td><b>93.48%</b></td><td><b>94.05%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledTensor.h#L149'>149</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledTensor.h#L153'>153</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledTensor.h#L227'>227</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledTensor.h#L30'>30</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledTensor.h#L57'>57</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledVector.h'>LabeledVector.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/Scalar.h'>Scalar.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/Scalar.h#L28'>28</a></td></tr><tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/utils.cxx'>utils.cxx</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/utils.cxx#L10'>10</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/utils.cxx#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/utils.cxx#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/utils.cxx#L13'>13</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/utils.cxx#L6'>6</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/utils.cxx#L8'>8</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/utils.cxx#L9'>9</a></td></tr><tr><td colspan='5'><b>src/miscellaneous</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/miscellaneous/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>src/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/models/ADModel.cxx'>ADModel.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/models/ADSecDerivModel.cxx'>ADSecDerivModel.cxx</a></td><td>100%</td><td><b>50%</b></td><td><b>51.52%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/models/ADSecDerivModel.cxx#L10'>10</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/models/ADSecDerivModel.cxx#L14'>14</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/models/ADSecDerivModel.cxx#L17'>17</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/models/ADSecDerivModel.cxx#L20'>20</a>, <a href='https:/ [...]

2022-12-09 17:31 UTC, reverendbedford commented
See :)

2022-12-09 17:31 UTC, hugary1995 commented
easy

2022-12-09 17:46 UTC, hugary1995 commented
For context, which I forgot to mention just now in the meeting, I've convinced myself that `LabeledAxis` can always stay on the CPU. That choice significantly reduces the amount of work. If at anytime we figured the opposite, although I doubt it, it's possible to make the switch.

2022-12-09 17:59 UTC, reverendbedford commented
Total Coverage: <b>83.21%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/utils.h'>utils.h</a></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/utils.h#L31'>31</a></td></tr><tr><td colspan='5'><b>include/miscellaneous</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/miscellaneous/error.h'>error.h</a></td><td>100%</td><td><b>26.09%</b></td><td><b>35.29%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/miscellaneous/error.h#L10'>10</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/miscellaneous/error.h#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/miscellaneous/error.h#L13'>13</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/miscellaneous/error.h#L48'>48</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/miscellaneous/error.h#L49'>49</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/miscellaneous/error.h#L50'>50</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/miscellaneous/error.h#L51'>51</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/miscellaneous/error.h#L67'>67</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/miscellaneous/error.h#L69'>69</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/miscellaneous/error.h#L70'>70</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/miscellaneous/error.h#L71'>71</a></td></tr><tr><td colspan='5'><b>include/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/models/Model.h'>Model.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/BatchTensor.h'>BatchTensor.h</a></td><td>100%</td><td><b>86.67%</b></td><td><b>86.44%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/BatchTensor.h#L105'>105</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/BatchTensor.h#L106'>106</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/BatchTensor.h#L108'>108</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/BatchTensor.h#L110'>110</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/BatchTensor.h#L113'>113</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/BatchTensor.h#L150'>150</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/BatchTensor.h#L152'>152</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/BatchTensor.h#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/FixedDimTensor.h'>FixedDimTensor.h</a></td><td>100%</td><td><b>83.33%</b></td><td><b>84.62%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/FixedDimTensor.h#L38'>38</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/FixedDimTensor.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/LabeledAxis.h'>LabeledAxis.h</a></td><td>100%</td><td><b>72.73%</b></td><td><b>81.25%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/LabeledAxis.h#L132'>132</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/LabeledAxis.h#L135'>135</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/LabeledAxis.h#L138'>138</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/LabeledMatrix.h'>LabeledMatrix.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/LabeledTensor.h'>LabeledTensor.h</a></td><td>100%</td><td><b>93.48%</b></td><td><b>94.05%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/LabeledTensor.h#L149'>149</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/LabeledTensor.h#L153'>153</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/LabeledTensor.h#L227'>227</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/LabeledTensor.h#L30'>30</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/LabeledTensor.h#L57'>57</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/LabeledVector.h'>LabeledVector.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/Scalar.h'>Scalar.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/include/tensors/Scalar.h#L28'>28</a></td></tr><tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/src/utils.cxx'>utils.cxx</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/src/utils.cxx#L10'>10</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/src/utils.cxx#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/src/utils.cxx#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/385ff8d69e136e42990ec06b754a0e5c0dc0642c/src/utils.cxx#L13'>13</a>, <a href='https://github.com/ [...]

2022-12-09 18:26 UTC, reverendbedford requested changes
1. `const std::shared_ptr<> &` seems perverse to me...
2. Passing `std::shared_ptr<>` objects to models higher in the dependency tree may be necessary, but think about if they need to own a share of the "lower" models or not.  If they just need a weak reference either pass by reference or weak_ptr or something.
3. Uhh, I must have missed it, but is there the option for CUDA tests if you have CUDA available?

2022-12-09 18:26 UTC, reverendbedford commented on include/models/ComposedModel.h
> +  void resolve_dependency(const std::shared_ptr<Model> & i,
Is there any conceivable reason not to use `const Model &`?

2022-12-09 18:26 UTC, reverendbedford commented on include/models/ComposedModel.h
> +              const std::shared_ptr<Model> & model,
Same comment.

2022-12-09 18:26 UTC, reverendbedford commented on src/models/ComposedModel.cxx
> +                      const std::shared_ptr<Model> & model,
Same comment.

2022-12-09 18:26 UTC, reverendbedford commented on src/models/solid_mechanics/AssociativePlasticFlowDirection.cxx
> +                                                                 std::shared_ptr<YieldFunction> f)
Do the "higher" models need to own a share of the "lower" models, or are they all allocated elsewhere?  If you don't need to share ownership than passing by reference (or with a `weak_ptr` if you really need a pointer) would be better.

2022-12-09 18:26 UTC, reverendbedford commented on src/models/Model.cxx
> +Model::registerModel(const std::shared_ptr<Model> & model)
Same comment.

2022-12-09 18:26 UTC, reverendbedford commented on src/models/solid_mechanics/AssociativePlasticHardening.cxx
> +                                                         std::shared_ptr<YieldFunction> f)
Same ownership and reference versus pointer question.

2022-12-09 18:26 UTC, reverendbedford commented on tests/src/UniaxialStrainStructuralDriver.cxx
> +  : _model(*model),
If you're dereferencing anyway why not just pass in the constant reference?

2022-12-09 18:26 UTC, reverendbedford commented on tests/include/UniaxialStrainStructuralDriver.h
> +  UniaxialStrainStructuralDriver(const std::shared_ptr<Model> & model,
Same comment.

2022-12-09 18:34 UTC, hugary1995 commented
The libtorch API requires a shared_ptr to register submodule: https://pytorch.org/cppdocs/api/classtorch_1_1nn_1_1_module.html#_CPPv4I0EN5torch2nn6Module15register_moduleENSt10shared_ptrI10ModuleTypeEENSt6stringENSt10shared_ptrI10ModuleTypeEE

Other than that, I guess it is because the factory will make shared_ptrs anyways...

2022-12-09 18:37 UTC, hugary1995 commented
> Uhh, I must have missed it, but is there the option for CUDA tests if you have CUDA available?

I just check it in the unit test itself: `if (torch::cuda::is_available())` blah blah.

2022-12-09 21:11 UTC, reverendbedford commented
> > Uhh, I must have missed it, but is there the option for CUDA tests if you have CUDA available?
> 
> I just check it in the unit test itself: `if (torch::cuda::is_available())` blah blah.

I just missed it, yes.

2022-12-09 21:58 UTC, hugary1995 commented on include/models/ComposedModel.h
> +  void resolve_dependency(const std::shared_ptr<Model> & i,
This one is special, I need to push this `i` to evaluation order, so that later on I use the evaluation order vector to register torch submodules. As torch expects shared_ptr, I need shared_ptr here.

2022-12-09 21:59 UTC, hugary1995 commented on include/models/ComposedModel.h
> +              const std::shared_ptr<Model> & model,
This one is real. I've changed it to const Model &

2022-12-09 21:59 UTC, hugary1995 commented on src/models/ComposedModel.cxx
> +                      const std::shared_ptr<Model> & model,
yep, fixed it.

2022-12-09 21:59 UTC, hugary1995 commented on src/models/solid_mechanics/AssociativePlasticFlowDirection.cxx
> +                                                                 std::shared_ptr<YieldFunction> f)
Same reason, torch expects shared_ptr.

2022-12-09 22:00 UTC, hugary1995 commented on src/models/Model.cxx
> +Model::registerModel(const std::shared_ptr<Model> & model)
Similar reasoning: I need to register the registered model into torch as well (as submodule).

2022-12-09 22:01 UTC, hugary1995 commented on src/models/solid_mechanics/AssociativePlasticHardening.cxx
> +                                                         std::shared_ptr<YieldFunction> f)
torch to blame again.

2022-12-09 22:05 UTC, hugary1995 commented on tests/src/UniaxialStrainStructuralDriver.cxx
> +  : _model(*model),
This one I'm not sure. My plan is to have something like this in the input file in the future:
```python
[driver]
  type = UniaxialStrainStructuralDriver
  model = "rate_model"
  max_strain = 0.2
  end_time = 100
  nsteps = 100
[]
```
So eventually I will need to go into the factory/warehouse to retrieve the object based on the model name.

I haven't convinced myself that the factory will ever only need to give me `const NEML2Object &`, or does it have to give me `std::shared_ptr<NEML2Object>`.

2022-12-09 22:08 UTC, reverendbedford commented
Total Coverage: <b>83.21%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/utils.h'>utils.h</a></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/utils.h#L31'>31</a></td></tr><tr><td colspan='5'><b>include/miscellaneous</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/miscellaneous/error.h'>error.h</a></td><td>100%</td><td><b>26.09%</b></td><td><b>35.29%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/miscellaneous/error.h#L10'>10</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/miscellaneous/error.h#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/miscellaneous/error.h#L13'>13</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/miscellaneous/error.h#L48'>48</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/miscellaneous/error.h#L49'>49</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/miscellaneous/error.h#L50'>50</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/miscellaneous/error.h#L51'>51</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/miscellaneous/error.h#L67'>67</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/miscellaneous/error.h#L69'>69</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/miscellaneous/error.h#L70'>70</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/miscellaneous/error.h#L71'>71</a></td></tr><tr><td colspan='5'><b>include/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/models/Model.h'>Model.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/BatchTensor.h'>BatchTensor.h</a></td><td>100%</td><td><b>86.67%</b></td><td><b>86.44%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/BatchTensor.h#L105'>105</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/BatchTensor.h#L106'>106</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/BatchTensor.h#L108'>108</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/BatchTensor.h#L110'>110</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/BatchTensor.h#L113'>113</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/BatchTensor.h#L150'>150</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/BatchTensor.h#L152'>152</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/BatchTensor.h#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/FixedDimTensor.h'>FixedDimTensor.h</a></td><td>100%</td><td><b>83.33%</b></td><td><b>84.62%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/FixedDimTensor.h#L38'>38</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/FixedDimTensor.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/LabeledAxis.h'>LabeledAxis.h</a></td><td>100%</td><td><b>72.73%</b></td><td><b>81.25%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/LabeledAxis.h#L132'>132</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/LabeledAxis.h#L135'>135</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/LabeledAxis.h#L138'>138</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/LabeledMatrix.h'>LabeledMatrix.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/LabeledTensor.h'>LabeledTensor.h</a></td><td>100%</td><td><b>93.33%</b></td><td><b>94.05%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/LabeledTensor.h#L149'>149</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/LabeledTensor.h#L153'>153</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/LabeledTensor.h#L227'>227</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/LabeledTensor.h#L30'>30</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/LabeledTensor.h#L57'>57</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/LabeledVector.h'>LabeledVector.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/Scalar.h'>Scalar.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/include/tensors/Scalar.h#L28'>28</a></td></tr><tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/src/utils.cxx'>utils.cxx</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/src/utils.cxx#L10'>10</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/src/utils.cxx#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/src/utils.cxx#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/818fece8b72d3ced9854c9f8bc2414cc9e3a2dba/src/utils.cxx#L13'>13</a>, <a href='https://github.com/ [...]

2022-12-09 22:09 UTC, hugary1995 commented on tests/src/UniaxialStrainStructuralDriver.cxx
> +  : _model(*model),
nvmd, I convinced myself -- the driver never takes ownership of the Model.

2022-12-09 22:11 UTC, hugary1995 commented
ok I'm happy with this now.

2022-12-09 22:19 UTC, reverendbedford commented
Total Coverage: <b>83.21%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/utils.h'>utils.h</a></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/utils.h#L31'>31</a></td></tr><tr><td colspan='5'><b>include/miscellaneous</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/miscellaneous/error.h'>error.h</a></td><td>100%</td><td><b>26.09%</b></td><td><b>35.29%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/miscellaneous/error.h#L10'>10</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/miscellaneous/error.h#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/miscellaneous/error.h#L13'>13</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/miscellaneous/error.h#L48'>48</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/miscellaneous/error.h#L49'>49</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/miscellaneous/error.h#L50'>50</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/miscellaneous/error.h#L51'>51</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/miscellaneous/error.h#L67'>67</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/miscellaneous/error.h#L69'>69</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/miscellaneous/error.h#L70'>70</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/miscellaneous/error.h#L71'>71</a></td></tr><tr><td colspan='5'><b>include/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/models/Model.h'>Model.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/BatchTensor.h'>BatchTensor.h</a></td><td>100%</td><td><b>86.67%</b></td><td><b>86.44%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/BatchTensor.h#L105'>105</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/BatchTensor.h#L106'>106</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/BatchTensor.h#L108'>108</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/BatchTensor.h#L110'>110</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/BatchTensor.h#L113'>113</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/BatchTensor.h#L150'>150</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/BatchTensor.h#L152'>152</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/BatchTensor.h#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/FixedDimTensor.h'>FixedDimTensor.h</a></td><td>100%</td><td><b>83.33%</b></td><td><b>84.62%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/FixedDimTensor.h#L38'>38</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/FixedDimTensor.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/LabeledAxis.h'>LabeledAxis.h</a></td><td>100%</td><td><b>72.73%</b></td><td><b>81.25%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/LabeledAxis.h#L132'>132</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/LabeledAxis.h#L135'>135</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/LabeledAxis.h#L138'>138</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/LabeledMatrix.h'>LabeledMatrix.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/LabeledTensor.h'>LabeledTensor.h</a></td><td>100%</td><td><b>93.33%</b></td><td><b>94.05%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/LabeledTensor.h#L149'>149</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/LabeledTensor.h#L153'>153</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/LabeledTensor.h#L227'>227</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/LabeledTensor.h#L30'>30</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/LabeledTensor.h#L57'>57</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/LabeledVector.h'>LabeledVector.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/Scalar.h'>Scalar.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/include/tensors/Scalar.h#L28'>28</a></td></tr><tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/src/utils.cxx'>utils.cxx</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/src/utils.cxx#L10'>10</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/src/utils.cxx#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/src/utils.cxx#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/f2b32ae6a507c993e1afe8ee01be0b9972195462/src/utils.cxx#L13'>13</a>, <a href='https://github.com/ [...]

2022-12-09 22:36 UTC, reverendbedford commented
Total Coverage: <b>83.21%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/utils.h'>utils.h</a></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/utils.h#L31'>31</a></td></tr><tr><td colspan='5'><b>include/miscellaneous</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/miscellaneous/error.h'>error.h</a></td><td>100%</td><td><b>26.09%</b></td><td><b>35.29%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/miscellaneous/error.h#L10'>10</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/miscellaneous/error.h#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/miscellaneous/error.h#L13'>13</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/miscellaneous/error.h#L48'>48</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/miscellaneous/error.h#L49'>49</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/miscellaneous/error.h#L50'>50</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/miscellaneous/error.h#L51'>51</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/miscellaneous/error.h#L67'>67</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/miscellaneous/error.h#L69'>69</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/miscellaneous/error.h#L70'>70</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/miscellaneous/error.h#L71'>71</a></td></tr><tr><td colspan='5'><b>include/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/models/Model.h'>Model.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/BatchTensor.h'>BatchTensor.h</a></td><td>100%</td><td><b>86.67%</b></td><td><b>86.44%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/BatchTensor.h#L105'>105</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/BatchTensor.h#L106'>106</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/BatchTensor.h#L108'>108</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/BatchTensor.h#L110'>110</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/BatchTensor.h#L113'>113</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/BatchTensor.h#L150'>150</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/BatchTensor.h#L152'>152</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/BatchTensor.h#L35'>35</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/FixedDimTensor.h'>FixedDimTensor.h</a></td><td>100%</td><td><b>83.33%</b></td><td><b>84.62%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/FixedDimTensor.h#L38'>38</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/FixedDimTensor.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/LabeledAxis.h'>LabeledAxis.h</a></td><td>100%</td><td><b>72.73%</b></td><td><b>81.25%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/LabeledAxis.h#L132'>132</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/LabeledAxis.h#L135'>135</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/LabeledAxis.h#L138'>138</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/LabeledMatrix.h'>LabeledMatrix.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/LabeledTensor.h'>LabeledTensor.h</a></td><td>100%</td><td><b>93.33%</b></td><td><b>94.05%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/LabeledTensor.h#L149'>149</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/LabeledTensor.h#L153'>153</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/LabeledTensor.h#L227'>227</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/LabeledTensor.h#L30'>30</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/LabeledTensor.h#L57'>57</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/LabeledVector.h'>LabeledVector.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/Scalar.h'>Scalar.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/include/tensors/Scalar.h#L28'>28</a></td></tr><tr><td colspan='5'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/src/utils.cxx'>utils.cxx</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/src/utils.cxx#L10'>10</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/src/utils.cxx#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/src/utils.cxx#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/11cb3dd56d0d26668a9675a91cc6c730e4d0180c/src/utils.cxx#L13'>13</a>, <a href='https://github.com/ [...]

2022-12-10 05:57 UTC, hugary1995 commented
I guess I'll take the liberty to merge this :)

2022-12-10 05:57 UTC, merged