Setup stress control model AND improve user interface
applied-material-modeling/neml2 pull request #46
Opened 2022-12-11 01:45 UTC by hugary1995

close #43
close #38

2022-12-11 01:45 UTC, hugary1995 commented
Results look reasonable to me:

![Figure_1](https://user-images.githubusercontent.com/31555204/206882621-fb4baa29-0d69-43bd-ab06-fb27d015f87d.png)

2022-12-11 01:47 UTC, reverendbedford commented
You can add a regression test that shows you can go from strain -> stress and then back from stress -> strain and get the same strains.  But yes, they look reasonable.

2022-12-11 01:50 UTC, hugary1995 commented
Yeah, good point.

2022-12-11 01:51 UTC, hugary1995 commented
BTW, this is _without_ an outer newton loop.

2022-12-11 02:12 UTC, reverendbedford commented
Total Coverage: <b>83.73%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/misc/error.h'>error.h</a></td><td>100%</td><td><b>26.09%</b></td><td><b>35.29%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/misc/error.h#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/misc/error.h#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/misc/error.h#L14'>14</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/misc/error.h#L49'>49</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/misc/error.h#L50'>50</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/misc/error.h#L51'>51</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/misc/error.h#L52'>52</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/misc/error.h#L68'>68</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/misc/error.h#L70'>70</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/misc/error.h#L71'>71</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/misc/error.h#L72'>72</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/misc/utils.h'>utils.h</a></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/misc/utils.h#L33'>33</a></td></tr><tr><td colspan='5'><b>include/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/models/Model.h'>Model.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/BatchTensor.h'>BatchTensor.h</a></td><td>100%</td><td><b>86.67%</b></td><td><b>86.44%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/BatchTensor.h#L107'>107</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/BatchTensor.h#L108'>108</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/BatchTensor.h#L110'>110</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/BatchTensor.h#L112'>112</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/BatchTensor.h#L115'>115</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/BatchTensor.h#L152'>152</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/BatchTensor.h#L154'>154</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/BatchTensor.h#L37'>37</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/FixedDimTensor.h'>FixedDimTensor.h</a></td><td>100%</td><td><b>83.33%</b></td><td><b>84.62%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/FixedDimTensor.h#L40'>40</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/FixedDimTensor.h#L51'>51</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledAxis.h'>LabeledAxis.h</a></td><td>100%</td><td><b>72.73%</b></td><td><b>81.25%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledAxis.h#L134'>134</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledAxis.h#L137'>137</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledAxis.h#L140'>140</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledMatrix.h'>LabeledMatrix.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledTensor.h'>LabeledTensor.h</a></td><td>100%</td><td><b>93.33%</b></td><td><b>94.05%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledTensor.h#L151'>151</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledTensor.h#L155'>155</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledTensor.h#L229'>229</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledTensor.h#L32'>32</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledTensor.h#L59'>59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/LabeledVector.h'>LabeledVector.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/Scalar.h'>Scalar.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/undefined/include/tensors/Scalar.h#L30'>30</a></td></tr><tr><td colspan='5'><b>src/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/misc/utils.cxx'>utils.cxx</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/misc/utils.cxx#L10'>10</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/misc/utils.cxx#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/misc/utils.cxx#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/misc/utils.cxx#L13'>13</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/misc/utils.cxx#L14'>14</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/misc/utils.cxx#L15'>15</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/misc/utils.cxx#L8'>8</a></td></tr><tr><td colspan='5'><b>src/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/models/ADModel.cxx'>ADModel.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/models/ADSecDerivModel.cxx'>ADSecDerivModel.cxx</a></td><td>100%</td><td><b>50%</b></td><td><b>51.52%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/models/ADSecDerivModel.cxx#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/models/ADSecDerivModel.cxx#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/models/ADSecDerivModel.cxx#L16'>16</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/models/ADSecDerivModel.cxx#L19'>19</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefined/src/models/ADSecDerivModel.cxx#L22'>22</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/undefin [...]

2022-12-11 22:17 UTC, reverendbedford commented
Total Coverage: <b>83.98%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/misc/error.h'>error.h</a></td><td>100%</td><td><b>26.09%</b></td><td><b>35.29%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/misc/error.h#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/misc/error.h#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/misc/error.h#L14'>14</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/misc/error.h#L49'>49</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/misc/error.h#L50'>50</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/misc/error.h#L51'>51</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/misc/error.h#L52'>52</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/misc/error.h#L68'>68</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/misc/error.h#L70'>70</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/misc/error.h#L71'>71</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/misc/error.h#L72'>72</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/misc/utils.h'>utils.h</a></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/misc/utils.h#L33'>33</a></td></tr><tr><td colspan='5'><b>include/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/models/Model.h'>Model.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/BatchTensor.h'>BatchTensor.h</a></td><td>100%</td><td><b>86.67%</b></td><td><b>86.44%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/BatchTensor.h#L107'>107</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/BatchTensor.h#L108'>108</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/BatchTensor.h#L110'>110</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/BatchTensor.h#L112'>112</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/BatchTensor.h#L115'>115</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/BatchTensor.h#L152'>152</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/BatchTensor.h#L154'>154</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/BatchTensor.h#L37'>37</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/FixedDimTensor.h'>FixedDimTensor.h</a></td><td>100%</td><td><b>83.33%</b></td><td><b>84.62%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/FixedDimTensor.h#L40'>40</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/FixedDimTensor.h#L51'>51</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/LabeledAxis.h'>LabeledAxis.h</a></td><td>100%</td><td><b>72.73%</b></td><td><b>81.25%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/LabeledAxis.h#L145'>145</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/LabeledAxis.h#L148'>148</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/LabeledAxis.h#L151'>151</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/LabeledMatrix.h'>LabeledMatrix.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/LabeledTensor.h'>LabeledTensor.h</a></td><td>100%</td><td><b>94.17%</b></td><td><b>93.98%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/LabeledTensor.h#L151'>151</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/LabeledTensor.h#L155'>155</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/LabeledTensor.h#L232'>232</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/LabeledTensor.h#L32'>32</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/LabeledTensor.h#L59'>59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/LabeledVector.h'>LabeledVector.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/Scalar.h'>Scalar.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/include/tensors/Scalar.h#L30'>30</a></td></tr><tr><td colspan='5'><b>src/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/src/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/src/misc/utils.cxx'>utils.cxx</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947844601f320/src/misc/utils.cxx#L10'>10</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6604795ae2af040ac503047d069947 [...]

2022-12-11 22:39 UTC, hugary1995 commented
I've also improved the user interface. You can see it live in `src/models/solid_mechanics/J2IsotropicYieldFunction.cxx`

There isn't much of a reduction in terms of number of lines, but it does encapsulate all the information required to access a LabeledTensor in an object called `LabeledAxisAccessor`. Though I'm not sure if this is what you were after, so let's discuss...

2022-12-11 23:02 UTC, reverendbedford commented
Total Coverage: <b>83.91%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/misc/error.h'>error.h</a></td><td>100%</td><td><b>26.09%</b></td><td><b>35.29%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/misc/error.h#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/misc/error.h#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/misc/error.h#L14'>14</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/misc/error.h#L49'>49</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/misc/error.h#L50'>50</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/misc/error.h#L51'>51</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/misc/error.h#L52'>52</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/misc/error.h#L68'>68</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/misc/error.h#L70'>70</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/misc/error.h#L71'>71</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/misc/error.h#L72'>72</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/misc/utils.h'>utils.h</a></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/misc/utils.h#L33'>33</a></td></tr><tr><td colspan='5'><b>include/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/models/Model.h'>Model.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/BatchTensor.h'>BatchTensor.h</a></td><td>100%</td><td><b>86.67%</b></td><td><b>86.44%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/BatchTensor.h#L107'>107</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/BatchTensor.h#L108'>108</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/BatchTensor.h#L110'>110</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/BatchTensor.h#L112'>112</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/BatchTensor.h#L115'>115</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/BatchTensor.h#L152'>152</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/BatchTensor.h#L154'>154</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/BatchTensor.h#L37'>37</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/FixedDimTensor.h'>FixedDimTensor.h</a></td><td>100%</td><td><b>83.33%</b></td><td><b>84.62%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/FixedDimTensor.h#L40'>40</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/FixedDimTensor.h#L51'>51</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/LabeledAxis.h'>LabeledAxis.h</a></td><td>100%</td><td><b>72.73%</b></td><td><b>81.25%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/LabeledAxis.h#L145'>145</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/LabeledAxis.h#L148'>148</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/LabeledAxis.h#L151'>151</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/LabeledMatrix.h'>LabeledMatrix.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/LabeledTensor.h'>LabeledTensor.h</a></td><td>100%</td><td><b>94.55%</b></td><td><b>93.98%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/LabeledTensor.h#L151'>151</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/LabeledTensor.h#L155'>155</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/LabeledTensor.h#L232'>232</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/LabeledTensor.h#L32'>32</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/LabeledTensor.h#L59'>59</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/LabeledVector.h'>LabeledVector.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/Scalar.h'>Scalar.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/include/tensors/Scalar.h#L30'>30</a></td></tr><tr><td colspan='5'><b>src/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/src/misc/error.cxx'>error.cxx</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/src/misc/utils.cxx'>utils.cxx</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6a4bca793f0/src/misc/utils.cxx#L10'>10</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/40e3aebd335bc9a3f24631608f36b6 [...]

2022-12-12 20:43 UTC, reverendbedford requested changes
1. The new `TimeIntegration` class confuses me because it doesn't seem to interact with `ImplicitTimeIntegration`
2. The elastic compliance object could be done in a better way to avoid more work later on when we have other anisotropic elasticity models around.

2022-12-12 20:43 UTC, reverendbedford commented on src/models/solid_mechanics/LinearIsotropicCompliance.cxx
> +  auto S = SymSymR4::init(SymSymR4::FillMethod::isotropic_E_nu, {_E, _nu}).inverse();
I mean why not save the expensive inverse operation if we're not connecting it to the stiffness model.  You can of course write the linear isotropic compliance tensor directly as a function of E and nu.

Actually, why not make this object more generic and template it on a `LinearElasticStiffness` type, grab the tensor from that type, and invert it if you're going to do it this way?  That way as I had other asymmetric elastic models we won't need to rewrite anything.

2022-12-12 20:43 UTC, reverendbedford commented on tests/src/UniaxialStrainStructuralDriver.cxx
> +  for (TorchSize i = 1; i < _nsteps + 1; i++)
Ah you noticed that did you.

2022-12-12 20:43 UTC, reverendbedford commented on src/models/TimeIntegration.cxx
> +#include "models/TimeIntegration.h"
I'm confused here as to if this is just a Backward Euler time integration or if it's supposed to cover all potential time integration schemes.  What happened to the `ImplicitTimeIntegration`

2022-12-12 21:01 UTC, hugary1995 commented on src/models/solid_mechanics/LinearIsotropicCompliance.cxx
> +  auto S = SymSymR4::init(SymSymR4::FillMethod::isotropic_E_nu, {_E, _nu}).inverse();
ya, this is doable. Let me try.

2022-12-12 22:46 UTC, reverendbedford commented
Total Coverage: <b>78.89%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/misc/error.h'>error.h</a></td><td>100%</td><td><b>19.23%</b></td><td><b>35.29%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/misc/error.h#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/misc/error.h#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/misc/error.h#L14'>14</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/misc/error.h#L49'>49</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/misc/error.h#L50'>50</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/misc/error.h#L51'>51</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/misc/error.h#L52'>52</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/misc/error.h#L68'>68</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/misc/error.h#L70'>70</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/misc/error.h#L71'>71</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/misc/error.h#L72'>72</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/misc/utils.h'>utils.h</a></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/misc/utils.h#L33'>33</a></td></tr><tr><td colspan='5'><b>include/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/models/Model.h'>Model.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h'>BatchTensor.h</a></td><td>100%</td><td><b>60%</b></td><td><b>64.41%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L107'>107</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L108'>108</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L110'>110</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L112'>112</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L115'>115</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L138'>138</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L140'>140</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L145'>145</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L147'>147</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L152'>152</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L154'>154</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L205'>205</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L207'>207</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L209'>209</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L214'>214</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L215'>215</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L216'>216</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L217'>217</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L246'>246</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L248'>248</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/BatchTensor.h#L37'>37</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/FixedDimTensor.h'>FixedDimTensor.h</a></td><td>100%</td><td><b>66.67%</b></td><td><b>84.62%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/FixedDimTensor.h#L40'>40</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/FixedDimTensor.h#L51'>51</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/LabeledAxis.h'>LabeledAxis.h</a></td><td>100%</td><td><b>72.73%</b></td><td><b>81.25%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/LabeledAxis.h#L145'>145</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/LabeledAxis.h#L148'>148</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/LabeledAxis.h#L151'>151</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/LabeledMatrix.h'>LabeledMatrix.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/LabeledTensor.h'>LabeledTensor.h</a></td><td>100%</td><td><b>94.55%</b></td><td><b>93.98%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/1cb1cae775e3eecfdec24545da3ee007eebb8195/include/tensors/LabeledTensor.h#L151'>1 [...]

2022-12-13 14:02 UTC, hugary1995 commented
The general form for first order integration is
```
r = (s_np1 - s_n) / dt - F(s_np1, s_n, s_nm1, f_np1, f_n, f_nm1)
```
for an alpha method, this simplifies to
```
r = (s_np1 - s_n) / dt - a F(s_np1, s_n, f_np1, f_n) - (1 - a) F(s_n, s_nm1, f_n, f_nm1)
```

Right now, we only use the fully implicit case `a = 1`. The issue is if we want to handle `0 < a < 1`, we also need to keep track of `s_nm1` and `f_nm1`.

That's doable, but is it worth the headache? I guess what I can do for now is to write things in a general form, but only accept a fully implicit time integration rule. What do you think?

2022-12-14 17:32 UTC, hugary1995 commented
I've created issue #50 to keep track of the time integration stuff. I will address that in a separate PR.
This branch should fix the recursive assembly bug when you have sub-sub-axes. But I am flying blind. I will try to cook up a basic unit test.

2022-12-14 17:59 UTC, reverendbedford commented
Total Coverage: <b>78.37%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/misc/error.h'>error.h</a></td><td>100%</td><td><b>19.23%</b></td><td><b>35.29%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/misc/error.h#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/misc/error.h#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/misc/error.h#L14'>14</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/misc/error.h#L49'>49</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/misc/error.h#L50'>50</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/misc/error.h#L51'>51</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/misc/error.h#L52'>52</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/misc/error.h#L68'>68</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/misc/error.h#L70'>70</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/misc/error.h#L71'>71</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/misc/error.h#L72'>72</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/misc/utils.h'>utils.h</a></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/misc/utils.h#L33'>33</a></td></tr><tr><td colspan='5'><b>include/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/models/Model.h'>Model.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h'>BatchTensor.h</a></td><td>100%</td><td><b>56.25%</b></td><td><b>62.30%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L107'>107</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L108'>108</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L110'>110</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L112'>112</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L115'>115</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L138'>138</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L140'>140</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L145'>145</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L147'>147</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L152'>152</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L154'>154</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L205'>205</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L207'>207</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L209'>209</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L214'>214</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L215'>215</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L216'>216</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L217'>217</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L239'>239</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L241'>241</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L246'>246</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L248'>248</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/BatchTensor.h#L37'>37</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/FixedDimTensor.h'>FixedDimTensor.h</a></td><td>100%</td><td><b>66.67%</b></td><td><b>84.62%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/FixedDimTensor.h#L40'>40</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/FixedDimTensor.h#L51'>51</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/LabeledAxis.h'>LabeledAxis.h</a></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/LabeledAxis.h#L139'>139</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/LabeledAxis.h#L142'>142</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/LabeledAxis.h#L145'>145</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/ca9091db2c42ec85d836d344700dc10173a8d403/include/tensors/LabeledMatrix.h'>LabeledMatrix.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/ca90 [...]

2022-12-14 18:27 UTC, reverendbedford commented
Total Coverage: <b>78.59%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/misc/error.h'>error.h</a></td><td>100%</td><td><b>19.23%</b></td><td><b>35.29%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/misc/error.h#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/misc/error.h#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/misc/error.h#L14'>14</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/misc/error.h#L49'>49</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/misc/error.h#L50'>50</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/misc/error.h#L51'>51</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/misc/error.h#L52'>52</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/misc/error.h#L68'>68</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/misc/error.h#L70'>70</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/misc/error.h#L71'>71</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/misc/error.h#L72'>72</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/misc/utils.h'>utils.h</a></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/misc/utils.h#L33'>33</a></td></tr><tr><td colspan='5'><b>include/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/models/Model.h'>Model.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h'>BatchTensor.h</a></td><td>100%</td><td><b>56.25%</b></td><td><b>62.30%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L107'>107</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L108'>108</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L110'>110</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L112'>112</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L115'>115</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L138'>138</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L140'>140</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L145'>145</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L147'>147</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L152'>152</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L154'>154</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L205'>205</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L207'>207</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L209'>209</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L214'>214</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L215'>215</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L216'>216</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L217'>217</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L239'>239</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L241'>241</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L246'>246</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L248'>248</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/BatchTensor.h#L37'>37</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/FixedDimTensor.h'>FixedDimTensor.h</a></td><td>100%</td><td><b>66.67%</b></td><td><b>84.62%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/FixedDimTensor.h#L40'>40</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/FixedDimTensor.h#L51'>51</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/LabeledAxis.h'>LabeledAxis.h</a></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/LabeledAxis.h#L139'>139</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/LabeledAxis.h#L142'>142</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/LabeledAxis.h#L145'>145</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/b8fa3610f74f30cb1a59d9940323c4d5035474a1/include/tensors/LabeledMatrix.h'>LabeledMatrix.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/b8fa [...]

2022-12-14 18:52 UTC, hugary1995 commented on src/models/TimeIntegration.cxx
> +#include "models/TimeIntegration.h"
I'll address this in a separate PR.

2022-12-14 18:52 UTC, hugary1995 commented on src/models/solid_mechanics/LinearIsotropicCompliance.cxx
> +  auto S = SymSymR4::init(SymSymR4::FillMethod::isotropic_E_nu, {_E, _nu}).inverse();
oops, forgot about this...

2022-12-14 21:06 UTC, reverendbedford commented
Total Coverage: <b>78.36%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/misc/error.h'>error.h</a></td><td>100%</td><td><b>19.23%</b></td><td><b>35.29%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/misc/error.h#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/misc/error.h#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/misc/error.h#L14'>14</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/misc/error.h#L49'>49</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/misc/error.h#L50'>50</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/misc/error.h#L51'>51</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/misc/error.h#L52'>52</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/misc/error.h#L68'>68</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/misc/error.h#L70'>70</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/misc/error.h#L71'>71</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/misc/error.h#L72'>72</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/misc/utils.h'>utils.h</a></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/misc/utils.h#L33'>33</a></td></tr><tr><td colspan='5'><b>include/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/models/Model.h'>Model.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h'>BatchTensor.h</a></td><td>100%</td><td><b>56.25%</b></td><td><b>62.30%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L107'>107</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L108'>108</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L110'>110</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L112'>112</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L115'>115</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L138'>138</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L140'>140</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L145'>145</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L147'>147</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L152'>152</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L154'>154</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L205'>205</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L207'>207</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L209'>209</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L214'>214</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L215'>215</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L216'>216</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L217'>217</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L239'>239</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L241'>241</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L246'>246</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L248'>248</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/BatchTensor.h#L37'>37</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/FixedDimTensor.h'>FixedDimTensor.h</a></td><td>100%</td><td><b>66.67%</b></td><td><b>84.62%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/FixedDimTensor.h#L40'>40</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/FixedDimTensor.h#L51'>51</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/LabeledAxis.h'>LabeledAxis.h</a></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/LabeledAxis.h#L139'>139</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/LabeledAxis.h#L142'>142</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/LabeledAxis.h#L145'>145</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6536598abbe92d1c539b1e2c721f6b13894e6fb8/include/tensors/LabeledMatrix.h'>LabeledMatrix.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/6536 [...]

2022-12-14 21:49 UTC, hugary1995 commented on src/models/solid_mechanics/LinearIsotropicCompliance.cxx
> +  auto S = SymSymR4::init(SymSymR4::FillMethod::isotropic_E_nu, {_E, _nu}).inverse();
Done

2022-12-14 22:14 UTC, reverendbedford commented
Total Coverage: <b>78.45%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/misc/error.h'>error.h</a></td><td>100%</td><td><b>19.23%</b></td><td><b>35.29%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/misc/error.h#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/misc/error.h#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/misc/error.h#L14'>14</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/misc/error.h#L49'>49</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/misc/error.h#L50'>50</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/misc/error.h#L51'>51</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/misc/error.h#L52'>52</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/misc/error.h#L68'>68</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/misc/error.h#L70'>70</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/misc/error.h#L71'>71</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/misc/error.h#L72'>72</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/misc/utils.h'>utils.h</a></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/misc/utils.h#L33'>33</a></td></tr><tr><td colspan='5'><b>include/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/models/Model.h'>Model.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h'>BatchTensor.h</a></td><td>100%</td><td><b>58.82%</b></td><td><b>66.18%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L110'>110</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L111'>111</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L113'>113</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L115'>115</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L118'>118</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L141'>141</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L143'>143</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L148'>148</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L150'>150</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L155'>155</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L157'>157</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L208'>208</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L210'>210</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L212'>212</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L217'>217</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L218'>218</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L219'>219</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L220'>220</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L258'>258</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L260'>260</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L265'>265</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L267'>267</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/BatchTensor.h#L37'>37</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/FixedDimTensor.h'>FixedDimTensor.h</a></td><td>100%</td><td><b>66.67%</b></td><td><b>84.62%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/FixedDimTensor.h#L40'>40</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/FixedDimTensor.h#L51'>51</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/LabeledAxis.h'>LabeledAxis.h</a></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/LabeledAxis.h#L139'>139</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/LabeledAxis.h#L142'>142</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/LabeledAxis.h#L145'>145</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/c8c0f1b505ae1970a950be941c254318aca8ea01/include/tensors/LabeledMatrix.h'>LabeledMatrix.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/c8c0 [...]

2022-12-14 22:15 UTC, reverendbedford commented
Total Coverage: <b>78.45%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/misc/error.h'>error.h</a></td><td>100%</td><td><b>19.23%</b></td><td><b>35.29%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/misc/error.h#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/misc/error.h#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/misc/error.h#L14'>14</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/misc/error.h#L49'>49</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/misc/error.h#L50'>50</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/misc/error.h#L51'>51</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/misc/error.h#L52'>52</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/misc/error.h#L68'>68</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/misc/error.h#L70'>70</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/misc/error.h#L71'>71</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/misc/error.h#L72'>72</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/misc/utils.h'>utils.h</a></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/misc/utils.h#L33'>33</a></td></tr><tr><td colspan='5'><b>include/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/models/Model.h'>Model.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h'>BatchTensor.h</a></td><td>100%</td><td><b>58.82%</b></td><td><b>66.18%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L110'>110</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L111'>111</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L113'>113</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L115'>115</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L118'>118</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L141'>141</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L143'>143</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L148'>148</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L150'>150</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L155'>155</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L157'>157</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L208'>208</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L210'>210</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L212'>212</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L217'>217</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L218'>218</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L219'>219</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L220'>220</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L258'>258</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L260'>260</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L265'>265</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L267'>267</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/BatchTensor.h#L37'>37</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/FixedDimTensor.h'>FixedDimTensor.h</a></td><td>100%</td><td><b>66.67%</b></td><td><b>84.62%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/FixedDimTensor.h#L40'>40</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/FixedDimTensor.h#L51'>51</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/LabeledAxis.h'>LabeledAxis.h</a></td><td>100%</td><td><b>66.67%</b></td><td><b>76.92%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/LabeledAxis.h#L139'>139</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/LabeledAxis.h#L142'>142</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/LabeledAxis.h#L145'>145</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/4cd79ec23d833ed57d33228cc3e0faba685caa36/include/tensors/LabeledMatrix.h'>LabeledMatrix.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/4cd7 [...]

2022-12-15 13:54 UTC, hugary1995 commented
If you haven't had a chance to review this, I'd like to push another commit. But if you've already started your review, I'll hold that off to the next PR.

2022-12-15 14:11 UTC, hugary1995 commented on include/models/ComposedModel.h
> +                bool wtf);
Ignore the last `bool` argument... I just added it to disambiguate with the existing constructor.
All the `Model`s will have to use the new `declareInputVariable`/`declareOutputVariable` API for automatic dependency resolution to work.

So the plan is:
1. Modify _all_ the existing `Model`s to use the new API.
2. Delete the old `ComposedModel` constructor which requires user-specified dependencies.
3. Remove the temporary bool argument in the new constructor.

2022-12-15 14:32 UTC, reverendbedford commented
Total Coverage: <b>76.67%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/misc/error.h'>error.h</a></td><td>100%</td><td><b>19.23%</b></td><td><b>35.29%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/misc/error.h#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/misc/error.h#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/misc/error.h#L14'>14</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/misc/error.h#L49'>49</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/misc/error.h#L50'>50</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/misc/error.h#L51'>51</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/misc/error.h#L52'>52</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/misc/error.h#L68'>68</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/misc/error.h#L70'>70</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/misc/error.h#L71'>71</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/misc/error.h#L72'>72</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/misc/utils.h'>utils.h</a></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/misc/utils.h#L33'>33</a></td></tr><tr><td colspan='5'><b>include/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/models/Model.h'>Model.h</a></td><td>100%</td><td><b>71.43%</b></td><td><b>71.43%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/models/Model.h#L45'>45</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/models/Model.h#L46'>46</a></td></tr><tr><td colspan='5'><b>include/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h'>BatchTensor.h</a></td><td>100%</td><td><b>58.82%</b></td><td><b>66.18%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L110'>110</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L111'>111</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L113'>113</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L115'>115</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L118'>118</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L141'>141</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L143'>143</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L148'>148</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L150'>150</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L155'>155</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L157'>157</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L208'>208</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L210'>210</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L212'>212</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L217'>217</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L218'>218</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L219'>219</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L220'>220</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L258'>258</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L260'>260</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L265'>265</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L267'>267</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/BatchTensor.h#L37'>37</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/FixedDimTensor.h'>FixedDimTensor.h</a></td><td>100%</td><td><b>66.67%</b></td><td><b>84.62%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/FixedDimTensor.h#L40'>40</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/FixedDimTensor.h#L51'>51</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/LabeledAxis.h'>LabeledAxis.h</a></td><td>100%</td><td><b>60%</b></td><td><b>66.67%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/LabeledAxis.h#L146'>146</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/LabeledAxis.h#L149'>149</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/84981d4c00f0f8a50db9bb817d7e74d413d3d65a/include/tensors/LabeledAxis.h#L152'>152</a>, <a href='https://github.com/reverendbe [...]

2022-12-15 17:20 UTC, reverendbedford requested changes
You may as well just make the driver take a vector of forces as input at this point and we'll just be done with it.  There are also a few minor things scattered around.

2022-12-15 17:20 UTC, reverendbedford commented on include/models/ComposedModel.h
> +                bool wtf);
Sure, let's try to remember to remove it before we release the code...

2022-12-15 17:20 UTC, reverendbedford commented on src/models/IdentityMap.cxx
> +IdentityMap<T>::IdentityMap(const std::string & name,
Is there any easy way to make this recursive on the axes?  Say you want to map

input().subaxis("one").subaxis("two").get<whatever>("var1") 

to

output().subaxis("three").subaxis("four").subaxis("five").get<whatever>("var2")

2022-12-15 17:20 UTC, reverendbedford commented on src/models/solid_mechanics/J2IsotropicYieldFunction.cxx
> +    _g_idx(declareVariable<Scalar>(input(), "state", "isotropic_hardening"))
I will check, but this is recursive on the axis, right?  So you can specify a subsubaxis in the definition?

2022-12-15 17:20 UTC, reverendbedford commented on tests/include/StructuralDriver.h
> +  std::string _driving_force_name;
If you're going this far, why not have the ability to have more than one driving force?  That way temperature is taken care of...

2022-12-15 17:20 UTC, reverendbedford commented on tests/regression/models/solid_mechanics/regression_viscoplasticity.cxx
> +                                      /*verbose=*/true};
Fix.

2022-12-15 17:20 UTC, reverendbedford commented on tests/regression/models/solid_mechanics/regression_viscoplasticity.cxx
> +  auto elasticity = std::make_shared<CauchyStressRateFromElasticStrainRate>("elasticity", C);
This isn't exactly the structure I was thinking of, but it will be okay.  I can make this take a "ElasticityTensor" as input, which is parameterized by parameters (E and nu or whatever).

2022-12-15 17:20 UTC, reverendbedford commented on tests/regression/models/solid_mechanics/regression_viscoplasticity2.cxx
> +#include <catch2/catch.hpp>
Be a bit more descriptive in what is changing instead of `viscoplasticity2`.  Maybe `plastic_strain_viscoplasticity` or something.

2022-12-15 17:20 UTC, reverendbedford commented on tests/src/StructuralDriver.cxx
> +                                   torch::Tensor driving_force,
So just make these vectors of tensors and vectors of strings.

2022-12-15 17:20 UTC, reverendbedford commented on tests/regression/models/solid_mechanics/regression_viscoplasticity.cxx
> +  auto elasticity = std::make_shared<CauchyStressRateFromElasticStrainRate>("elasticity", C);
There is nothing to do here by the way....

2022-12-15 17:25 UTC, hugary1995 commented on src/models/IdentityMap.cxx
> +IdentityMap<T>::IdentityMap(const std::string & name,
Yes, absolutely. The idea is to construct two `LabeledAxisAccessor`s from the input.

2022-12-15 17:26 UTC, hugary1995 commented on src/models/solid_mechanics/J2IsotropicYieldFunction.cxx
> +    _g_idx(declareVariable<Scalar>(input(), "state", "isotropic_hardening"))
Yes. So it could be
```
declareVariable<Scalar>(input(), "state", "substate", "subsubstate", "varname");
```

2022-12-15 17:26 UTC, hugary1995 commented on tests/include/StructuralDriver.h
> +  std::string _driving_force_name;
Good point.

2022-12-15 17:27 UTC, hugary1995 commented on tests/src/StructuralDriver.cxx
> +                                   torch::Tensor driving_force,
yep

2022-12-15 17:27 UTC, hugary1995 commented on tests/regression/models/solid_mechanics/regression_viscoplasticity2.cxx
> +#include <catch2/catch.hpp>
k

2022-12-15 17:27 UTC, hugary1995 commented on tests/regression/models/solid_mechanics/regression_viscoplasticity.cxx
> +                                      /*verbose=*/true};
good catch...

2022-12-15 22:10 UTC, hugary1995 commented on include/models/ComposedModel.h
> +                bool wtf);
1, 2, 3 are all done.

2022-12-15 22:13 UTC, hugary1995 commented on tests/regression/models/solid_mechanics/regression_viscoplasticity2.cxx
> +#include <catch2/catch.hpp>
I renamed it to viscoplasticity_alternative

2022-12-15 22:17 UTC, reverendbedford commented
Total Coverage: <b>77.13%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/misc/error.h'>error.h</a></td><td>100%</td><td><b>19.23%</b></td><td><b>35.29%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/misc/error.h#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/misc/error.h#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/misc/error.h#L14'>14</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/misc/error.h#L49'>49</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/misc/error.h#L50'>50</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/misc/error.h#L51'>51</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/misc/error.h#L52'>52</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/misc/error.h#L68'>68</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/misc/error.h#L70'>70</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/misc/error.h#L71'>71</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/misc/error.h#L72'>72</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/misc/utils.h'>utils.h</a></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/misc/utils.h#L33'>33</a></td></tr><tr><td colspan='5'><b>include/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td><b>87.50%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/models/Model.h'>Model.h</a></td><td>100%</td><td><b>86.36%</b></td><td><b>86.36%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/models/Model.h#L62'>62</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/models/Model.h#L82'>82</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/models/Model.h#L91'>91</a></td></tr><tr><td colspan='5'><b>include/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h'>BatchTensor.h</a></td><td>100%</td><td><b>58.82%</b></td><td><b>66.18%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L110'>110</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L111'>111</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L113'>113</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L115'>115</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L118'>118</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L141'>141</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L143'>143</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L148'>148</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L150'>150</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L155'>155</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L157'>157</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L208'>208</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L210'>210</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L212'>212</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L217'>217</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L218'>218</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L219'>219</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L220'>220</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L258'>258</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L260'>260</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L265'>265</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L267'>267</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/BatchTensor.h#L37'>37</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/FixedDimTensor.h'>FixedDimTensor.h</a></td><td>100%</td><td><b>66.67%</b></td><td><b>84.62%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/FixedDimTensor.h#L40'>40</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/FixedDimTensor.h#L51'>51</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/LabeledAxis.h'>LabeledAxis.h</a></td><td>100%</td><td><b>50%</b></td><td><b>60%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/LabeledAxis.h#L107'>107</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/1cd192001c780304a621c083a76b6a1fefcc2b8e/include/tensors/LabeledAxis.h#L108'>108</a>, <a href='https://github.com/reverendbedfo [...]

2022-12-15 22:26 UTC, hugary1995 commented on tests/src/StructuralDriver.cxx
> +                                   torch::Tensor driving_force,
skipping this one with issue #52

2022-12-15 22:26 UTC, hugary1995 commented on tests/include/StructuralDriver.h
> +  std::string _driving_force_name;
skipping this one with issue #52

2022-12-15 22:43 UTC, reverendbedford commented
Total Coverage: <b>77.24%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/misc/error.h'>error.h</a></td><td>100%</td><td><b>19.23%</b></td><td><b>35.29%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/misc/error.h#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/misc/error.h#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/misc/error.h#L14'>14</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/misc/error.h#L49'>49</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/misc/error.h#L50'>50</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/misc/error.h#L51'>51</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/misc/error.h#L52'>52</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/misc/error.h#L68'>68</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/misc/error.h#L70'>70</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/misc/error.h#L71'>71</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/misc/error.h#L72'>72</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/misc/utils.h'>utils.h</a></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/misc/utils.h#L33'>33</a></td></tr><tr><td colspan='5'><b>include/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/models/Model.h'>Model.h</a></td><td>100%</td><td>100%</td><td><b>86.36%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/models/Model.h#L60'>60</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/models/Model.h#L78'>78</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/models/Model.h#L88'>88</a></td></tr><tr><td colspan='5'><b>include/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h'>BatchTensor.h</a></td><td>100%</td><td><b>58.82%</b></td><td><b>66.18%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L110'>110</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L111'>111</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L113'>113</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L115'>115</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L118'>118</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L141'>141</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L143'>143</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L148'>148</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L150'>150</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L155'>155</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L157'>157</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L208'>208</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L210'>210</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L212'>212</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L217'>217</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L218'>218</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L219'>219</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L220'>220</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L258'>258</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L260'>260</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L265'>265</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L267'>267</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/BatchTensor.h#L37'>37</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/FixedDimTensor.h'>FixedDimTensor.h</a></td><td>100%</td><td><b>66.67%</b></td><td><b>84.62%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/FixedDimTensor.h#L40'>40</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/FixedDimTensor.h#L51'>51</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/LabeledAxis.h'>LabeledAxis.h</a></td><td>100%</td><td><b>50%</b></td><td><b>60%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/LabeledAxis.h#L107'>107</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/fe54b19eb6515fd8fe84ebd40becd329356722ec/include/tensors/LabeledAxis.h#L108'>108</a>, <a href='https://github.com/reverendbedford/batchedmat/blob [...]

2022-12-15 22:44 UTC, reverendbedford commented
Total Coverage: <b>77.24%</b>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/misc/error.h'>error.h</a></td><td>100%</td><td><b>19.23%</b></td><td><b>35.29%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/misc/error.h#L11'>11</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/misc/error.h#L12'>12</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/misc/error.h#L14'>14</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/misc/error.h#L49'>49</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/misc/error.h#L50'>50</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/misc/error.h#L51'>51</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/misc/error.h#L52'>52</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/misc/error.h#L68'>68</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/misc/error.h#L70'>70</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/misc/error.h#L71'>71</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/misc/error.h#L72'>72</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/misc/utils.h'>utils.h</a></td><td>100%</td><td>100%</td><td><b>90%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/misc/utils.h#L33'>33</a></td></tr><tr><td colspan='5'><b>include/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/models/Model.h'>Model.h</a></td><td>100%</td><td>100%</td><td><b>86.36%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/models/Model.h#L60'>60</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/models/Model.h#L78'>78</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/models/Model.h#L88'>88</a></td></tr><tr><td colspan='5'><b>include/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h'>BatchTensor.h</a></td><td>100%</td><td><b>58.82%</b></td><td><b>66.18%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L110'>110</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L111'>111</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L113'>113</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L115'>115</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L118'>118</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L141'>141</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L143'>143</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L148'>148</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L150'>150</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L155'>155</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L157'>157</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L208'>208</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L210'>210</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L212'>212</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L217'>217</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L218'>218</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L219'>219</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L220'>220</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L258'>258</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L260'>260</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L265'>265</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L267'>267</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/BatchTensor.h#L37'>37</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/FixedDimTensor.h'>FixedDimTensor.h</a></td><td>100%</td><td><b>66.67%</b></td><td><b>84.62%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/FixedDimTensor.h#L40'>40</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/FixedDimTensor.h#L51'>51</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/LabeledAxis.h'>LabeledAxis.h</a></td><td>100%</td><td><b>50%</b></td><td><b>60%</b></td><td><a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/LabeledAxis.h#L107'>107</a>, <a href='https://github.com/reverendbedford/batchedmat/blob/0b3574e39510b833d8aa941ebefe63118a16d388/include/tensors/LabeledAxis.h#L108'>108</a>, <a href='https://github.com/reverendbedford/batchedmat/blob [...]

2022-12-15 23:38 UTC, merged