Dynamic, arbitrary batch size
applied-material-modeling/neml2 pull request #85
Opened 2023-09-24 02:37 UTC by hugary1995

- batch dimension no longer templated
- uses CRTP for tensors to do static polymorphism
- many improvements and additions to batch tensor methods
- unified factory methods for batch tensors

In addition:
- clearly defined broadcast rules and helpers
- better utils::add_shapes
- mandel::full_to_mandel and math::mandel_to_full helpers
- vectorized dSymSymR4/dr and dSymR2/dr
- faster and more generic Model::dparam, no longer need to loop over batches
- better utils::finite_differencing_derivatives supporting arbitrarily sized input tensor
- refactored Rot::apply and Rot::dapply, they now belong to each rotatable tensor (and consequently renamed to rotate and drotate)

2023-09-24 02:39 UTC, hugary1995 commented
This is really taking NEML2 to the next level! I'm such a genius.

2023-09-24 04:03 UTC, reverendbedford commented
Coverage after merging <b>runtime_batch</b> into <b>main</b><table><tbody><tr><th>87.88%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>45.45%</b></td><td><b>50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/CrossRef.h#L79'>79</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/CrossRef.h#L88'>88</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/CrossRef.h#L90-L91'>90&ndash;91</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>18.18%</b></td><td><b>56.25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/Factory.h#L105'>105</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/Factory.h#L136-L137'>136&ndash;137</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/Factory.h#L139-L140'>139&ndash;140</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/Factory.h#L143'>143</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/Factory.h#L149'>149</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/ParameterCollection.h'>ParameterCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/ParameterCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/ParameterCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/ParameterInterface.h'>ParameterInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/ParameterSet.h'>ParameterSet.h</a></td><td>100%</td><td><b>25.56%</b></td><td><b>61.22%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/ParameterSet.h#L133'>133</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/ParameterSet.h#L251'>251</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/ParameterSet.h#L253-L254'>253&ndash;254</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/ParameterSet.h#L257'>257</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/ParameterSet.h#L259-L261'>259&ndash;261</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/ParameterSet.h#L265'>265</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/ParameterSet.h#L267-L269'>267&ndash;269</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/ParameterSet.h#L273'>273</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/ParameterSet.h#L275-L278'>275&ndash;278</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/ParameterSet.h#L280'>280</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/ParameterSet.h#L73'>73</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/misc/broadcasting.h'>broadcasting.h</a></td><td>100%</td><td><b>72.58%</b></td><td><b>96.43%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/misc/broadcasting.h#L93'>93</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>34.34%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>76.92%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>47.62%</b></td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/models/ImplicitUpdate.h'>ImplicitUpdate.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/models/LabeledAxisInterface.h#L43'>43</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/models/LabeledAxisInterface.h#L46'>46</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/include/neml2/models/LabeledAxisInterface.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/175cdee3ead4e255c077cfd8802f63e036cec79c/i [...]

2023-09-26 19:08 UTC, reverendbedford commented
Coverage after merging <b>runtime_batch</b> into <b>main</b><table><tbody><tr><th>90.36%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>70.77%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/CrossRef.h#L61-L62'>61&ndash;62</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/CrossRef.h#L64'>64</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>12.90%</b></td><td><b>56.25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/Factory.h#L105'>105</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/Factory.h#L136-L137'>136&ndash;137</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/Factory.h#L139-L140'>139&ndash;140</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/Factory.h#L143'>143</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/Factory.h#L149'>149</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/ParameterCollection.h'>ParameterCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/ParameterCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/ParameterCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/ParameterInterface.h'>ParameterInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/ParameterSet.h'>ParameterSet.h</a></td><td>100%</td><td><b>47.30%</b></td><td><b>61.22%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/ParameterSet.h#L133'>133</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/ParameterSet.h#L251'>251</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/ParameterSet.h#L253-L254'>253&ndash;254</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/ParameterSet.h#L257'>257</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/ParameterSet.h#L259-L261'>259&ndash;261</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/ParameterSet.h#L265'>265</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/ParameterSet.h#L267-L269'>267&ndash;269</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/ParameterSet.h#L273'>273</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/ParameterSet.h#L275-L278'>275&ndash;278</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/ParameterSet.h#L280'>280</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/ParameterSet.h#L73'>73</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>38.66%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>55.74%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>67.89%</b></td><td><b>70.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/misc/utils.h#L167'>167</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/misc/utils.h#L229'>229</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/misc/utils.h#L231-L236'>231&ndash;236</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/misc/utils.h#L257'>257</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/misc/utils.h#L274'>274</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/misc/utils.h#L276-L279'>276&ndash;279</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/models/ImplicitUpdate.h'>ImplicitUpdate.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/dabb476c62d12da5886481bf2bbd7d2c3d85bf9b/include/neml2/models/LabeledAxisInterface.h#L43'>43</a>, <a href='https://github.com/reverendbedford/neml2/blob/dabb47 [...]

2023-09-26 21:26 UTC, reverendbedford commented
Coverage after merging <b>runtime_batch</b> into <b>main</b><table><tbody><tr><th>90.36%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>70.77%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/CrossRef.h#L61-L62'>61&ndash;62</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/CrossRef.h#L64'>64</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>12.90%</b></td><td><b>56.25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/Factory.h#L105'>105</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/Factory.h#L136-L137'>136&ndash;137</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/Factory.h#L139-L140'>139&ndash;140</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/Factory.h#L143'>143</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/Factory.h#L149'>149</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/ParameterCollection.h'>ParameterCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/ParameterCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/ParameterCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/ParameterInterface.h'>ParameterInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/ParameterSet.h'>ParameterSet.h</a></td><td>100%</td><td><b>47.30%</b></td><td><b>61.22%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/ParameterSet.h#L133'>133</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/ParameterSet.h#L251'>251</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/ParameterSet.h#L253-L254'>253&ndash;254</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/ParameterSet.h#L257'>257</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/ParameterSet.h#L259-L261'>259&ndash;261</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/ParameterSet.h#L265'>265</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/ParameterSet.h#L267-L269'>267&ndash;269</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/ParameterSet.h#L273'>273</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/ParameterSet.h#L275-L278'>275&ndash;278</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/ParameterSet.h#L280'>280</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/ParameterSet.h#L73'>73</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>38.66%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>55.74%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>67.89%</b></td><td><b>70.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/misc/utils.h#L167'>167</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/misc/utils.h#L229'>229</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/misc/utils.h#L231-L236'>231&ndash;236</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/misc/utils.h#L257'>257</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/misc/utils.h#L274'>274</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/misc/utils.h#L276-L279'>276&ndash;279</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/models/ImplicitUpdate.h'>ImplicitUpdate.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/37fa6f36d06b1b3f580aa91f9e5cddfde7695887/include/neml2/models/LabeledAxisInterface.h#L43'>43</a>, <a href='https://github.com/reverendbedford/neml2/blob/37fa6f [...]

2023-09-26 22:15 UTC, reverendbedford commented
Coverage after merging <b>runtime_batch</b> into <b>main</b><table><tbody><tr><th>90.20%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>70.77%</b></td><td><b>72.73%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/CrossRef.h#L61-L62'>61&ndash;62</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/CrossRef.h#L64'>64</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>12.90%</b></td><td><b>56.25%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/Factory.h#L105'>105</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/Factory.h#L136-L137'>136&ndash;137</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/Factory.h#L139-L140'>139&ndash;140</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/Factory.h#L143'>143</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/Factory.h#L149'>149</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/ParameterCollection.h'>ParameterCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/ParameterCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/ParameterCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/ParameterInterface.h'>ParameterInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/ParameterSet.h'>ParameterSet.h</a></td><td>100%</td><td><b>47.30%</b></td><td><b>61.22%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/ParameterSet.h#L133'>133</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/ParameterSet.h#L251'>251</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/ParameterSet.h#L253-L254'>253&ndash;254</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/ParameterSet.h#L257'>257</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/ParameterSet.h#L259-L261'>259&ndash;261</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/ParameterSet.h#L265'>265</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/ParameterSet.h#L267-L269'>267&ndash;269</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/ParameterSet.h#L273'>273</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/ParameterSet.h#L275-L278'>275&ndash;278</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/ParameterSet.h#L280'>280</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/ParameterSet.h#L73'>73</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>38.66%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>55.74%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>67.89%</b></td><td><b>70.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/misc/utils.h#L167'>167</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/misc/utils.h#L229'>229</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/misc/utils.h#L231-L236'>231&ndash;236</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/misc/utils.h#L257'>257</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/misc/utils.h#L274'>274</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/misc/utils.h#L276-L279'>276&ndash;279</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/models/ImplicitUpdate.h'>ImplicitUpdate.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/ee4204bbcca9e49638e959700d556ff90e117a83/include/neml2/models/LabeledAxisInterface.h#L43'>43</a>, <a href='https://github.com/reverendbedford/neml2/blob/ee4204 [...]

2023-09-27 02:49 UTC, reverendbedford commented
Coverage after merging <b>runtime_batch</b> into <b>main</b><table><tbody><tr><th>91.37%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>88.46%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>13.33%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/base/ParameterCollection.h'>ParameterCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/base/ParameterCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/base/ParameterCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/base/ParameterInterface.h'>ParameterInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/base/ParameterSet.h'>ParameterSet.h</a></td><td>100%</td><td><b>47.86%</b></td><td><b>92.86%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/base/ParameterSet.h#L133'>133</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/base/ParameterSet.h#L73'>73</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>38.66%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>54.10%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>67.89%</b></td><td><b>70.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/misc/utils.h#L167'>167</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/misc/utils.h#L229'>229</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/misc/utils.h#L231-L236'>231&ndash;236</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/misc/utils.h#L257'>257</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/misc/utils.h#L274'>274</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/misc/utils.h#L276-L279'>276&ndash;279</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/models/ImplicitUpdate.h'>ImplicitUpdate.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/models/LabeledAxisInterface.h#L43'>43</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/models/LabeledAxisInterface.h#L46'>46</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/models/LabeledAxisInterface.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/models/LabeledAxisInterface.h#L53-L56'>53&ndash;56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/models/Model.h'>Model.h</a></td><td>100%</td><td><b>42.86%</b></td><td><b>37.50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/models/Model.h#L168'>168</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/models/Model.h#L170-L173'>170&ndash;173</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/models/Model.h#L195'>195</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/models/Model.h#L197-L200'>197&ndash;200</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/models/Model.h#L218'>218</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/models/Model.h#L220'>220</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/models/Model.h#L58'>58</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/models/Model.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c7779b163c52253/include/neml2/models/Model.h#L68'>68</a></td></tr><tr><td colspan='5'><b>include/neml2/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f8a72a6fff6d6d86db6ac743c77 [...]

2023-09-27 03:22 UTC, reverendbedford commented
Coverage after merging <b>runtime_batch</b> into <b>main</b><table><tbody><tr><th>91.37%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>88.46%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>13.33%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/base/OptionInterface.h'>OptionInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>47.86%</b></td><td><b>92.86%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/base/OptionSet.h#L133'>133</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/base/OptionSet.h#L73'>73</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>38.66%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>54.10%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>67.89%</b></td><td><b>70.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/misc/utils.h#L167'>167</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/misc/utils.h#L229'>229</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/misc/utils.h#L231-L236'>231&ndash;236</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/misc/utils.h#L257'>257</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/misc/utils.h#L274'>274</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/misc/utils.h#L276-L279'>276&ndash;279</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/models/ImplicitUpdate.h'>ImplicitUpdate.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/models/LabeledAxisInterface.h#L43'>43</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/models/LabeledAxisInterface.h#L46'>46</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/models/LabeledAxisInterface.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/models/LabeledAxisInterface.h#L53-L56'>53&ndash;56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/models/Model.h'>Model.h</a></td><td>100%</td><td><b>42.86%</b></td><td><b>37.50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/models/Model.h#L168'>168</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/models/Model.h#L170-L173'>170&ndash;173</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/models/Model.h#L195'>195</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/models/Model.h#L197-L200'>197&ndash;200</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/models/Model.h#L218'>218</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/models/Model.h#L220'>220</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/models/Model.h#L58'>58</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/models/Model.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/models/Model.h#L68'>68</a></td></tr><tr><td colspan='5'><b>include/neml2/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/335e05054ef28f0e94acb74d8c50bbf41aa6f333/include/neml2/ten [...]

2023-09-27 03:25 UTC, reverendbedford commented
Coverage after merging <b>runtime_batch</b> into <b>main</b><table><tbody><tr><th>91.37%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>88.46%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>13.33%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/base/OptionInterface.h'>OptionInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>47.86%</b></td><td><b>92.86%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/base/OptionSet.h#L133'>133</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/base/OptionSet.h#L73'>73</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>38.66%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>54.10%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>67.89%</b></td><td><b>70.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/misc/utils.h#L167'>167</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/misc/utils.h#L229'>229</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/misc/utils.h#L231-L236'>231&ndash;236</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/misc/utils.h#L257'>257</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/misc/utils.h#L274'>274</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/misc/utils.h#L276-L279'>276&ndash;279</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/models/ImplicitUpdate.h'>ImplicitUpdate.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/models/LabeledAxisInterface.h#L43'>43</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/models/LabeledAxisInterface.h#L46'>46</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/models/LabeledAxisInterface.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/models/LabeledAxisInterface.h#L53-L56'>53&ndash;56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/models/Model.h'>Model.h</a></td><td>100%</td><td><b>42.86%</b></td><td><b>37.50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/models/Model.h#L168'>168</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/models/Model.h#L170-L173'>170&ndash;173</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/models/Model.h#L195'>195</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/models/Model.h#L197-L200'>197&ndash;200</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/models/Model.h#L218'>218</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/models/Model.h#L220'>220</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/models/Model.h#L58'>58</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/models/Model.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/models/Model.h#L68'>68</a></td></tr><tr><td colspan='5'><b>include/neml2/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/e3cf20f792da1199f7eae84346a1064aa0a22ff4/include/neml2/ten [...]

2023-09-27 18:22 UTC, reverendbedford commented
Coverage after merging <b>runtime_batch</b> into <b>main</b><table><tbody><tr><th>91.37%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>88.46%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>13.33%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/base/OptionInterface.h'>OptionInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>47.86%</b></td><td><b>92.86%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/base/OptionSet.h#L133'>133</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/base/OptionSet.h#L73'>73</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>38.66%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>54.10%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>67.89%</b></td><td><b>70.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/misc/utils.h#L167'>167</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/misc/utils.h#L229'>229</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/misc/utils.h#L231-L236'>231&ndash;236</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/misc/utils.h#L257'>257</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/misc/utils.h#L274'>274</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/misc/utils.h#L276-L279'>276&ndash;279</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/models/ImplicitUpdate.h'>ImplicitUpdate.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/models/LabeledAxisInterface.h#L43'>43</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/models/LabeledAxisInterface.h#L46'>46</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/models/LabeledAxisInterface.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/models/LabeledAxisInterface.h#L53-L56'>53&ndash;56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/models/Model.h'>Model.h</a></td><td>100%</td><td><b>42.86%</b></td><td><b>37.50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/models/Model.h#L168'>168</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/models/Model.h#L170-L173'>170&ndash;173</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/models/Model.h#L195'>195</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/models/Model.h#L197-L200'>197&ndash;200</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/models/Model.h#L218'>218</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/models/Model.h#L220'>220</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/models/Model.h#L58'>58</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/models/Model.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/models/Model.h#L68'>68</a></td></tr><tr><td colspan='5'><b>include/neml2/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/c4ddf66038e559f88a554adc7ef2c9a22f16fadf/include/neml2/ten [...]

2023-09-27 19:37 UTC, reverendbedford requested changes
List of things I've found:
- Need to add `syntax.yml` to `.gitignore` and get rid of it from the repo
- For `R2`, `R3`, `R4`, `R5`, `Rot`, `Scalar`, `SR2`, `SSFR5`,  `SSR4`, and `Vec` add the helpful doc comment like you did for `SFR3` giving the logical storage space.
- I looked at `math.cxx` but don't see any immediate way to improve what you have there.

I mean I've spent 2 hours on this (plus playing with VS Code...) and I can't see much to improve.  Very good work.

2023-09-27 21:35 UTC, reverendbedford commented
Coverage after merging <b>runtime_batch</b> into <b>main</b><table><tbody><tr><th>91.37%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>88.46%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>13.33%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/base/OptionInterface.h'>OptionInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>47.86%</b></td><td><b>92.86%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/base/OptionSet.h#L133'>133</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/base/OptionSet.h#L73'>73</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>38.66%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>54.10%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>67.89%</b></td><td><b>70.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/misc/utils.h#L167'>167</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/misc/utils.h#L229'>229</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/misc/utils.h#L231-L236'>231&ndash;236</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/misc/utils.h#L257'>257</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/misc/utils.h#L274'>274</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/misc/utils.h#L276-L279'>276&ndash;279</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/models/ImplicitUpdate.h'>ImplicitUpdate.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/models/LabeledAxisInterface.h#L43'>43</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/models/LabeledAxisInterface.h#L46'>46</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/models/LabeledAxisInterface.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/models/LabeledAxisInterface.h#L53-L56'>53&ndash;56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/models/Model.h'>Model.h</a></td><td>100%</td><td><b>42.86%</b></td><td><b>37.50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/models/Model.h#L168'>168</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/models/Model.h#L170-L173'>170&ndash;173</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/models/Model.h#L195'>195</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/models/Model.h#L197-L200'>197&ndash;200</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/models/Model.h#L218'>218</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/models/Model.h#L220'>220</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/models/Model.h#L58'>58</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/models/Model.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/models/Model.h#L68'>68</a></td></tr><tr><td colspan='5'><b>include/neml2/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/2957a5368c6d23b0994291f58f2465f7c9f79f6c/include/neml2/ten [...]

2023-09-27 22:03 UTC, hugary1995 commented on .gitignore
> +tests/syntax.yml
Do we need both?

2023-09-27 22:03 UTC, hugary1995 commented on .gitmodules
> +	url = git@github.com:gperftools/gperftools.git
If we are building gperftools we might want to `ignore = dirty`

2023-09-27 22:03 UTC, hugary1995 commented on tests/CMakeLists.txt
>        # target_link_libraries(profiling_tests profiler)
Remove this commented line.

2023-09-27 22:05 UTC, hugary1995 commented
We don't have to build tcmalloc if that's the only issue...

2023-09-28 00:29 UTC, reverendbedford approved these changes

2023-09-28 00:46 UTC, reverendbedford commented
Coverage after merging <b>runtime_batch</b> into <b>main</b><table><tbody><tr><th>91.37%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>88.46%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>13.33%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/base/OptionInterface.h'>OptionInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>47.86%</b></td><td><b>92.86%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/base/OptionSet.h#L133'>133</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/base/OptionSet.h#L73'>73</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>38.66%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>54.10%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>67.89%</b></td><td><b>70.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/misc/utils.h#L167'>167</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/misc/utils.h#L229'>229</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/misc/utils.h#L231-L236'>231&ndash;236</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/misc/utils.h#L257'>257</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/misc/utils.h#L274'>274</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/misc/utils.h#L276-L279'>276&ndash;279</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/models/ImplicitUpdate.h'>ImplicitUpdate.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/models/LabeledAxisInterface.h#L43'>43</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/models/LabeledAxisInterface.h#L46'>46</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/models/LabeledAxisInterface.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/models/LabeledAxisInterface.h#L53-L56'>53&ndash;56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/models/Model.h'>Model.h</a></td><td>100%</td><td><b>42.86%</b></td><td><b>37.50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/models/Model.h#L168'>168</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/models/Model.h#L170-L173'>170&ndash;173</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/models/Model.h#L195'>195</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/models/Model.h#L197-L200'>197&ndash;200</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/models/Model.h#L218'>218</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/models/Model.h#L220'>220</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/models/Model.h#L58'>58</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/models/Model.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/models/Model.h#L68'>68</a></td></tr><tr><td colspan='5'><b>include/neml2/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/1f67509f38523fb28c464019d4b452134fa15736/include/neml2/ten [...]

2023-09-28 01:07 UTC, reverendbedford commented
Coverage after merging <b>runtime_batch</b> into <b>main</b><table><tbody><tr><th>91.37%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>88.46%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>13.33%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/base/OptionInterface.h'>OptionInterface.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>47.86%</b></td><td><b>92.86%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/base/OptionSet.h#L133'>133</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/base/OptionSet.h#L73'>73</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>38.66%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>54.10%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>67.89%</b></td><td><b>70.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/misc/utils.h#L167'>167</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/misc/utils.h#L229'>229</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/misc/utils.h#L231-L236'>231&ndash;236</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/misc/utils.h#L257'>257</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/misc/utils.h#L274'>274</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/misc/utils.h#L276-L279'>276&ndash;279</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/models/ImplicitUpdate.h'>ImplicitUpdate.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/models/LabeledAxisInterface.h#L43'>43</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/models/LabeledAxisInterface.h#L46'>46</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/models/LabeledAxisInterface.h#L51'>51</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/models/LabeledAxisInterface.h#L53-L56'>53&ndash;56</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/models/Model.h'>Model.h</a></td><td>100%</td><td><b>42.86%</b></td><td><b>37.50%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/models/Model.h#L168'>168</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/models/Model.h#L170-L173'>170&ndash;173</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/models/Model.h#L195'>195</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/models/Model.h#L197-L200'>197&ndash;200</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/models/Model.h#L218'>218</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/models/Model.h#L220'>220</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/models/Model.h#L58'>58</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/models/Model.h#L62'>62</a>, <a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/models/Model.h#L68'>68</a></td></tr><tr><td colspan='5'><b>include/neml2/tensors</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/3329158dda579bee32829dc201605b10f274d856/include/neml2/ten [...]

2023-09-28 01:29 UTC, merged