Add generic nonlinear parameters
applied-material-modeling/neml2 pull request #94
Opened 2023-10-03 21:52 UTC by hugary1995

1. neml2::Model no longer derives from torch::nn::Module
2. Due to 1, I added a parameter store and a buffer store mimicking torch::nn::Module
3. Our parameter(buffer) store is more powerful as values are polymorphic on neml2::BatchTensorBase, i.e. we don't lose batch information by registering parameters/buffers
4. Unified register_model_parameter and register_crossref_model_parameter into declare_parameter<T>, where T is the plain tensor type.
5. Our declare_parameter<T> is very powerful as it handles plain tensor type, cross-reference of a tensor, and cross-reference of a nonlinear parameter
6. By "nonlinear parameters" I mean parameters that are functions of state or forces.
7. There is a base class for all nonlinear parameters: NonlinearParameter<T>, templated on the tensor type. It derives from neml2::Model, so all the good things about dependency resolution and automatic chain rule carry over.
8. A special type nonlinear parameter is Interpolation<T> which interpolates a parameter of type T given a Scalar.
9. Added a unit test to check the derivative when a nonlinear parameter is present.
10. Most interestingly, it turns out that we can be smart about LabeledMatrix::fill and speed things up by a factor of 2x. The magic is in LabeledAxis::common_indices
11. Bump cmake version, remove policy warning

close #87
ref #88

2023-10-03 21:58 UTC, hugary1995 commented
sigh, pre-cxx11 is inconvenient...

2023-10-04 02:09 UTC, reverendbedford commented
Coverage after merging <b>interpolator</b> into <b>main</b><table><tbody><tr><th>90.34%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>88.46%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.54%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>25%</b></td><td><b>33.33%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/base/NEML2Object.h#L52'>52</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>42.70%</b></td><td><b>92.86%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/base/OptionSet.h#L133'>133</a>, <a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/base/OptionSet.h#L73'>73</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>96.53%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/base/UniqueVector.h'>UniqueVector.h</a></td><td>100%</td><td><b>23.81%</b></td><td><b>83.33%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/base/UniqueVector.h#L169'>169</a>, <a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/base/UniqueVector.h#L171-L172'>171&ndash;172</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>36.82%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>54.10%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>67.89%</b></td><td><b>70.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/misc/utils.h#L167'>167</a>, <a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/misc/utils.h#L233'>233</a>, <a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/misc/utils.h#L235-L240'>235&ndash;240</a>, <a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/misc/utils.h#L261'>261</a>, <a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/misc/utils.h#L278'>278</a>, <a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/misc/utils.h#L280-L283'>280&ndash;283</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/models/ImplicitUpdate.h'>ImplicitUpdate.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/models/LabeledAxisInterface.h#L43'>43</a>, <a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/models/LabeledAxisInterface.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/models/LabeledAxisInterface.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/models/LabeledAxisInterface.h#L52-L53'>52&ndash;53</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/models/LinearInterpolation.h'>LinearInterpolation.h</a></td><td>100%</td><td><b>14.29%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/models/Model.h'>Model.h</a></td><td>100%</td><td><b>11.50%</b></td><td><b>65.45%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/models/Model.h#L196'>196</a>, <a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b810ea/include/neml2/models/Model.h#L198-L201'>198&ndash;201</a>, <a href='https://github.com/reverendbedford/neml2/blob/241c88a04752c90aabff88a6cfb9212bc7b [...]

2023-10-05 14:35 UTC, reverendbedford requested changes
Some minor comments, plus:
1. Do you actually have a unit test to check the correctness of the `LinearInterpolation` object by itself (ideally for several combinations of x/y batch sizes)?
2. We should add a model with interpolated parameters to the regression suite.

2023-10-05 14:35 UTC, reverendbedford commented on CMakeLists.txt
> +      Set(FETCHCONTENT_QUIET FALSE)
What does this do?  Also should use `set` (lowercase) to avoid giving me an aneurysm.

2023-10-05 14:35 UTC, reverendbedford commented on include/neml2/models/LinearInterpolation.h
> +template <typename T>
You probably need to document this, at least a little...

2023-10-05 14:35 UTC, reverendbedford commented on src/neml2/misc/math.cxx
> +  neml_assert(p.batch_dim() == 0 || out.batch_sizes() == p.batch_sizes(),
Do we want this to be `neml_assert` or `neml_assert_debug`?

2023-10-05 14:35 UTC, reverendbedford commented on src/neml2/models/Interpolation.cxx
> +template <typename T>
Definitely need documentation for this class...

2023-10-05 14:35 UTC, reverendbedford commented on src/neml2/models/LinearInterpolation.cxx
> +template <typename T>
Does this really work for arbitrary batch sizes?  Cases:
1. `y` has fewer batch dims than `x`
2. `x` has fewer batch dims than `y`

2023-10-05 14:35 UTC, reverendbedford commented on src/neml2/models/solid_mechanics/Normality.cxx
> +    declare_output_variable(to[i], sz);
Err, you changed the function order?

2023-10-05 14:35 UTC, reverendbedford commented on src/neml2/models/solid_mechanics/TotalStrain.cxx
> +  options.set<LabeledAxisAccessor>("total_strain") = vecstr{"state", "E"};
Maybe I missed it, but what is the point of `vecstr`?

2023-10-05 14:38 UTC, hugary1995 commented on CMakeLists.txt
> +      Set(FETCHCONTENT_QUIET FALSE)
This prints out download progress to the console like `[download 50%]`. Without this I get an awkward silence while downloading libtorch using my slow home internet.

2023-10-05 14:38 UTC, hugary1995 commented on include/neml2/models/LinearInterpolation.h
> +template <typename T>
whoops yes

2023-10-05 14:39 UTC, hugary1995 commented on src/neml2/misc/math.cxx
> +  neml_assert(p.batch_dim() == 0 || out.batch_sizes() == p.batch_sizes(),
ya, probably `neml_assert_dbg`.

2023-10-05 14:39 UTC, hugary1995 commented on src/neml2/models/Interpolation.cxx
> +template <typename T>
yep

2023-10-05 14:40 UTC, hugary1995 commented on src/neml2/models/solid_mechanics/Normality.cxx
> +    declare_output_variable(to[i], sz);
I'm open to either way. This is just my personal preference.

2023-10-05 14:46 UTC, hugary1995 commented on src/neml2/models/solid_mechanics/TotalStrain.cxx
> +  options.set<LabeledAxisAccessor>("total_strain") = vecstr{"state", "E"};
This is the annoyance of working with both pre-cxx11 abi and cxx11 abi. The root cause of the issue (unrelated to string abi) is:
- We now have a constructor for `LabeledAxisAccessor` that takes a string and another constructor that takes a vector of strings.
- On this line, we are providing an initializer list on the RHS.
- The RHS need exactly one implicit conversion to become a vector string (this is the obvious case)
- The RHS also need exactly one implicit conversion to become a string. This is a bit unusual, but there is indeed a constructor for `std::string` that takes 2 `char *`s.
- Therefore, there is an ambiguity. Note that this ambiguity only occurs when we provide exactly 2 strings in the initializer list.

With cxx11 abi, we could use string literal operators and just do `{"state"s, "E"s}` to disambiguate. But this string literal operator does not exist in the pre-cxx11 abi. Hence this `vecstr` workaround.

2023-10-05 14:49 UTC, hugary1995 commented
> Some minor comments, plus:
> 
> 1. Do you actually have a unit test to check the correctness of the `LinearInterpolation` object by itself (ideally for several combinations of x/y batch sizes)?

Yes, there is a `ScalarLinearInterpolation.i` and a `SR2LinearInterpolation.i`, but I'll add batched and unbatched versions.

> 2. We should add a model with interpolated parameters to the regression suite.

Yes, will do.

2023-10-05 17:36 UTC, reverendbedford commented
Coverage after merging <b>interpolator</b> into <b>main</b><table><tbody><tr><th>90.31%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>88.46%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.54%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>25%</b></td><td><b>33.33%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/base/NEML2Object.h#L52'>52</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>42.70%</b></td><td><b>92.86%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/base/OptionSet.h#L133'>133</a>, <a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/base/OptionSet.h#L73'>73</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>96.53%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/base/UniqueVector.h'>UniqueVector.h</a></td><td>100%</td><td><b>23.81%</b></td><td><b>83.33%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/base/UniqueVector.h#L169'>169</a>, <a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/base/UniqueVector.h#L171-L172'>171&ndash;172</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>36.82%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>54.10%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>67.89%</b></td><td><b>70.83%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/misc/utils.h#L167'>167</a>, <a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/misc/utils.h#L233'>233</a>, <a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/misc/utils.h#L235-L240'>235&ndash;240</a>, <a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/misc/utils.h#L261'>261</a>, <a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/misc/utils.h#L278'>278</a>, <a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/misc/utils.h#L280-L283'>280&ndash;283</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/models/ImplicitUpdate.h'>ImplicitUpdate.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/models/LabeledAxisInterface.h#L43'>43</a>, <a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/models/LabeledAxisInterface.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/models/LabeledAxisInterface.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/models/LabeledAxisInterface.h#L52-L53'>52&ndash;53</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/models/LinearInterpolation.h'>LinearInterpolation.h</a></td><td>100%</td><td><b>14.29%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/models/Model.h'>Model.h</a></td><td>100%</td><td><b>11.50%</b></td><td><b>65.45%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/models/Model.h#L196'>196</a>, <a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff055afb8/include/neml2/models/Model.h#L198-L201'>198&ndash;201</a>, <a href='https://github.com/reverendbedford/neml2/blob/15b33c36d439c3cff4ccdbb9d31f16aff05 [...]

2023-10-05 19:49 UTC, hugary1995 commented on src/neml2/models/LinearInterpolation.cxx
> +template <typename T>
I added 4 examples in `LinearInterpolation.h`. I then added 8 unit tests (4 for Scalar, 4 for SR2) corresponding to those 4 examples. They are
1. ScalarLinearInterpolation1.i
2. ScalarLinearInterpolation2.i
3. ScalarLinearInterpolation3.i
4. ScalarLinearInterpolation4.i
5. SR2LinearInterpolation1.i
6. SR2LinearInterpolation2.i
7. SR2LinearInterpolation3.i
8. SR2LinearInterpolation4.i

2023-10-05 19:51 UTC, hugary1995 commented
The NonlinearParameter.i unit test is already testing the chain rule with interpolations. I'll add regression tests as I work on #88.

2023-10-05 20:46 UTC, reverendbedford commented
Coverage after merging <b>interpolator</b> into <b>main</b><table><tbody><tr><th>90.37%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='5'><b>include/neml2/base</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/base/CrossRef.h'>CrossRef.h</a></td><td>100%</td><td><b>88.46%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/base/Factory.h'>Factory.h</a></td><td>100%</td><td><b>11.54%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/base/NEML2Object.h'>NEML2Object.h</a></td><td>100%</td><td><b>25%</b></td><td><b>33.33%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/base/NEML2Object.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/base/NEML2Object.h#L52'>52</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/base/OptionCollection.h'>OptionCollection.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/base/OptionCollection.h#L40'>40</a>, <a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/base/OptionCollection.h#L49'>49</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/base/OptionSet.h'>OptionSet.h</a></td><td>100%</td><td><b>45.69%</b></td><td><b>92.86%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/base/OptionSet.h#L133'>133</a>, <a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/base/OptionSet.h#L73'>73</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/base/Registry.h'>Registry.h</a></td><td>100%</td><td><b>96.53%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/base/UniqueVector.h'>UniqueVector.h</a></td><td>100%</td><td><b>23.81%</b></td><td><b>83.33%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/base/UniqueVector.h#L169'>169</a>, <a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/base/UniqueVector.h#L171-L172'>171&ndash;172</a></td></tr><tr><td colspan='5'><b>include/neml2/drivers</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/drivers/Driver.h'>Driver.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/drivers/Driver.h#L56'>56</a></td></tr><tr><td colspan='5'><b>include/neml2/misc</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/misc/error.h'>error.h</a></td><td>100%</td><td><b>37.44%</b></td><td><b>82.35%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/misc/error.h#L35-L36'>35&ndash;36</a>, <a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/misc/error.h#L38'>38</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/misc/math.h'>math.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/misc/parser_utils.h'>parser_utils.h</a></td><td>100%</td><td><b>54.10%</b></td><td><b>88%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/misc/parser_utils.h#L37-L38'>37&ndash;38</a>, <a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/misc/parser_utils.h#L40'>40</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/misc/utils.h'>utils.h</a></td><td>100%</td><td><b>68.47%</b></td><td><b>76.27%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/misc/utils.h#L173'>173</a>, <a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/misc/utils.h#L239'>239</a>, <a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/misc/utils.h#L241-L246'>241&ndash;246</a>, <a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/misc/utils.h#L267'>267</a>, <a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/misc/utils.h#L302'>302</a>, <a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/misc/utils.h#L304-L307'>304&ndash;307</a></td></tr><tr><td colspan='5'><b>include/neml2/models</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/models/ImplicitUpdate.h'>ImplicitUpdate.h</a></td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/models/LabeledAxisInterface.h'>LabeledAxisInterface.h</a></td><td>100%</td><td><b>0%</b></td><td><b>0%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/models/LabeledAxisInterface.h#L43'>43</a>, <a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/models/LabeledAxisInterface.h#L45'>45</a>, <a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/models/LabeledAxisInterface.h#L50'>50</a>, <a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/models/LabeledAxisInterface.h#L52-L53'>52&ndash;53</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/models/LinearInterpolation.h'>LinearInterpolation.h</a></td><td>100%</td><td><b>14.29%</b></td><td>100%</td><td></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/models/Model.h'>Model.h</a></td><td>100%</td><td><b>11.50%</b></td><td><b>65.45%</b></td><td><a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/models/Model.h#L196'>196</a>, <a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a702fbe/include/neml2/models/Model.h#L198-L201'>198&ndash;201</a>, <a href='https://github.com/reverendbedford/neml2/blob/66224da234c9848e27803206de73ec4b8a7 [...]

2023-10-06 13:20 UTC, reverendbedford commented on src/neml2/models/solid_mechanics/Normality.cxx
> +    declare_output_variable(to[i], sz);
That's fine, just wondering if there was a real reason...

2023-10-06 13:20 UTC, reverendbedford commented on src/neml2/models/solid_mechanics/TotalStrain.cxx
> +  options.set<LabeledAxisAccessor>("total_strain") = vecstr{"state", "E"};
Okay then, I guess I didn't want to know.

2023-10-06 13:21 UTC, reverendbedford approved these changes

2023-10-06 13:22 UTC, merged